/**
 * Massive Pool of 200+ Verified Science Questions
 * Categories: Biology, Chemistry, Physics, Earth Science
 * Difficulties: EASY, MEDIUM, HARD, CHALLENGE
 */

import { ScienceQuestion } from './science-quiz'

export const SCIENCE_QUESTIONS_POOL: Omit<ScienceQuestion, 'id' | 'type' | 'timeLimit' | 'points'>[] = [
    // --- BIOLOGY ---
    // EASY
    { difficulty: 'EASY', content: { topic: 'biology', question: 'What is the control center of a cell?' }, correctAnswer: 0, options: ['Nucleus', 'Ribosome', 'Mitochondria', 'Vacuole'] },
    { difficulty: 'EASY', content: { topic: 'biology', question: 'Which blood cells fight infection?' }, correctAnswer: 1, options: ['Red Blood Cells', 'White Blood Cells', 'Platelets', 'Plasma'] },
    { difficulty: 'EASY', content: { topic: 'biology', question: 'What pigment gives plants their green color?' }, correctAnswer: 2, options: ['Melanin', 'Hemoglobin', 'Chlorophyll', 'Carotene'] },
    { difficulty: 'EASY', content: { topic: 'biology', question: 'What is the largest bone in the human body?' }, correctAnswer: 0, options: ['Femur', 'Tibia', 'Humerus', 'Skull'] },
    { difficulty: 'EASY', content: { topic: 'biology', question: 'Which organ pumps blood throughout the body?' }, correctAnswer: 3, options: ['Liver', 'Lungs', 'Kidney', 'Heart'] },
    { difficulty: 'EASY', content: { topic: 'biology', question: 'What do pandas primarily eat?' }, correctAnswer: 1, options: ['Fish', 'Bamboo', 'Insects', 'Meat'] },
    { difficulty: 'EASY', content: { topic: 'biology', question: 'How many legs does a spider have?' }, correctAnswer: 2, options: ['6', '4', '8', '10'] },
    { difficulty: 'EASY', content: { topic: 'biology', question: 'What is the process of a caterpillar turning into a butterfly?' }, correctAnswer: 0, options: ['Metamorphosis', 'Photosynthesis', 'Evolution', 'Germination'] },
    { difficulty: 'EASY', content: { topic: 'biology', question: 'Which animals lay eggs?' }, correctAnswer: 3, options: ['Mammals', 'Humans', 'Whales', 'Birds'] },
    { difficulty: 'EASY', content: { topic: 'biology', question: 'What gas do humans exhale?' }, correctAnswer: 1, options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Helium'] },
    { difficulty: 'EASY', content: { topic: 'biology', question: 'What is the largest land animal?' }, correctAnswer: 2, options: ['Lion', 'Hippo', 'Elephant', 'Rhino'] },
    { difficulty: 'EASY', content: { topic: 'biology', question: 'Which sense is most developed in dogs?' }, correctAnswer: 0, options: ['Smell', 'Sight', 'Hearing', 'Taste'] },
    { difficulty: 'EASY', content: { topic: 'biology', question: 'What part of the plant conducts photosynthesis?' }, correctAnswer: 1, options: ['Root', 'Leaf', 'Stem', 'Flower'] },
    { difficulty: 'EASY', content: { topic: 'biology', question: 'How many chambers does the human heart have?' }, correctAnswer: 2, options: ['Two', 'Three', 'Four', 'Six'] },
    { difficulty: 'EASY', content: { topic: 'biology', question: 'Which bird cannot fly?' }, correctAnswer: 3, options: ['Eagle', 'Sparrow', 'Hawk', 'Penguin'] },

    // MEDIUM
    { difficulty: 'MEDIUM', content: { topic: 'biology', question: 'Which vitamin is produced when skin is exposed to sunlight?' }, correctAnswer: 2, options: ['Vitamin A', 'Vitamin C', 'Vitamin D', 'Vitamin B12'] },
    { difficulty: 'MEDIUM', content: { topic: 'biology', question: 'What is the genetic material in humans?' }, correctAnswer: 0, options: ['DNA', 'RNA', 'ATP', 'Protein'] },
    { difficulty: 'MEDIUM', content: { topic: 'biology', question: 'Which part of the brain controls balance?' }, correctAnswer: 1, options: ['Cerebrum', 'Cerebellum', 'Brain Stem', 'Thalamus'] },
    { difficulty: 'MEDIUM', content: { topic: 'biology', question: 'What structures carry oxygen in red blood cells?' }, correctAnswer: 3, options: ['Insulin', 'Keratin', 'Collagen', 'Hemoglobin'] },
    { difficulty: 'MEDIUM', content: { topic: 'biology', question: 'Which organ filters waste from the blood?' }, correctAnswer: 0, options: ['Kidneys', 'Stomach', 'Pancreas', 'Gallladder'] },
    { difficulty: 'MEDIUM', content: { topic: 'biology', question: 'What is the largest organ of the human body?' }, correctAnswer: 2, options: ['Liver', 'Intestines', 'Skin', 'Lungs'] },
    { difficulty: 'MEDIUM', content: { topic: 'biology', question: 'Which blood type is the universal donor?' }, correctAnswer: 1, options: ['AB+', 'O-', 'A+', 'B-'] },
    { difficulty: 'MEDIUM', content: { topic: 'biology', question: 'What connects muscles to bones?' }, correctAnswer: 0, options: ['Tendons', 'Ligaments', 'Cartilage', 'Joints'] },
    { difficulty: 'MEDIUM', content: { topic: 'biology', question: 'Which part of the plant absorbs water?' }, correctAnswer: 3, options: ['Leaves', 'Stem', 'Flower', 'Roots'] },
    { difficulty: 'MEDIUM', content: { topic: 'biology', question: 'What is the study of fossils called?' }, correctAnswer: 2, options: ['Biology', 'Geology', 'Paleontology', 'Archaeology'] },
    { difficulty: 'MEDIUM', content: { topic: 'biology', question: 'Which structure protects the brain?' }, correctAnswer: 0, options: ['Skull', 'Ribcage', 'Spine', 'Pelvis'] },
    { difficulty: 'MEDIUM', content: { topic: 'biology', question: 'What is the powerhouse of the cell?' }, correctAnswer: 1, options: ['Nucleus', 'Mitochondria', 'Ribosome', 'Golgi Body'] },
    { difficulty: 'MEDIUM', content: { topic: 'biology', question: 'Which animal group are snakes in?' }, correctAnswer: 2, options: ['Amphibians', 'Mammals', 'Reptiles', 'Fish'] },
    { difficulty: 'MEDIUM', content: { topic: 'biology', question: 'What is the name of the tube that carries food to the stomach?' }, correctAnswer: 3, options: ['Trachea', 'Larynx', 'Bronchus', 'Esophagus'] },
    { difficulty: 'MEDIUM', content: { topic: 'biology', question: 'What is the liquid part of blood called?' }, correctAnswer: 0, options: ['Plasma', 'Platelets', 'Serum', 'Lymph'] },

    // HARD
    { difficulty: 'HARD', content: { topic: 'biology', question: 'Which process divides one cell into two identical cells?' }, correctAnswer: 0, options: ['Mitosis', 'Meiosis', 'Fusion', 'Fission'] },
    { difficulty: 'HARD', content: { topic: 'biology', question: 'What is the basic unit of heredity?' }, correctAnswer: 1, options: ['Chromosome', 'Gene', 'Nucleus', 'Protein'] },
    { difficulty: 'HARD', content: { topic: 'biology', question: 'Which hormone regulates blood sugar levels?' }, correctAnswer: 2, options: ['Adrenaline', 'Thyroxine', 'Insulin', 'Estrogen'] },
    { difficulty: 'HARD', content: { topic: 'biology', question: 'What are the building blocks of proteins?' }, correctAnswer: 3, options: ['Sugars', 'Fats', 'Nucleotides', 'Amino Acids'] },
    { difficulty: 'HARD', content: { topic: 'biology', question: 'Which scientist proposed the theory of evolution by natural selection?' }, correctAnswer: 0, options: ['Darwin', 'Mendel', 'Pasteur', 'Newton'] },
    { difficulty: 'HARD', content: { topic: 'biology', question: 'What type of blood vessel carries blood away from the heart?' }, correctAnswer: 1, options: ['Veins', 'Arteries', 'Capillaries', 'Venules'] },
    { difficulty: 'HARD', content: { topic: 'biology', question: 'Which organ produces bile?' }, correctAnswer: 2, options: ['Pancreas', 'Stomach', 'Liver', 'Gallladder'] },
    { difficulty: 'HARD', content: { topic: 'biology', question: 'What is the outer layer of skin called?' }, correctAnswer: 0, options: ['Epidermis', 'Dermis', 'Hypodermis', 'Cuticle'] },
    { difficulty: 'HARD', content: { topic: 'biology', question: 'Which animal group includes frogs and salamanders?' }, correctAnswer: 3, options: ['Reptiles', 'Mammals', 'Fish', 'Amphibians'] },
    { difficulty: 'HARD', content: { topic: 'biology', question: 'What is the term for animals that eat both plants and meat?' }, correctAnswer: 1, options: ['Carnivore', 'Omnivore', 'Herbivore', 'Detritivore'] },
    { difficulty: 'HARD', content: { topic: 'biology', question: 'What part of the brain controls memory?' }, correctAnswer: 2, options: ['Cerebellum', 'Brain Stem', 'Hippocampus', 'Thalamus'] },
    { difficulty: 'HARD', content: { topic: 'biology', question: 'Which cell organelle makes proteins?' }, correctAnswer: 3, options: ['Lysosome', 'Vacuole', 'Golgi', 'Ribosome'] },
    { difficulty: 'HARD', content: { topic: 'biology', question: 'What is the most abundant protein in the human body?' }, correctAnswer: 0, options: ['Collagen', 'Keratin', 'Elastin', 'Actin'] },
    { difficulty: 'HARD', content: { topic: 'biology', question: 'Which disease is caused by a lack of Vitamin C?' }, correctAnswer: 1, options: ['Rickets', 'Scurvy', 'Beriberi', 'Pellegra'] },
    { difficulty: 'HARD', content: { topic: 'biology', question: 'What is the smallest bone in the human body?' }, correctAnswer: 2, options: ['Incus', 'Malleus', 'Stapes', 'Patella'] },

    // --- CHEMISTRY ---
    // EASY
    { difficulty: 'EASY', content: { topic: 'chemistry', question: 'What is the chemical symbol for Gold?' }, correctAnswer: 0, options: ['Au', 'Ag', 'Fe', 'Cu'] },
    { difficulty: 'EASY', content: { topic: 'chemistry', question: 'What is the chemical symbol for Oxygen?' }, correctAnswer: 1, options: ['Ox', 'O', 'Om', 'On'] },
    { difficulty: 'EASY', content: { topic: 'chemistry', question: 'What is H2O commonly known as?' }, correctAnswer: 2, options: ['Salt', 'Air', 'Water', 'Ice'] },
    { difficulty: 'EASY', content: { topic: 'chemistry', question: 'Which gas do balloons float with?' }, correctAnswer: 3, options: ['Oxygen', 'Nitrogen', 'Carbon', 'Helium'] },
    { difficulty: 'EASY', content: { topic: 'chemistry', question: 'What state of matter is ice?' }, correctAnswer: 0, options: ['Solid', 'Liquid', 'Gas', 'Plasma'] },
    { difficulty: 'EASY', content: { topic: 'chemistry', question: 'What is the pH of pure water?' }, correctAnswer: 1, options: ['5', '7', '9', '14'] },
    { difficulty: 'EASY', content: { topic: 'chemistry', question: 'Which element is needed for strong bones?' }, correctAnswer: 2, options: ['Iron', 'Potassium', 'Calcium', 'Zinc'] },
    { difficulty: 'EASY', content: { topic: 'chemistry', question: 'What is the common name for Sodium Chloride?' }, correctAnswer: 3, options: ['Sugar', 'Pepper', 'Flour', 'Salt'] },
    { difficulty: 'EASY', content: { topic: 'chemistry', question: 'What is the lightest chemical element?' }, correctAnswer: 0, options: ['Hydrogen', 'Helium', 'Lithium', 'Boron'] },
    { difficulty: 'EASY', content: { topic: 'chemistry', question: 'Rust is the result of iron reacting with what?' }, correctAnswer: 1, options: ['Nitrogen', 'Oxygen', 'Hydrogen', 'Helium'] },
    { difficulty: 'EASY', content: { topic: 'chemistry', question: 'Which metal is gathered from bauxite?' }, correctAnswer: 2, options: ['Iron', 'Copper', 'Aluminum', 'Zinc'] },
    { difficulty: 'EASY', content: { topic: 'chemistry', question: 'What is the symbol for Iron?' }, correctAnswer: 0, options: ['Fe', 'Ir', 'In', 'I'] },
    { difficulty: 'EASY', content: { topic: 'chemistry', question: 'What gas do plants need for photosynthesis?' }, correctAnswer: 1, options: ['Oxygen', 'Carbon Dioxide', 'Nitrogen', 'Hydrogen'] },
    { difficulty: 'EASY', content: { topic: 'chemistry', question: 'What is the center of an atom called?' }, correctAnswer: 2, options: ['Proton', 'Shell', 'Nucleus', 'Orbit'] },
    { difficulty: 'EASY', content: { topic: 'chemistry', question: 'What is the symbol for Silver?' }, correctAnswer: 3, options: ['Si', 'Sl', 'Au', 'Ag'] },

    // MEDIUM
    { difficulty: 'MEDIUM', content: { topic: 'chemistry', question: 'What is the atomic number of Carbon?' }, correctAnswer: 2, options: ['4', '12', '6', '8'] },
    { difficulty: 'MEDIUM', content: { topic: 'chemistry', question: 'Which particle has a negative charge?' }, correctAnswer: 0, options: ['Electron', 'Proton', 'Neutron', 'Nucleus'] },
    { difficulty: 'MEDIUM', content: { topic: 'chemistry', question: 'What is the most abundant gas in Earth\'s atmosphere?' }, correctAnswer: 1, options: ['Oxygen', 'Nitrogen', 'Argon', 'Carbon Dioxide'] },
    { difficulty: 'MEDIUM', content: { topic: 'chemistry', question: 'Which element is a noble gas?' }, correctAnswer: 3, options: ['Chlorine', 'Sodium', 'Oxygen', 'Neon'] },
    { difficulty: 'MEDIUM', content: { topic: 'chemistry', question: 'What do acids release in water?' }, correctAnswer: 0, options: ['Hydrogen ions', 'Hydroxide ions', 'Oxygen', 'Salt'] },
    { difficulty: 'MEDIUM', content: { topic: 'chemistry', question: 'Is a lemon acidic or basic?' }, correctAnswer: 0, options: ['Acidic', 'Basic', 'Neutral', 'None'] },
    { difficulty: 'MEDIUM', content: { topic: 'chemistry', question: 'What is the chemical formula for Methane?' }, correctAnswer: 2, options: ['CH2', 'C2H6', 'CH4', 'CH3'] },
    { difficulty: 'MEDIUM', content: { topic: 'chemistry', question: 'What is the heaviest naturally occurring element?' }, correctAnswer: 1, options: ['Gold', 'Uranium', 'Lead', 'Plutonium'] },
    { difficulty: 'MEDIUM', content: { topic: 'chemistry', question: 'What type of bond involves sharing electrons?' }, correctAnswer: 0, options: ['Covalent', 'Ionic', 'Metallic', 'Hydrogen'] },
    { difficulty: 'MEDIUM', content: { topic: 'chemistry', question: 'What is dry ice made of?' }, correctAnswer: 3, options: ['Water', 'Nitrogen', 'Oxygen', 'Carbon Dioxide'] },
    { difficulty: 'MEDIUM', content: { topic: 'chemistry', question: 'What is the chemical formula for Ozone?' }, correctAnswer: 2, options: ['O', 'O2', 'O3', 'O4'] },
    { difficulty: 'MEDIUM', content: { topic: 'chemistry', question: 'Which element is liquid at room temperature?' }, correctAnswer: 1, options: ['Iron', 'Mercury', 'Gold', 'Lead'] },
    { difficulty: 'MEDIUM', content: { topic: 'chemistry', question: 'What is the main component of natural gas?' }, correctAnswer: 0, options: ['Methane', 'Ethane', 'Propane', 'Butane'] },
    { difficulty: 'MEDIUM', content: { topic: 'chemistry', question: 'Which acid is found in the stomach?' }, correctAnswer: 2, options: ['Sulfuric', 'Acetic', 'Hydrochloric', 'Nitric'] },
    { difficulty: 'MEDIUM', content: { topic: 'chemistry', question: 'What color does litmus turn in acid?' }, correctAnswer: 0, options: ['Red', 'Blue', 'Green', 'Yellow'] },

    // HARD
    { difficulty: 'HARD', content: { topic: 'chemistry', question: 'What is the vertical column in the periodic table called?' }, correctAnswer: 0, options: ['Group', 'Period', 'Block', 'Family'] },
    { difficulty: 'HARD', content: { topic: 'chemistry', question: 'Which scientist arranged the Periodic Table?' }, correctAnswer: 1, options: ['Einstein', 'Mendeleev', 'Newton', 'Curie'] },
    { difficulty: 'HARD', content: { topic: 'chemistry', question: 'What is the process of a liquid turning into a gas?' }, correctAnswer: 2, options: ['Melting', 'Freezing', 'Evaporation', 'Sublimation'] },
    { difficulty: 'HARD', content: { topic: 'chemistry', question: 'Which metal is liquid at room temperature?' }, correctAnswer: 3, options: ['Iron', 'Gold', 'Silver', 'Mercury'] },
    { difficulty: 'HARD', content: { topic: 'chemistry', question: 'What is the chemical name for Vitamin C?' }, correctAnswer: 0, options: ['Ascorbic Acid', 'Citric Acid', 'Acetic Acid', 'Lactic Acid'] },
    { difficulty: 'HARD', content: { topic: 'chemistry', question: 'What is the charge of a neutron?' }, correctAnswer: 1, options: ['Positive', 'Neutral', 'Negative', 'Variable'] },
    { difficulty: 'HARD', content: { topic: 'chemistry', question: 'Which element has the symbol Pb?' }, correctAnswer: 2, options: ['Potassium', 'Phosphorus', 'Lead', 'Platinum'] },
    { difficulty: 'HARD', content: { topic: 'chemistry', question: 'What is the most electronegative element?' }, correctAnswer: 0, options: ['Fluorine', 'Oxygen', 'Chlorine', 'Nitrogen'] },
    { difficulty: 'HARD', content: { topic: 'chemistry', question: 'Which gas smells like rotten eggs?' }, correctAnswer: 3, options: ['Oxygen', 'Hydrogen', 'Chlorine', 'Hydrogen Sulfide'] },
    { difficulty: 'HARD', content: { topic: 'chemistry', question: 'What is the common name of Calcium Carbonate?' }, correctAnswer: 0, options: ['Chalk', 'Salt', 'Gypsum', 'Quartz'] },
    { difficulty: 'HARD', content: { topic: 'chemistry', question: 'What alloy is made of copper and zinc?' }, correctAnswer: 1, options: ['Bronze', 'Brass', 'Steel', 'Pewter'] },
    { difficulty: 'HARD', content: { topic: 'chemistry', question: 'Which element is used in computer chips?' }, correctAnswer: 2, options: ['Iron', 'Copper', 'Silicon', 'Gold'] },
    { difficulty: 'HARD', content: { topic: 'chemistry', question: 'What is the hardest natural substance?' }, correctAnswer: 3, options: ['Steel', 'Titanium', 'Granite', 'Diamond'] },
    { difficulty: 'HARD', content: { topic: 'chemistry', question: 'What is the formula for table sugar?' }, correctAnswer: 0, options: ['C12H22O11', 'C6H12O6', 'NaCl', 'CH4'] },
    { difficulty: 'HARD', content: { topic: 'chemistry', question: 'Which element prevents goiter?' }, correctAnswer: 1, options: ['Iron', 'Iodine', 'Calcium', 'Zinc'] },

    // --- PHYSICS ---
    // EASY
    { difficulty: 'EASY', content: { topic: 'physics', question: 'What pulls objects toward the Earth?' }, correctAnswer: 0, options: ['Gravity', 'Magnetism', 'Friction', 'Inertia'] },
    { difficulty: 'EASY', content: { topic: 'physics', question: 'What is the unit of electric current?' }, correctAnswer: 1, options: ['Volt', 'Ampere', 'Ohm', 'Watt'] },
    { difficulty: 'EASY', content: { topic: 'physics', question: 'Which color absorbs light?' }, correctAnswer: 2, options: ['White', 'Red', 'Black', 'Green'] },
    { difficulty: 'EASY', content: { topic: 'physics', question: 'What is the speed of sound dependent on?' }, correctAnswer: 3, options: ['Light', 'Color', 'Time', 'Medium'] },
    { difficulty: 'EASY', content: { topic: 'physics', question: 'What divides the Earth into North and South?' }, correctAnswer: 0, options: ['Equator', 'Prime Meridian', 'Tropic of Cancer', 'Axis'] },
    { difficulty: 'EASY', content: { topic: 'physics', question: 'What energy do moving objects have?' }, correctAnswer: 1, options: ['Potential', 'Kinetic', 'Thermal', 'Chemical'] },
    { difficulty: 'EASY', content: { topic: 'physics', question: 'What simple machine is a ramp?' }, correctAnswer: 2, options: ['Lever', 'Pulley', 'Inclined Plane', 'Wedge'] },
    { difficulty: 'EASY', content: { topic: 'physics', question: 'What measures temperature?' }, correctAnswer: 3, options: ['Barometer', 'Ruler', 'Scale', 'Thermometer'] },
    { difficulty: 'EASY', content: { topic: 'physics', question: 'What comes from the sun?' }, correctAnswer: 0, options: ['Solar Energy', 'Wind Energy', 'Hydro Energy', 'Geo Energy'] },
    { difficulty: 'EASY', content: { topic: 'physics', question: 'Which pole of a magnet attracts the North pole?' }, correctAnswer: 1, options: ['North', 'South', 'East', 'West'] },
    { difficulty: 'EASY', content: { topic: 'physics', question: 'What travels faster, light or sound?' }, correctAnswer: 0, options: ['Light', 'Sound', 'Same', 'Neither'] },
    { difficulty: 'EASY', content: { topic: 'physics', question: 'What force stops a moving ball?' }, correctAnswer: 2, options: ['Gravity', 'Push', 'Friction', 'Magnetic'] },
    { difficulty: 'EASY', content: { topic: 'physics', question: 'What device stores electricity?' }, correctAnswer: 3, options: ['Motor', 'Switch', 'Wire', 'Battery'] },
    { difficulty: 'EASY', content: { topic: 'physics', question: 'What is the boiling point of water?' }, correctAnswer: 0, options: ['100°C', '0°C', '50°C', '200°C'] },
    { difficulty: 'EASY', content: { topic: 'physics', question: 'Which instrument measures time?' }, correctAnswer: 1, options: ['Ruler', 'Clock', 'Scale', 'Compass'] },

    // MEDIUM
    { difficulty: 'MEDIUM', content: { topic: 'physics', question: 'What is force measured in?' }, correctAnswer: 0, options: ['Newtons', 'Joules', 'Watts', 'Pascals'] },
    { difficulty: 'MEDIUM', content: { topic: 'physics', question: 'What is the formula for speed?' }, correctAnswer: 1, options: ['Distance x Time', 'Distance / Time', 'Time / Distance', 'Force x Mass'] },
    { difficulty: 'MEDIUM', content: { topic: 'physics', question: 'Sound cannot travel through what?' }, correctAnswer: 2, options: ['Water', 'Solids', 'Vacuum', 'Air'] },
    { difficulty: 'MEDIUM', content: { topic: 'physics', question: 'Which law states "For every action, there is an equal and opposite reaction"?' }, correctAnswer: 2, options: ['First Law', 'Second Law', 'Third Law', 'Fourth Law'] },
    { difficulty: 'MEDIUM', content: { topic: 'physics', question: 'What is the rate of change of velocity?' }, correctAnswer: 0, options: ['Acceleration', 'Speed', 'Momentum', 'Inertia'] },
    { difficulty: 'MEDIUM', content: { topic: 'physics', question: 'Which particle carries a positive charge?' }, correctAnswer: 1, options: ['Electron', 'Proton', 'Neutron', 'Photon'] },
    { difficulty: 'MEDIUM', content: { topic: 'physics', question: 'What is the SI unit of mass?' }, correctAnswer: 2, options: ['Gram', 'Pound', 'Kilogram', 'Ton'] },
    { difficulty: 'MEDIUM', content: { topic: 'physics', question: 'Which color has the shortest wavelength?' }, correctAnswer: 3, options: ['Red', 'Green', 'Yellow', 'Violet'] },
    { difficulty: 'MEDIUM', content: { topic: 'physics', question: 'What property resists change in motion?' }, correctAnswer: 0, options: ['Inertia', 'Velocity', 'Force', 'Gravity'] },
    { difficulty: 'MEDIUM', content: { topic: 'physics', question: 'What is the flow of electrons called?' }, correctAnswer: 1, options: ['Voltage', 'Current', 'Resistance', 'Power'] },
    { difficulty: 'MEDIUM', content: { topic: 'physics', question: 'What kind of lens is in a magnifying glass?' }, correctAnswer: 2, options: ['Concave', 'Flat', 'Convex', 'Cylindrical'] },
    { difficulty: 'MEDIUM', content: { topic: 'physics', question: 'Which force keeps planets in orbit?' }, correctAnswer: 0, options: ['Gravity', 'Magnetism', 'Friction', 'Tension'] },
    { difficulty: 'MEDIUM', content: { topic: 'physics', question: 'What is stored energy called?' }, correctAnswer: 1, options: ['Kinetic', 'Potential', 'Thermal', 'Mechanical'] },
    { difficulty: 'MEDIUM', content: { topic: 'physics', question: 'What does a barometer measure?' }, correctAnswer: 2, options: ['Temperature', 'Humidity', 'Pressure', 'Wind'] },
    { difficulty: 'MEDIUM', content: { topic: 'physics', question: 'What is the freezing point of water in Fahrenheit?' }, correctAnswer: 3, options: ['0°F', '100°F', '212°F', '32°F'] },

    // HARD
    { difficulty: 'HARD', content: { topic: 'physics', question: 'Who formulated the laws of motion?' }, correctAnswer: 0, options: ['Isaac Newton', 'Albert Einstein', 'Galileo', 'Tesla'] },
    { difficulty: 'HARD', content: { topic: 'physics', question: 'What is the bending of light called?' }, correctAnswer: 1, options: ['Reflection', 'Refraction', 'Diffraction', 'Dispersion'] },
    { difficulty: 'HARD', content: { topic: 'physics', question: 'What is the unit of power?' }, correctAnswer: 2, options: ['Joule', 'Newton', 'Watt', 'Volt'] },
    { difficulty: 'HARD', content: { topic: 'physics', question: 'Which wave type requires a medium?' }, correctAnswer: 3, options: ['Light', 'Radio', 'X-ray', 'Sound'] },
    { difficulty: 'HARD', content: { topic: 'physics', question: 'What is density?' }, correctAnswer: 0, options: ['Mass/Volume', 'Mass x Volume', 'Weight/Area', 'Force/Area'] },
    { difficulty: 'HARD', content: { topic: 'physics', question: 'What is the speed of light?' }, correctAnswer: 1, options: ['300 km/s', '300,000 km/s', '3,000 km/s', '300,000 m/s'] },
    { difficulty: 'HARD', content: { topic: 'physics', question: 'Which particle has no charge?' }, correctAnswer: 2, options: ['Proton', 'Electron', 'Neutron', 'Ion'] },
    { difficulty: 'HARD', content: { topic: 'physics', question: 'What is the unit of frequency?' }, correctAnswer: 3, options: ['Watt', 'Joule', 'Volt', 'Hertz'] },
    { difficulty: 'HARD', content: { topic: 'physics', question: 'What is the absolute zero temperature?' }, correctAnswer: 0, options: ['-273.15°C', '0°C', '-100°C', '-459°C'] },
    { difficulty: 'HARD', content: { topic: 'physics', question: 'Who discovered radioactivity?' }, correctAnswer: 1, options: ['Einstein', 'Curie', 'Newton', 'Darwin'] },
    { difficulty: 'HARD', content: { topic: 'physics', question: 'What is the force involved in nuclear decay?' }, correctAnswer: 2, options: ['Gravity', 'Electromagnetic', 'Weak Nuclear', 'Strong Nuclear'] },
    { difficulty: 'HARD', content: { topic: 'physics', question: 'What device converts mechanical energy to electrical?' }, correctAnswer: 3, options: ['Motor', 'Battery', 'Resistor', 'Generator'] },
    { difficulty: 'HARD', content: { topic: 'physics', question: 'What is the unit of resistance?' }, correctAnswer: 0, options: ['Ohm', 'Volt', 'Ampere', 'Watt'] },
    { difficulty: 'HARD', content: { topic: 'physics', question: 'Which radiation has the highest energy?' }, correctAnswer: 1, options: ['Radio', 'Gamma', 'Infrared', 'Visible'] },
    { difficulty: 'HARD', content: { topic: 'physics', question: 'What causes the blue color of the sky?' }, correctAnswer: 2, options: ['Reflection', 'Diffraction', 'Scattering', 'Absorption'] },

    // --- EARTH SCIENCE & SPACE ---
    // EASY
    { difficulty: 'EASY', content: { topic: 'earth-science', question: 'What is the name of our galaxy?' }, correctAnswer: 0, options: ['Milky Way', 'Andromeda', 'Sombrero', 'Whirlpool'] },
    { difficulty: 'EASY', content: { topic: 'earth-science', question: 'Which planet has rings?' }, correctAnswer: 1, options: ['Mars', 'Saturn', 'Venus', 'Mercury'] },
    { difficulty: 'EASY', content: { topic: 'earth-science', question: 'What is the closest star to Earth?' }, correctAnswer: 2, options: ['Sirius', 'Alpha Centauri', 'The Sun', 'Betelgeuse'] },
    { difficulty: 'EASY', content: { topic: 'earth-science', question: 'What is the blue planet?' }, correctAnswer: 3, options: ['Mars', 'Venus', 'Jupiter', 'Earth'] },
    { difficulty: 'EASY', content: { topic: 'earth-science', question: 'What do we call a rock from space that hits Earth?' }, correctAnswer: 0, options: ['Meteorite', 'Meteor', 'Asteroid', 'Comet'] },
    { difficulty: 'EASY', content: { topic: 'earth-science', question: 'What is the hot liquid rock inside Earth?' }, correctAnswer: 1, options: ['Lava', 'Magma', 'Ash', 'Core'] },
    { difficulty: 'EASY', content: { topic: 'earth-science', question: 'Which season is the hottest?' }, correctAnswer: 2, options: ['Winter', 'Spring', 'Summer', 'Autumn'] },
    { difficulty: 'EASY', content: { topic: 'earth-science', question: 'What is the Moon made of?' }, correctAnswer: 0, options: ['Rock', 'Cheese', 'Ice', 'Gas'] },
    { difficulty: 'EASY', content: { topic: 'earth-science', question: 'What protects Earth from the Sun\'s rays?' }, correctAnswer: 1, options: ['Moon', 'Ozone Layer', 'Clouds', 'Ocean'] },
    { difficulty: 'EASY', content: { topic: 'earth-science', question: 'What is the center of the solar system?' }, correctAnswer: 0, options: ['Sun', 'Earth', 'Moon', 'Mars'] },

    // MEDIUM
    { difficulty: 'MEDIUM', content: { topic: 'earth-science', question: 'What causes tides?' }, correctAnswer: 0, options: ['Moon\'s Gravity', 'Sun\'s Heat', 'Wind', 'Earth\'s Rotation'] },
    { difficulty: 'MEDIUM', content: { topic: 'earth-science', question: 'Which layer of Earth is liquid?' }, correctAnswer: 1, options: ['Crust', 'Outer Core', 'Inner Core', 'Mantle'] },
    { difficulty: 'MEDIUM', content: { topic: 'earth-science', question: 'What type of rock is formed from lava?' }, correctAnswer: 2, options: ['Sedimentary', 'Metamorphic', 'Igneous', 'Fossilized'] },
    { difficulty: 'MEDIUM', content: { topic: 'earth-science', question: 'Which planet is known as the Red Planet?' }, correctAnswer: 0, options: ['Mars', 'Jupiter', 'Saturn', 'Venus'] },
    { difficulty: 'MEDIUM', content: { topic: 'earth-science', question: 'What gas makes up most of the atmosphere?' }, correctAnswer: 3, options: ['Oxygen', 'Carbon Dioxide', 'Argon', 'Nitrogen'] },
    { difficulty: 'MEDIUM', content: { topic: 'earth-science', question: 'What instrument measures earthquakes?' }, correctAnswer: 0, options: ['Seismograph', 'Barometer', 'Thermometer', 'Scale'] },
    { difficulty: 'MEDIUM', content: { topic: 'earth-science', question: 'What is the study of weather called?' }, correctAnswer: 1, options: ['Geology', 'Meteorology', 'Biology', 'Astronomy'] },
    { difficulty: 'MEDIUM', content: { topic: 'earth-science', question: 'Which planet is closest to the Sun?' }, correctAnswer: 2, options: ['Venus', 'Earth', 'Mercury', 'Mars'] },
    { difficulty: 'MEDIUM', content: { topic: 'earth-science', question: 'What is the hardest mineral?' }, correctAnswer: 3, options: ['Quartz', 'Topaz', 'Gold', 'Diamond'] },
    { difficulty: 'MEDIUM', content: { topic: 'earth-science', question: 'What are clouds made of?' }, correctAnswer: 0, options: ['Water droplets', 'Smoke', 'Cotton', 'Gas'] },

    // HARD
    { difficulty: 'HARD', content: { topic: 'earth-science', question: 'Which planet rotates on its side?' }, correctAnswer: 3, options: ['Mars', 'Jupiter', 'Saturn', 'Uranus'] },
    { difficulty: 'HARD', content: { topic: 'earth-science', question: 'What is the layer of gas surrounding Earth?' }, correctAnswer: 0, options: ['Atmosphere', 'Hydrosphere', 'Lithosphere', 'Biosphere'] },
    { difficulty: 'HARD', content: { topic: 'earth-science', question: 'What theory explains the movement of continents?' }, correctAnswer: 1, options: ['Big Bang', 'Plate Tectonics', 'Evolution', 'Relativity'] },
    { difficulty: 'HARD', content: { topic: 'earth-science', question: 'Which planet is the largest in our solar system?' }, correctAnswer: 2, options: ['Saturn', 'Neptune', 'Jupiter', 'Uranus'] },
    { difficulty: 'HARD', content: { topic: 'earth-science', question: 'What is the boundary between the crust and mantle?' }, correctAnswer: 3, options: ['Core', 'Fault', 'Ridge', 'Moho'] },
    { difficulty: 'HARD', content: { topic: 'earth-science', question: 'Which rock type contains fossils?' }, correctAnswer: 0, options: ['Sedimentary', 'Igneous', 'Metamorphic', 'Volcanic'] },
    { difficulty: 'HARD', content: { topic: 'earth-science', question: 'What is the point above an earthquake called?' }, correctAnswer: 1, options: ['Focus', 'Epicenter', 'Fault', 'Core'] },
    { difficulty: 'HARD', content: { topic: 'earth-science', question: 'Which planet has the Great Red Spot?' }, correctAnswer: 2, options: ['Mars', 'Venus', 'Jupiter', 'Saturn'] },
    { difficulty: 'HARD', content: { topic: 'earth-science', question: 'What is the hottest layer of Earth?' }, correctAnswer: 3, options: ['Crust', 'Mantle', 'Outer Core', 'Inner Core'] },
    { difficulty: 'HARD', content: { topic: 'earth-science', question: 'What measures wind speed?' }, correctAnswer: 0, options: ['Anemometer', 'Barometer', 'Compass', 'Scale'] },

    // CHALLENGE (General Science)
    { difficulty: 'CHALLENGE', content: { topic: 'physics', question: 'What is the First Law of Thermodynamics?' }, correctAnswer: 0, options: ['Conservation of Energy', 'Entropy Increase', 'Absolute Zero', 'Action-Reaction'] },
    { difficulty: 'CHALLENGE', content: { topic: 'biology', question: 'What are plasmids?' }, correctAnswer: 1, options: ['Viral DNA', 'Small circular DNA', 'Plant organelles', 'Protein coats'] },
    { difficulty: 'CHALLENGE', content: { topic: 'chemistry', question: 'What is the Avogadro constant?' }, correctAnswer: 2, options: ['3.14 x 10^23', '9.8 x 10^23', '6.022 x 10^23', '1.6 x 10^-19'] },
    { difficulty: 'CHALLENGE', content: { topic: 'earth-science', question: 'What is the discontinuity between crust and mantle?' }, correctAnswer: 3, options: ['Gutenberg', 'Lehman', 'Conrad', 'Mohorovicic'] },
    { difficulty: 'CHALLENGE', content: { topic: 'earth-science', question: 'What is the term for the point directly above an earthquake focus?' }, correctAnswer: 0, options: ['Epicenter', 'Hypocenter', 'Fault', 'Seismic Zone'] },
    { difficulty: 'CHALLENGE', content: { topic: 'biology', question: 'Which enzyme breaks down starch?' }, correctAnswer: 1, options: ['Pepsin', 'Amylase', 'Lipase', 'Trypsin'] },
    { difficulty: 'CHALLENGE', content: { topic: 'chemistry', question: 'What is the geometry of a methane molecule?' }, correctAnswer: 2, options: ['Linear', 'Trigonal', 'Tetrahedral', 'Octahedral'] },
    { difficulty: 'CHALLENGE', content: { topic: 'physics', question: 'What particle explains gravity in theory?' }, correctAnswer: 3, options: ['Photon', 'Gluon', 'Boson', 'Graviton'] },
    { difficulty: 'CHALLENGE', content: { topic: 'earth-science', question: 'Which era is the Age of Reptiles?' }, correctAnswer: 0, options: ['Mesozoic', 'Cenozoic', 'Paleozoic', 'Precambrian'] },
    { difficulty: 'CHALLENGE', content: { topic: 'physics', question: 'What is the escape velocity of Earth?' }, correctAnswer: 1, options: ['7.2 km/s', '11.2 km/s', '9.8 m/s', '300 km/s'] },
    { difficulty: 'CHALLENGE', content: { topic: 'chemistry', question: 'Which acid is used in car batteries?' }, correctAnswer: 2, options: ['Nitric', 'Acetic', 'Sulfuric', 'Hydrochloric'] },
    { difficulty: 'CHALLENGE', content: { topic: 'biology', question: 'What is the study of fungi called?' }, correctAnswer: 3, options: ['Botany', 'Zoology', 'Virology', 'Mycology'] },
    { difficulty: 'CHALLENGE', content: { topic: 'physics', question: 'What is the unit of capacitance?' }, correctAnswer: 0, options: ['Farad', 'Henry', 'Ohm', 'Tesla'] },
    { difficulty: 'CHALLENGE', content: { topic: 'chemistry', question: 'What is the main ore of mercury?' }, correctAnswer: 1, options: ['Bauxite', 'Cinnabar', 'Galena', 'Hematite'] },
    { difficulty: 'CHALLENGE', content: { topic: 'earth-science', question: 'What layer protects Earth from UV rays?' }, correctAnswer: 2, options: ['Troposphere', 'Ionosphere', 'Stratosphere', 'Exosphere'] }
];
