export const TYPING_DATA = {
    sentences: {
        easy: [
            "The sun is shining bright today.",
            "I love to play games with my friends.",
            "My cat likes to sleep on the sofa.",
            "We went to the park to play ball.",
            "Apples are red and taste sweet.",
            "The dog ran fast to catch the stick.",
            "Birds can fly high in the blue sky.",
            "I can read many books at school.",
            "Fish swim in the deep blue sea.",
            "The stars come out at night time.",
            "Green grass grows in my garden.",
            "I drink milk every morning for breakfast.",
            "Rain water helps the flowers grow.",
            "A fast car drove down the street.",
            "The moon looks like a big white cheese.",
            "Cats and dogs can be good friends.",
            "I like to draw with my crayons.",
            "The bus stops at the corner.",
            "She has a red hat and blue shoes.",
            "He rides his bike to school.",
            "The big tree gives us shade.",
            "Ants work hard all day long.",
            "Bees make honey from flowers.",
            "The wind blows the leaves away.",
            "Snow is cold and white.",
            "I put on my coat and scarf.",
            "Mom bakes a cake for us.",
            "Dad plays catch with me.",
            "The baby sleeps in the crib.",
            "We eat lunch at noon."
        ],
        medium: [
            "The quick brown fox jumps over the lazy dog.",
            "Practice makes perfect if you keep trying every day.",
            "The Earth revolves around the Sun once every year.",
            "Honey never spoils and can be eaten years later.",
            "A group of flamingos is called a flamboyance.",
            "Octopuses have three hearts and blue blood.",
            "Honeybees can recognize human faces.",
            "Dolphins sleep with one eye open to watch for danger.",
            "The Eiffel Tower can grow taller in the summer heat.",
            "Bananas are curved because they grow towards the sun.",
            "Computers use binary code made of zeros and ones.",
            "Australia is the only continent without active volcanoes.",
            "The Great Wall of China is visible from space.",
            "Elephants are the only animals that cannot jump.",
            "Butterflies taste with their feet.",
            "A snail can sleep for three years.",
            "Slugs have four noses.",
            "It takes about eight minutes for light from the Sun to reach Earth.",
            "Some bamboo plants can grow almost a meter in just one day.",
            "The fingerprint of a koala is so similar to a human's that they can be confused at a crime scene.",
            "A bolt of lightning is five times hotter than the surface of the sun.",
            "Humans and giraffes have the same number of neck vertebrae.",
            "The total weight of ants on Earth once equaled the total weight of people.",
            "A cockroach can live for several weeks without its head."
        ],
        hard: [
            "To be or not to be, that is the question.",
            "Consistency is the key to mastering any new skill.",
            "The five boxing wizards jump quickly.",
            "Sphinx of black quartz, judge my vow.",
            "Pack my box with five dozen liquor jugs.",
            "A journey of a thousand miles begins with a single step.",
            "Success is not final, failure is not fatal: it is the courage to continue that counts.",
            "In the middle of difficulty lies opportunity.",
            "Imagination is more important than knowledge.",
            "Life is what happens when you're busy making other plans.",
            "Do not go where the path may lead, go instead where there is no path and leave a trail.",
            "The only way to do great work is to love what you do.",
            "Believe you can and you're halfway there.",
            "It does not matter how slowly you go as long as you do not stop.",
            "Our greatest glory is not in never falling, but in rising every time we fall.",
            "The future belongs to those who believe in the beauty of their dreams.",
            "The best way to predict the future is to create it.",
            "You miss 100% of the shots you don't take.",
            "Whether you think you can or you think you can't, you're right.",
            "I have not failed. I've just found 10,000 ways that won't work.",
            "Tell me and I forget. Teach me and I remember. Involve me and I learn."
        ]
    },
    paragraphs: [
        "The Amazon rainforest is the largest tropical rainforest in the world, covering over 5.5 million square kilometers. It is often referred to as the 'lungs of the Earth' because it produces more than 20% of the world's oxygen. The Amazon is home to an incredibly diverse array of wildlife, including jaguars, sloths, and macaws.",
        "Space exploration has always fascinated humanity. From the first steps on the moon to the latest rovers on Mars, we are constantly pushing the boundaries of what is possible. The International Space Station orbits Earth at a speed of approximately 17,500 miles per hour, witnessing 16 sunrises and sunsets every single day.",
        "The history of computers dates back to the early 19th century with Charles Babbage's analytical engine. However, it wasn't until the mid-20th century that electronic computers were developed. Today, our smartphones have more computing power than the computers used to guide the Apollo missions to the moon.",
        "In the deep ocean, there are creatures that glow in the dark. This phenomenon, known as bioluminescence, helps them attract prey or find mates in the pitch-black water. Some jellyfish, squid, and even sharks have the ability to produce their own light through chemical reactions.",
        "Mount Everest is the highest peak on Earth, standing at 29,032 feet above sea level. Climbing it is a dangerous feat that requires months of preparation. The air at the summit is so thin that most climbers need supplemental oxygen to survive the ascent.",
        "The Great Barrier Reef off the coast of Australia is the world's largest coral reef system. It is composed of over 2,900 individual reefs and 900 islands. It is so huge that it can be seen from outer space and is home to thousands of marine species.",
        "Artificial Intelligence is rapidly changing the world. From self-driving cars to personalized recommendations on streaming services, AI is everywhere. While it offers many benefits, it also raises important ethical questions about privacy and the future of work.",
        "The human brain is the most complex organ in the body. It contains faster processing power than any supercomputer and controls everything from our thoughts to our movements. Despite years of research, scientists still have much to learn about how memory and consciousness work.",
        "Renewable energy sources like solar and wind power are becoming increasingly important. Unlike fossil fuels, they do not produce harmful greenhouse gases that contribute to climate change. Transitioning to green energy is essential for a sustainable future.",
        "Video games have evolved from simple pixelated graphics to immersive virtual worlds. They are not just for entertainment; they can also improve hand-eye coordination and problem-solving skills. Esports has even become a professional industry with tournaments offering millions in prizes.",
        "The Pyramids of Giza were built over 4,500 years ago and are the only surviving wonder of the ancient world. How they were constructed with such precision remains a subject of debate among historians and archaeologists. They stand as a testament to the ingenuity of ancient Egyptian civilization.",
        "Music has a profound effect on our emotions and well-being. Listening to your favorite song can release dopamine in the brain, making you feel happy. Different genres of music can also help you focus, relax, or get pumped up for a workout.",
        "The migration of monarch butterflies is one of nature's greatest mysteries. Every year, millions of them travel thousands of miles from Canada and the US to Mexico. Remarkably, no single butterfly completes the entire round trip; it takes several generations.",
        "Chocolate is made from the seeds of the cacao tree. The ancient Maya and Aztecs were the first to consume chocolate, but they drank it as a bitter, spicy beverage. It wasn't until Europeans added sugar and milk that it became the sweet treat we know today.",
        "The internet has connected the world in ways previously unimaginable. We can communicate instantly with anyone, anywhere. However, this connectivity also brings challenges, such as the spread of misinformation and cyber threats.",
        "Honeybees are essential for pollinating many of the crops we eat. Without them, our food supply would be severely threatened. Unfortunately, bee populations are declining due to habitat loss and pesticides, prompting efforts to save them.",
        "Diamonds are formed deep within the Earth under extreme heat and pressure. They are brought to the surface by volcanic eruptions. Although they are made of carbon, the same element as graphite in pencils, their atomic structure makes them the hardest natural material.",
        "The aurora borealis, or northern lights, is a stunning natural light display. It occurs when charged particles from the sun collide with Earth's atmosphere. The colors range from green and pink to red and violet, dancing across the night sky.",
        "Robotics is a field that combines engineering and computer science. Robots are used in manufacturing, medicine, and even space exploration. As technology advances, robots are becoming more autonomous and capable of performing complex tasks.",
        "Climate change is causing global temperatures to rise. This leads to melting ice caps, rising sea levels, and more frequent extreme weather events. Reducing our carbon footprint is crucial to protecting the planet for future generations.",
        "The cheetah is the fastest land animal, capable of reaching speeds up to 70 mph. However, it can only maintain this speed for short bursts. Its agility and speed make it a formidable predator on the African savanna.",
        "The Eiffel Tower was originally built as a temporary structure for the 1889 World's Fair. Many Parisians hated it at first, calling it an eyesore. Today, it is the most iconic symbol of Paris and one of the most visited monuments in the world."
    ],
    commonWords: [
        "the", "be", "to", "of", "and", "a", "in", "that", "have", "I", "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
        "this", "but", "his", "by", "from", "they", "we", "say", "her", "she", "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
        "so", "up", "out", "if", "about", "who", "get", "which", "go", "me", "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
        "people", "into", "year", "your", "good", "some", "could", "them", "see", "other", "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
        "back", "after", "use", "two", "how", "our", "work", "first", "well", "way", "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
        "time", "person", "year", "way", "day", "thing", "man", "world", "life", "hand", "part", "child", "eye", "woman", "place", "work", "week", "case", "point", "government",
        "company", "number", "group", "problem", "fact", "apple", "banana", "orange", "grape", "cherry", "lemon", "table", "chair", "desk", "book", "pen", "paper", "computer", "phone", "mouse",
        "keyboard", "screen", "monitor", "speaker", "music", "sound", "light", "color", "red", "blue", "green", "yellow", "black", "white", "purple", "orange", "pink", "brown", "gray", "silver",
        "gold", "metal", "wood", "glass", "plastic", "water", "fire", "earth", "wind", "sky", "cloud", "rain", "snow", "storm", "tree", "flower", "grass", "leaf", "plant", "garden",
        "forest", "mountain", "river", "ocean", "lake", "sea", "sand", "beach", "stone", "rock", "animal", "dog", "cat", "bird", "fish", "horse", "cow", "pig", "sheep", "chicken",
        "duck", "lion", "tiger", "bear", "monkey", "elephant", "zebra", "giraffe", "snake", "lizard", "frog", "turtle", "school", "class", "student", "teacher", "learn", "study", "read", "write",
        "math", "science", "art", "history", "english", "book", "pencil", "ruler", "eraser", "glue", "map", "globe", "friend", "family", "house", "home", "room", "door", "window", "wall",
        "floor", "ceiling", "lights", "bed", "sofa", "television", "radio", "clock", "watch", "car", "bus", "train", "plane", "boat", "ship", "bike", "walk", "run", "jump", "swim",
        "play", "game", "sport", "ball", "team", "win", "lose", "score", "goal", "start", "stop", "finish", "fast", "slow", "big", "small", "tall", "short", "long", "wide",
        "narrow", "hot", "cold", "warm", "cool", "dry", "wet", "happy", "sad", "angry", "calm", "excited", "bored", "scared", "brave", "strong", "weak", "smart", "funny", "nice",
        "kind", "mean", "rich", "poor", "money", "dollar", "coin", "buy", "sell", "shop", "store", "market", "food", "drink", "eat", "cook", "bread", "milk", "cheese", "egg",
        "meat", "fruit", "vegetable", "onion", "garlic", "salt", "pepper", "sugar", "sweet", "sour", "bitter", "spicy", "hot", "cold", "fresh", "stale", "clean", "dirty", "messy", "neat",
        "new", "old", "young", "ancient", "modern", "future", "past", "present", "now", "later", "soon", "never", "always", "often", "sometimes", "rarely", "maybe", "yes", "no", "hello",
        "goodbye", "please", "thanks", "sorry", "excuse", "pardon", "welcome", "morning", "noon", "afternoon", "evening", "night", "midnight", "today", "tomorrow", "yesterday", "week", "month", "year", "decade",
        "century", "second", "minute", "hour", "north", "south", "east", "west", "direction", "left", "right", "up", "down", "front", "back", "inside", "outside", "top", "bottom", "middle",
        "center", "edge", "corner", "side", "circle", "square", "triangle", "star", "shape", "line", "dot", "zero", "one", "two", "three", "four", "five", "six", "seven", "eight",
        "nine", "ten", "hundred", "thousand", "million", "billion", "first", "last", "next", "previous", "add", "subtract", "divide", "multiply", "count", "number", "letter", "word", "sentence", "grammar",
        "speak", "talk", "hear", "listen", "see", "watch", "look", "smell", "taste", "touch", "feel", "think", "know", "believe", "guess", "wonder", "hope", "wish", "dream", "idea",
        "story", "truth", "lie", "secret", "news", "question", "answer", "ask", "reply", "call", "shout", "whisper", "sing", "dance", "laugh", "cry", "smile", "frown", "hark", "hush",
        "baby", "boy", "girl", "child", "teen", "adult", "parent", "mother", "father", "sister", "brother", "grandma", "grandpa", "aunt", "uncle", "cousin", "niece", "nephew", "neighbor", "doctor",
        "nurse", "cop", "fireman", "cook", "artist", "actor", "singer", "player", "worker", "boss", "king", "queen", "prince", "leader", "hero", "villain", "monster", "ghost", "robot", "alien",
        "magic", "power", "energy", "force", "mass", "atom", "cell", "body", "head", "face", "hair", "nose", "mouth", "ear", "eye", "arm", "hand", "finger", "leg", "foot",
        "shadow", "reflection", "mirror", "glass", "cup", "plate", "fork", "spoon", "knife", "bowl", "napkin", "towel", "soap", "shampoo", "brush", "comb", "tooth", "paste", "water", "shower",
        "bath", "toilet", "sink", "faucet", "pipe", "drain", "floor", "carpet", "rug", "tile", "wood", "stone", "brick", "cement", "metal", "iron", "steel", "gold", "silver", "copper",
        "paper", "card", "board", "box", "bag", "sack", "case", "jar", "can", "bottle", "jug", "bucket", "basket", "bin", "trash", "waste", "dirt", "dust", "mud", "sand"
    ]
}
