/**
 * Massive Pool of 150+ Countries for World Flags Game
 * Includes: Name, Flag Emoji, ISO Code, Region, Capital, GeoFact
 */

export interface CountryData {
    name: string
    code: string // ISO 2-letter, lowercase
    flag: string // Emoji
    region: 'asia' | 'europe' | 'africa' | 'americas' | 'oceania'
    capital: string
    geoFact: string
    similar?: string[] // Codes of similar flags
}

export const WORLD_FLAGS_POOL: CountryData[] = [
    // --- ASIA (35) ---
    { name: 'Japan', flag: '🇯🇵', code: 'jp', region: 'asia', capital: 'Tokyo', geoFact: 'Japan consists of 6,852 islands!', similar: ['bd', 'pw'] },
    { name: 'China', flag: '🇨🇳', code: 'cn', region: 'asia', capital: 'Beijing', geoFact: 'China has the world\'s largest population.', similar: ['vn', 'kp'] },
    { name: 'India', flag: '🇮🇳', code: 'in', region: 'asia', capital: 'New Delhi', geoFact: 'India is the world\'s largest democracy.', similar: ['ne', 'ie'] },
    { name: 'Indonesia', flag: '🇮🇩', code: 'id', region: 'asia', capital: 'Jakarta', geoFact: 'Indonesia has over 17,000 islands!', similar: ['pl', 'mc'] },
    { name: 'South Korea', flag: '🇰🇷', code: 'kr', region: 'asia', capital: 'Seoul', geoFact: 'South Korea has the fastest internet in the world.' },
    { name: 'North Korea', flag: '🇰🇵', code: 'kp', region: 'asia', capital: 'Pyongyang', geoFact: 'The DMZ separates North and South Korea.', similar: ['cn', 'th'] },
    { name: 'Thailand', flag: '🇹🇭', code: 'th', region: 'asia', capital: 'Bangkok', geoFact: 'Thailand means "Land of the Free".', similar: ['cr', 'kp'] },
    { name: 'Vietnam', flag: '🇻🇳', code: 'vn', region: 'asia', capital: 'Hanoi', geoFact: 'Vietnam is the world\'s largest cashew nut exporter.', similar: ['cn', 'ma'] },
    { name: 'Malaysia', flag: '🇲🇾', code: 'my', region: 'asia', capital: 'Kuala Lumpur', geoFact: 'Malaysia has the world\'s oldest rainforest.', similar: ['us', 'lr'] },
    { name: 'Singapore', flag: '🇸🇬', code: 'sg', region: 'asia', capital: 'Singapore', geoFact: 'Singapore is both a city and a country!', similar: ['tr', 'id'] },
    { name: 'Philippines', flag: '🇵🇭', code: 'ph', region: 'asia', capital: 'Manila', geoFact: 'Named after King Philip II of Spain.', similar: ['cz', 'sx'] },
    { name: 'Pakistan', flag: '🇵🇰', code: 'pk', region: 'asia', capital: 'Islamabad', geoFact: 'Pakistan has the highest paved international road.', similar: ['tr', 'dz'] },
    { name: 'Bangladesh', flag: '🇧🇩', code: 'bd', region: 'asia', capital: 'Dhaka', geoFact: 'Have the longest natural sea beach.', similar: ['jp', 'pw'] },
    { name: 'Sri Lanka', flag: '🇱🇰', code: 'lk', region: 'asia', capital: 'Colombo', geoFact: 'Known as the Pearl of the Indian Ocean.' },
    { name: 'Nepal', flag: '🇳🇵', code: 'np', region: 'asia', capital: 'Kathmandu', geoFact: 'The only country with a non-rectangular flag.' },
    { name: 'Bhutan', flag: '🇧🇹', code: 'bt', region: 'asia', capital: 'Thimphu', geoFact: 'Current carbon-negative country.' },
    { name: 'Maldives', flag: '🇲🇻', code: 'mv', region: 'asia', capital: 'Malé', geoFact: 'The lowest country in the world.' },
    { name: 'Afghanistan', flag: '🇦🇫', code: 'af', region: 'asia', capital: 'Kabul', geoFact: 'Landlocked country in South-Central Asia.' },
    { name: 'Iran', flag: '🇮🇷', code: 'ir', region: 'asia', capital: 'Tehran', geoFact: 'Home to one of the world\'s oldest civilizations.', similar: ['tj', 'kw'] },
    { name: 'Iraq', flag: '🇮🇶', code: 'iq', region: 'asia', capital: 'Baghdad', geoFact: 'Home to ancient Mesopotamia.', similar: ['sy', 'ye'] },
    { name: 'Saudi Arabia', flag: '🇸🇦', code: 'sa', region: 'asia', capital: 'Riyadh', geoFact: 'Largest country without a river.' },
    { name: 'Yemen', flag: '🇾🇪', code: 'ye', region: 'asia', capital: 'Sana\'a', geoFact: 'Home to the Dragon Blood Trees.', similar: ['iq', 'sy'] },
    { name: 'Oman', flag: '🇴🇲', code: 'om', region: 'asia', capital: 'Muscat', geoFact: 'Oldest independent state in the Arab world.', similar: ['ae', 'jo'] },
    { name: 'UAE', flag: '🇦🇪', code: 'ae', region: 'asia', capital: 'Abu Dhabi', geoFact: 'Home to the world\'s tallest building.', similar: ['kw', 'jo'] },
    { name: 'Qatar', flag: '🇶🇦', code: 'qa', region: 'asia', capital: 'Doha', geoFact: 'Has the highest GDP per capita.', similar: ['bh'] },
    { name: 'Bahrain', flag: '🇧🇭', code: 'bh', region: 'asia', capital: 'Manama', geoFact: 'An archipelago of 33 islands.', similar: ['qa'] },
    { name: 'Kuwait', flag: '🇰🇼', code: 'kw', region: 'asia', capital: 'Kuwait City', geoFact: 'Currency is the highest valued in the world.', similar: ['ae', 'sd'] },
    { name: 'Jordan', flag: '🇯🇴', code: 'jo', region: 'asia', capital: 'Amman', geoFact: 'Home to the ancient city of Petra.', similar: ['ps', 'ae'] },
    { name: 'Israel', flag: '🇮🇱', code: 'il', region: 'asia', capital: 'Jerusalem', geoFact: 'Has the highest number of museums per capita.' },
    { name: 'Lebanon', flag: '🇱🇧', code: 'lb', region: 'asia', capital: 'Beirut', geoFact: 'The name Lebanon appears 70 times in the Bible.' },
    { name: 'Turkey', flag: '🇹🇷', code: 'tr', region: 'asia', capital: 'Ankara', geoFact: 'Straddles two continents: Europe and Asia.', similar: ['tn', 'pk'] },
    { name: 'Kazakhstan', flag: '🇰🇿', code: 'kz', region: 'asia', capital: 'Astana', geoFact: 'World\'s largest landlocked country.', similar: ['pw'] },
    { name: 'Uzbekistan', flag: '🇺🇿', code: 'uz', region: 'asia', capital: 'Tashkent', geoFact: 'Doubly landlocked country.' },
    { name: 'Mongolia', flag: '🇲🇳', code: 'mn', region: 'asia', capital: 'Ulaanbaatar', geoFact: 'Least densely populated country.' },
    { name: 'Cambodia', flag: '🇰🇭', code: 'kh', region: 'asia', capital: 'Phnom Penh', geoFact: 'Home to Angkor Wat, the largest religious monument.' },

    // --- EUROPE (45) ---
    { name: 'United Kingdom', flag: '🇬🇧', code: 'gb', region: 'europe', capital: 'London', geoFact: 'No written constitution.', similar: ['au', 'nz', 'fj'] },
    { name: 'France', flag: '🇫🇷', code: 'fr', region: 'europe', capital: 'Paris', geoFact: 'Most visited country in the world.', similar: ['nl', 'lu', 'ru'] }, // Vertical vs Horizontal
    { name: 'Germany', flag: '🇩🇪', code: 'de', region: 'europe', capital: 'Berlin', geoFact: '1,500 types of beer!', similar: ['be'] },
    { name: 'Italy', flag: '🇮🇹', code: 'it', region: 'europe', capital: 'Rome', geoFact: 'Most UNESCO World Heritage Sites.', similar: ['ie', 'mx'] },
    { name: 'Spain', flag: '🇪🇸', code: 'es', region: 'europe', capital: 'Madrid', geoFact: 'Produces 45% of world\'s olive oil.' },
    { name: 'Ukraine', flag: '🇺🇦', code: 'ua', region: 'europe', capital: 'Kyiv', geoFact: 'Largest country entirely within Europe.' },
    { name: 'Poland', flag: '🇵🇱', code: 'pl', region: 'europe', capital: 'Warsaw', geoFact: 'Home to the world\'s largest castle.', similar: ['id', 'mc'] },
    { name: 'Romania', flag: '🇷🇴', code: 'ro', region: 'europe', capital: 'Bucharest', geoFact: 'Home to the heaviest building in the world.', similar: ['td', 'ad'] },
    { name: 'Netherlands', flag: '🇳🇱', code: 'nl', region: 'europe', capital: 'Amsterdam', geoFact: 'More bikes than people!', similar: ['lu', 'fr', 'ru'] },
    { name: 'Belgium', flag: '🇧🇪', code: 'be', region: 'europe', capital: 'Brussels', geoFact: 'Produces 220,000 tons of chocolate.', similar: ['de', 'ro'] },
    { name: 'Czechia', flag: '🇨🇿', code: 'cz', region: 'europe', capital: 'Prague', geoFact: 'Consumes the most beer per capita.', similar: ['ph'] },
    { name: 'Greece', flag: '🇬🇷', code: 'gr', region: 'europe', capital: 'Athens', geoFact: 'Thousands of islands.' },
    { name: 'Portugal', flag: '🇵🇹', code: 'pt', region: 'europe', capital: 'Lisbon', geoFact: 'Oldest country in Europe with defined borders.' },
    { name: 'Sweden', flag: '🇸🇪', code: 'se', region: 'europe', capital: 'Stockholm', geoFact: 'Imports waste to power energy plants.', similar: ['fi', 'no', 'dk'] },
    { name: 'Hungary', flag: '🇭🇺', code: 'hu', region: 'europe', capital: 'Budapest', geoFact: 'Invented the Rubik\'s Cube.', similar: ['it', 'bg'] },
    { name: 'Belarus', flag: '🇧🇾', code: 'by', region: 'europe', capital: 'Minsk', geoFact: '40% covered by forests.' },
    { name: 'Austria', flag: '🇦🇹', code: 'at', region: 'europe', capital: 'Vienna', geoFact: 'Birthplace of Mozart.', similar: ['lv', 'lb'] },
    { name: 'Switzerland', flag: '🇨🇭', code: 'ch', region: 'europe', capital: 'Bern', geoFact: 'Neutral since 1815.' },
    { name: 'Bulgaria', flag: '🇧🇬', code: 'bg', region: 'europe', capital: 'Sofia', geoFact: 'Oldest country name in Europe.', similar: ['hu', 'it'] },
    { name: 'Serbia', flag: '🇷🇸', code: 'rs', region: 'europe', capital: 'Belgrade', geoFact: 'One of the largest raspberry exporters.', similar: ['ru', 'sk', 'si'] },
    { name: 'Denmark', flag: '🇩🇰', code: 'dk', region: 'europe', capital: 'Copenhagen', geoFact: 'Oldest flag in the world still in use.', similar: ['no', 'se'] },
    { name: 'Finland', flag: '🇫🇮', code: 'fi', region: 'europe', capital: 'Helsinki', geoFact: 'More saunas than cars.', similar: ['se', 'no'] },
    { name: 'Slovakia', flag: '🇸🇰', code: 'sk', region: 'europe', capital: 'Bratislava', geoFact: 'Most castles per capita.', similar: ['si', 'rs', 'ru'] },
    { name: 'Norway', flag: '🇳🇴', code: 'no', region: 'europe', capital: 'Oslo', geoFact: 'Introduced salmon sushi to Japan.', similar: ['is', 'dk'] },
    { name: 'Ireland', flag: '🇮🇪', code: 'ie', region: 'europe', capital: 'Dublin', geoFact: 'St. Patrick was not Irish!', similar: ['ci', 'it'] },
    { name: 'Croatia', flag: '🇭🇷', code: 'hr', region: 'europe', capital: 'Zagreb', geoFact: 'Invented the necktie.', similar: ['nl', 'py'] },
    { name: 'Moldova', flag: '🇲🇩', code: 'md', region: 'europe', capital: 'Chișinău', geoFact: 'Least visited country in Europe.', similar: ['ro', 'ad'] },
    { name: 'Bosnia', flag: '🇧🇦', code: 'ba', region: 'europe', capital: 'Sarajevo', geoFact: 'Sarajevo hosted 1984 Winter Olympics.' },
    { name: 'Albania', flag: '🇦🇱', code: 'al', region: 'europe', capital: 'Tirana', geoFact: 'More Albanians live outside the country than inside.' },
    { name: 'Lithuania', flag: '🇱🇹', code: 'lt', region: 'europe', capital: 'Vilnius', geoFact: 'Has a national scent.', similar: ['mm', 'bo'] },
    { name: 'Macedonia', flag: '🇲🇰', code: 'mk', region: 'europe', capital: 'Skopje', geoFact: 'Mother Teresa was born here.' },
    { name: 'Slovenia', flag: '🇸🇮', code: 'si', region: 'europe', capital: 'Ljubljana', geoFact: 'First crypto-friendly country monument.', similar: ['sk', 'rs'] },
    { name: 'Latvia', flag: '🇱🇻', code: 'lv', region: 'europe', capital: 'Riga', geoFact: 'Invented jeans (Levi Strauss).', similar: ['at'] },
    { name: 'Estonia', flag: '🇪🇪', code: 'ee', region: 'europe', capital: 'Tallinn', geoFact: 'First country to vote online.', similar: ['bw'] },
    { name: 'Luxembourg', flag: '🇱🇺', code: 'lu', region: 'europe', capital: 'Luxembourg', geoFact: 'Last Grand Duchy in the world.', similar: ['nl', 'fr'] },
    { name: 'Malta', flag: '🇲🇹', code: 'mt', region: 'europe', capital: 'Valletta', geoFact: 'Game of Thrones filmed here.' },
    { name: 'Iceland', flag: '🇮🇸', code: 'is', region: 'europe', capital: 'Reykjavik', geoFact: 'No mosquitoes exist here.', similar: ['no', 'gb'] },
    { name: 'Andorra', flag: '🇦🇩', code: 'ad', region: 'europe', capital: 'Andorra la Vella', geoFact: 'Co-principality ruled by two princes.', similar: ['ro', 'md'] },
    { name: 'Monaco', flag: '🇲🇨', code: 'mc', region: 'europe', capital: 'Monaco', geoFact: 'Second smallest country in the world.', similar: ['id', 'pl'] },
    { name: 'Liechtenstein', flag: '🇱🇮', code: 'li', region: 'europe', capital: 'Vaduz', geoFact: 'Largest producer of false teeth.' },
    { name: 'San Marino', flag: '🇸🇲', code: 'sm', region: 'europe', capital: 'San Marino', geoFact: 'Oldest republic in the world.' },
    { name: 'Vatican City', flag: '🇻🇦', code: 'va', region: 'europe', capital: 'Vatican City', geoFact: 'Smallest country in the world.' },

    // --- AMERICAS (30) ---
    { name: 'United States', flag: '🇺🇸', code: 'us', region: 'americas', capital: 'Washington D.C.', geoFact: 'Has the world\'s largest economy.', similar: ['lr', 'my'] },
    { name: 'Brazil', flag: '🇧🇷', code: 'br', region: 'americas', capital: 'Brasília', geoFact: 'Home to the Amazon Rainforest.' },
    { name: 'Mexico', flag: '🇲🇽', code: 'mx', region: 'americas', capital: 'Mexico City', geoFact: 'Introduced chocolate to the world.', similar: ['it'] },
    { name: 'Colombia', flag: '🇨🇴', code: 'co', region: 'americas', capital: 'Bogotá', geoFact: 'No seasons due to being near equator.', similar: ['ec', 've'] },
    { name: 'Argentina', flag: '🇦🇷', code: 'ar', region: 'americas', capital: 'Buenos Aires', geoFact: 'Highest consumption of red meat.', similar: ['sv', 'ni', 'hn'] },
    { name: 'Canada', flag: '🇨🇦', code: 'ca', region: 'americas', capital: 'Ottawa', geoFact: 'Most lakes in the world.' },
    { name: 'Peru', flag: '🇵🇪', code: 'pe', region: 'americas', capital: 'Lima', geoFact: 'Origin of the potato.' },
    { name: 'Venezuela', flag: '🇻🇪', code: 've', region: 'americas', capital: 'Caracas', geoFact: 'Home to Angel Falls.', similar: ['co', 'ec'] },
    { name: 'Chile', flag: '🇨🇱', code: 'cl', region: 'americas', capital: 'Santiago', geoFact: 'Driest desert in the world (Atacama).', similar: ['tx'] }, // Texas flag emoji not available but similar
    { name: 'Ecuador', flag: '🇪🇨', code: 'ec', region: 'americas', capital: 'Quito', geoFact: 'Closest point to space (Mt. Chimborazo).', similar: ['co', 've'] },
    { name: 'Guatemala', flag: '🇬🇹', code: 'gt', region: 'americas', capital: 'Guatemala City', geoFact: 'Invented the first chocolate bar.', similar: ['sv', 'ar'] },
    { name: 'Cuba', flag: '🇨🇺', code: 'cu', region: 'americas', capital: 'Havana', geoFact: 'Known as the "Pearl of the Antilles".', similar: ['pr'] }, // Puerto Rico similar
    { name: 'Haiti', flag: '🇭🇹', code: 'ht', region: 'americas', capital: 'Port-au-Prince', geoFact: 'First independent black republic.', similar: ['li'] },
    { name: 'Dominican Rep.', flag: '🇩🇴', code: 'do', region: 'americas', capital: 'Santo Domingo', geoFact: 'Oldest European settlement in Americas.' },
    { name: 'Honduras', flag: '🇭🇳', code: 'hn', region: 'americas', capital: 'Tegucigalpa', geoFact: 'Known as the Banana Republic.', similar: ['sv', 'ni'] },
    { name: 'Paraguay', flag: '🇵🇾', code: 'py', region: 'americas', capital: 'Asunción', geoFact: 'Only flag with different sides.', similar: ['nl', 'hr'] },
    { name: 'El Salvador', flag: '🇸🇻', code: 'sv', region: 'americas', capital: 'San Salvador', geoFact: 'Smallest country in Central America.', similar: ['ni', 'hn'] },
    { name: 'Nicaragua', flag: '🇳🇮', code: 'ni', region: 'americas', capital: 'Managua', geoFact: 'Largest country in Central America.', similar: ['sv', 'hn'] },
    { name: 'Costa Rica', flag: '🇨🇷', code: 'cr', region: 'americas', capital: 'San José', geoFact: 'No standing army.', similar: ['th'] },
    { name: 'Panama', flag: '🇵🇦', code: 'pa', region: 'americas', capital: 'Panama City', geoFact: 'Can see sunrise on Pacific and set on Atlantic.' },
    { name: 'Uruguay', flag: '🇺🇾', code: 'uy', region: 'americas', capital: 'Montevideo', geoFact: 'First to host Wikipedia server in Latin America.', similar: ['ar', 'gr'] },
    { name: 'Jamaica', flag: '🇯🇲', code: 'jm', region: 'americas', capital: 'Kingston', geoFact: 'First Caribbean country to gain independence.' },
    { name: 'Trinidad', flag: '🇹🇹', code: 'tt', region: 'americas', capital: 'Port of Spain', geoFact: 'Birthplace of the steel pan.' },
    { name: 'Guyana', flag: '🇬🇾', code: 'gy', region: 'americas', capital: 'Georgetown', geoFact: 'Only English speaking country in South America.' },
    { name: 'Suriname', flag: '🇸🇷', code: 'sr', region: 'americas', capital: 'Paramaribo', geoFact: 'Most forested country.' },
    { name: 'Belize', flag: '🇧🇿', code: 'bz', region: 'americas', capital: 'Belmopan', geoFact: 'Only Jaguar reserve in the world.' },
    { name: 'Barbados', flag: '🇧🇧', code: 'bb', region: 'americas', capital: 'Bridgetown', geoFact: 'Birthplace of rum.' },
    { name: 'St. Lucia', flag: '🇱🇨', code: 'lc', region: 'americas', capital: 'Castries', geoFact: 'Only country named after a woman.' },
    { name: 'Grenada', flag: '🇬🇩', code: 'gd', region: 'americas', capital: 'St. George\'s', geoFact: 'Known as the Isle of Spice.' },
    { name: 'Bahamas', flag: '🇧🇸', code: 'bs', region: 'americas', capital: 'Nassau', geoFact: 'Contains 700 islands.' },
    { name: 'Bolivia', flag: '🇧🇴', code: 'bo', region: 'americas', capital: 'Sucre', geoFact: 'Highest capital city (La Paz).', similar: ['gh', 'lt'] },
    { name: 'Puerto Rico', flag: '🇵🇷', code: 'pr', region: 'americas', capital: 'San Juan', geoFact: 'Home to the El Yunque National Forest.', similar: ['cu', 'us'] },

    // --- AFRICA (Expanded) ---
    { name: 'Nigeria', flag: '🇳🇬', code: 'ng', region: 'africa', capital: 'Abuja', geoFact: 'Most populous African country.' },
    { name: 'Ethiopia', flag: '🇪🇹', code: 'et', region: 'africa', capital: 'Addis Ababa', geoFact: 'Only African nation never colonized.', similar: ['gh', 'sn'] },
    { name: 'Egypt', flag: '🇪🇬', code: 'eg', region: 'africa', capital: 'Cairo', geoFact: 'Home to the only remaining Ancient Wonder.', similar: ['ye', 'sy', 'iq'] },
    { name: 'DR Congo', flag: '🇨🇩', code: 'cd', region: 'africa', capital: 'Kinshasa', geoFact: 'Second largest country in Africa.' },
    { name: 'Tanzania', flag: '🇹🇿', code: 'tz', region: 'africa', capital: 'Dodoma', geoFact: 'Home to Mount Kilimanjaro.' },
    { name: 'South Africa', flag: '🇿🇦', code: 'za', region: 'africa', capital: 'Pretoria', geoFact: 'Has three capital cities.' },
    { name: 'Kenya', flag: '🇰🇪', code: 'ke', region: 'africa', capital: 'Nairobi', geoFact: 'First African woman Nobel Peace Prize winner.' },
    { name: 'Uganda', flag: '🇺🇬', code: 'ug', region: 'africa', capital: 'Kampala', geoFact: 'Youngest population in the world.' },
    { name: 'Algeria', flag: '🇩🇿', code: 'dz', region: 'africa', capital: 'Algiers', geoFact: 'Largest country in Africa.', similar: ['pk'] },
    { name: 'Sudan', flag: '🇸🇩', code: 'sd', region: 'africa', capital: 'Khartoum', geoFact: 'More pyramids than Egypt.', similar: ['kw', 'jo', 'ae'] },
    { name: 'Morocco', flag: '🇲🇦', code: 'ma', region: 'africa', capital: 'Rabat', geoFact: 'Oldest university in the world.', similar: ['vn'] },
    { name: 'Angola', flag: '🇦🇴', code: 'ao', region: 'africa', capital: 'Luanda', geoFact: 'Youngest population in world.' },
    { name: 'Mozambique', flag: '🇲🇿', code: 'mz', region: 'africa', capital: 'Maputo', geoFact: 'Only flag with a modern weapon.' },
    { name: 'Ghana', flag: '🇬Ｈ', code: 'gh', region: 'africa', capital: 'Accra', geoFact: 'Center of the world (0°N 0°E).', similar: ['et', 'sn'] },
    { name: 'Madagascar', flag: '🇲🇬', code: 'mg', region: 'africa', capital: 'Antananarivo', geoFact: 'Fourth largest island.' },
    { name: 'Cameroon', flag: '🇨🇲', code: 'cm', region: 'africa', capital: 'Yaoundé', geoFact: 'One of the wettest places on earth.', similar: ['sn', 'ml'] },
    { name: 'Ivory Coast', flag: '🇨🇮', code: 'ci', region: 'africa', capital: 'Yamoussoukro', geoFact: 'Largest cocoa producer.', similar: ['ie'] },
    { name: 'Niger', flag: '🇳🇪', code: 'ne', region: 'africa', capital: 'Niamey', geoFact: 'Named after the Niger River.', similar: ['in'] },
    { name: 'Burkina Faso', flag: '🇧🇫', code: 'bf', region: 'africa', capital: 'Ouagadougou', geoFact: 'Name means "Land of Incorruptible People".' },
    { name: 'Mali', flag: '🇲🇱', code: 'ml', region: 'africa', capital: 'Bamako', geoFact: 'Home to the Great Mosque of Djenné.', similar: ['gn', 'cm'] },
    { name: 'Malawi', flag: '🇲🇼', code: 'mw', region: 'africa', capital: 'Lilongwe', geoFact: 'Known as the Warm Heart of Africa.' },
    { name: 'Zambia', flag: '🇿🇲', code: 'zm', region: 'africa', capital: 'Lusaka', geoFact: 'Home to Victoria Falls.' },
    { name: 'Senegal', flag: '🇸🇳', code: 'sn', region: 'africa', capital: 'Dakar', geoFact: 'Westernmost point of Africa.', similar: ['ml', 'gh'] },
    { name: 'Chad', flag: '🇹🇩', code: 'td', region: 'africa', capital: 'N\'Djamena', geoFact: 'Known as the "Dead Heart of Africa".', similar: ['ro', 'ad'] },
    { name: 'Somalia', flag: '🇸🇴', code: 'so', region: 'africa', capital: 'Mogadishu', geoFact: 'Longest coastline in mainland Africa.', similar: ['fm'] },
    { name: 'Zimbabwe', flag: '🇿🇼', code: 'zw', region: 'africa', capital: 'Harare', geoFact: 'Has 16 official languages.' },
    { name: 'Guinea', flag: '🇬🇳', code: 'gn', region: 'africa', capital: 'Conakry', geoFact: 'Contains the source of the Niger River.', similar: ['ml', 'bo'] },
    { name: 'Rwanda', flag: '🇷🇼', code: 'rw', region: 'africa', capital: 'Kigali', geoFact: 'First country to ban plastic bags.' },
    { name: 'Benin', flag: '🇧🇯', code: 'bj', region: 'africa', capital: 'Porto-Novo', geoFact: 'Birthplace of Voodoo.' },
    { name: 'Burundi', flag: '🇧🇮', code: 'bi', region: 'africa', capital: 'Gitega', geoFact: 'Heart of Africa.' },
    { name: 'Tunisia', flag: '🇹🇳', code: 'tn', region: 'africa', capital: 'Tunis', geoFact: 'Northernmost country in Africa.', similar: ['tr'] },
    { name: 'South Sudan', flag: '🇸🇸', code: 'ss', region: 'africa', capital: 'Juba', geoFact: 'Newest country in the world.' },
    { name: 'Togo', flag: '🇹🇬', code: 'tg', region: 'africa', capital: 'Lomé', geoFact: 'Flag uses golden ratio.' },
    { name: 'Sierra Leone', flag: '🇸🇱', code: 'sl', region: 'africa', capital: 'Freetown', geoFact: 'Home to the third largest natural harbor.' },
    { name: 'Libya', flag: '🇱🇾', code: 'ly', region: 'africa', capital: 'Tripoli', geoFact: '90% is desert.' },
    { name: 'Namibia', flag: '🇳🇦', code: 'na', region: 'africa', capital: 'Windhoek', geoFact: 'Home to the oldest desert.' },
    { name: 'Botswana', flag: '🇧🇼', code: 'bw', region: 'africa', capital: 'Gaborone', geoFact: 'A premier safari destination.', similar: ['ee'] },
    { name: 'Mauritius', flag: '🇲🇺', code: 'mu', region: 'africa', capital: 'Port Louis', geoFact: 'Home of the Dodo bird.' },

    // --- OCEANIA (Expanded) ---
    { name: 'Australia', flag: '🇦🇺', code: 'au', region: 'oceania', capital: 'Canberra', geoFact: 'Wider than the moon.', similar: ['nz', 'gb'] },
    { name: 'Papua N.G.', flag: '🇵🇬', code: 'pg', region: 'oceania', capital: 'Port Moresby', geoFact: '800+ languages spoken.' },
    { name: 'New Zealand', flag: '🇳🇿', code: 'nz', region: 'oceania', capital: 'Wellington', geoFact: 'First to give women right to vote.', similar: ['au', 'gb'] },
    { name: 'Fiji', flag: '🇫🇯', code: 'fj', region: 'oceania', capital: 'Suva', geoFact: 'Islands form a horseshoe shape.', similar: ['tv', 'au'] },
    { name: 'Solomon Is.', flag: '🇸🇧', code: 'sb', region: 'oceania', capital: 'Honiara', geoFact: 'Discovered in 1568.' },
    { name: 'Micronesia', flag: '🇫🇲', code: 'fm', region: 'oceania', capital: 'Palikir', geoFact: 'Made of 607 islands.', similar: ['so'] },
    { name: 'Vanuatu', flag: '🇻🇺', code: 'vu', region: 'oceania', capital: 'Port Vila', geoFact: 'Invented bungee jumping.' },
    { name: 'Samoa', flag: '🇼🇸', code: 'ws', region: 'oceania', capital: 'Apia', geoFact: 'Skipped a day to switch timezones.' },
    { name: 'Kiribati', flag: '🇰🇮', code: 'ki', region: 'oceania', capital: 'South Tarawa', geoFact: 'Only nation in all 4 hemispheres.' },
    { name: 'Tonga', flag: '🇹🇴', code: 'to', region: 'oceania', capital: 'Nuku\'alofa', geoFact: 'Only Pacific nation never colonized.' },
    { name: 'Marshall Is.', flag: '🇲🇭', code: 'mh', region: 'oceania', capital: 'Majuro', geoFact: 'Atomic bomb testing site.' },
    { name: 'Palau', flag: '🇵🇼', code: 'pw', region: 'oceania', capital: 'Ngerulmud', geoFact: 'Created first shark sanctuary.', similar: ['bd', 'jp', 'kz'] },
    { name: 'Tuvalu', flag: '🇹🇻', code: 'tv', region: 'oceania', capital: 'Funafuti', geoFact: 'Earns money from .tv domain.', similar: ['fj'] },
    { name: 'Nauru', flag: '🇳🇷', code: 'nr', region: 'oceania', capital: 'Yaren', geoFact: 'Smallest island nation.' },
    { name: 'Cook Is.', flag: '🇨🇰', code: 'ck', region: 'oceania', capital: 'Avarua', geoFact: 'Created largest shark sanctuary.' }
];
