/**
 * English / Language Arts Question Banks
 * 30-40 questions per game, curriculum-accurate, shuffled at runtime
 */
import { Question } from '../question-banks'

export const ENGLISH_BANKS: Record<string, Question[]> = {

    PHONICS_POND_HOP: [
        { prompt: 'Which word starts with the "sh" sound?', options: ['apple', 'shoe', 'ball', 'cake'], answer: 'shoe', visual: '🎵' },
        { prompt: 'Which word rhymes with "cat"?', options: ['dog', 'bat', 'sun', 'run'], answer: 'bat', visual: '🎵' },
        { prompt: 'What sound does "ph" make?', options: ['p', 'f', 'ph', 'b'], answer: 'f', visual: '🎵' },
        { prompt: '"ch" in "chair" sounds like?', options: ['sh', 'k', 'ch sound as in church', 's'], answer: 'ch sound as in church', visual: '🎵' },
        { prompt: 'Which word has a long "a" sound?', options: ['cat', 'cap', 'cake', 'can'], answer: 'cake', visual: '🎵' },
        { prompt: 'Which letter is silent in "knee"?', options: ['e', 'n', 'k', 'both k and e'], answer: 'k', visual: '🎵' },
        { prompt: 'How many syllables in "butterfly"?', options: ['2', '3', '4', '1'], answer: '3', visual: '🎵' },
        { prompt: 'Which word ends with the "ck" sound?', options: ['milk', 'duck', 'bell', 'fish'], answer: 'duck', visual: '🎵' },
        { prompt: '"oa" in "boat" makes which sound?', options: ['short o', 'long o', 'short a', 'ow'], answer: 'long o', visual: '🎵' },
        { prompt: 'Which word has the short "i" sound?', options: ['bite', 'bike', 'bit', 'by'], answer: 'bit', visual: '🎵' },
        { prompt: 'How many syllables in "elephant"?', options: ['2', '3', '4', '1'], answer: '3', visual: '🎵' },
        { prompt: 'Which letter makes the "j" sound in "giraffe"?', options: ['j', 'g', 'r', 'f'], answer: 'g', visual: '🎵' },
        { prompt: 'Which word rhymes with "moon"?', options: ['sun', 'soon', 'man', 'fun'], answer: 'soon', visual: '🎵' },
        { prompt: 'The "tion" ending sounds like?', options: ['t-ion', 'shun', 'shon', 'teen'], answer: 'shun', visual: '🎵' },
        { prompt: 'Which two letters make the "f" sound in "phone"?', options: ['po', 'ho', 'ph', 'pn'], answer: 'ph', visual: '🎵' },
        { prompt: 'Which word has the "ow" sound as in "cow"?', options: ['low', 'snow', 'town', 'know'], answer: 'town', visual: '🎵' },
        { prompt: 'How many syllables in "tomato"?', options: ['2', '3', '4', '1'], answer: '3', visual: '🎵' },
        { prompt: '"ea" in "read" (present tense) sounds like?', options: ['short e', 'long e', 'short a', 'long a'], answer: 'long e', visual: '🎵' },
        { prompt: 'Which word starts with a vowel?', options: ['cat', 'elephant', 'monkey', 'pig'], answer: 'elephant', visual: '🎵' },
        { prompt: 'The silent letter in "lamb" is?', options: ['a', 'm', 'b', 'l'], answer: 'b', visual: '🎵' },
        { prompt: 'How many syllables in "beautiful"?', options: ['2', '3', '4', '5'], answer: '3', visual: '🎵' },
        { prompt: 'Which word rhymes with "light"?', options: ['list', 'lift', 'night', 'live'], answer: 'night', visual: '🎵' },
        { prompt: '"wr" in "write" — which letter is silent?', options: ['r', 'w', 'i', 't'], answer: 'w', visual: '🎵' },
        { prompt: 'Which word has the "oo" sound as in "food"?', options: ['book', 'foot', 'moon', 'good'], answer: 'moon', visual: '🎵' },
        { prompt: 'The "-ing" suffix adds how many syllables?', options: ['0', '1', '2', '3'], answer: '1', visual: '🎵' },
        { prompt: 'Which word has the "air" sound?', options: ['bar', 'bare', 'blur', 'bar'], answer: 'bare', visual: '🎵' },
        { prompt: '"qu" always sounds like?', options: ['q', 'kw', 'ku', 'kv'], answer: 'kw', visual: '🎵' },
        { prompt: 'How many syllables in "dictionary"?', options: ['3', '4', '5', '6'], answer: '4', visual: '🎵' },
        { prompt: 'Which word is a compound word?', options: ['beautiful', 'football', 'running', 'jumped'], answer: 'football', visual: '🎵' },
        { prompt: 'The prefix "un-" means?', options: ['again', 'before', 'not', 'under'], answer: 'not', visual: '🎵' },
    ],

    LETTER_LASSO: [
        { prompt: 'Which is a vowel?', options: ['b', 'c', 'e', 'g'], answer: 'e', visual: '✏️' },
        { prompt: 'Capital of "a" is?', options: ['A', 'B', 'C', 'D'], answer: 'A', visual: '✏️' },
        { prompt: 'Which letter comes after "M" in the alphabet?', options: ['L', 'N', 'K', 'O'], answer: 'N', visual: '✏️' },
        { prompt: 'How many vowels in the English alphabet?', options: ['4', '5', '6', '7'], answer: '5', visual: '✏️' },
        { prompt: 'Which letter comes before "Z"?', options: ['X', 'Y', 'W', 'V'], answer: 'Y', visual: '✏️' },
        { prompt: 'Which pair are both vowels?', options: ['a, b', 'e, i', 'c, d', 'f, g'], answer: 'e, i', visual: '✏️' },
        { prompt: '"B" in lowercase is?', options: ['b', 'd', 'p', 'q'], answer: 'b', visual: '✏️' },
        { prompt: 'Which letter looks the same upside down?', options: ['b', 'd', 'o', 'p'], answer: 'o', visual: '✏️' },
        { prompt: 'Which comes first in alphabet: "K" or "G"?', options: ['K', 'G', 'Same', 'Neither'], answer: 'G', visual: '✏️' },
        { prompt: 'How many letters in the alphabet?', options: ['24', '25', '26', '27'], answer: '26', visual: '✏️' },
        { prompt: 'Which is NOT a consonant?', options: ['b', 'd', 'u', 'm'], answer: 'u', visual: '✏️' },
        { prompt: 'Which letter makes the "ks" sound?', options: ['c', 'k', 'x', 'z'], answer: 'x', visual: '✏️' },
        { prompt: 'Lowercase of "W" is?', options: ['m', 'w', 'n', 'v'], answer: 'w', visual: '✏️' },
        { prompt: 'Which two letters look most similar?', options: ['a and e', 'b and d', 'c and g', 'm and n'], answer: 'b and d', visual: '✏️' },
        { prompt: 'Which letter is 13th in the alphabet?', options: ['L', 'M', 'N', 'O'], answer: 'M', visual: '✏️' },
        { prompt: '"Y" is sometimes considered a?', options: ['consonant only', 'vowel only', 'vowel or consonant', 'neither'], answer: 'vowel or consonant', visual: '✏️' },
        { prompt: 'Which letter can be both uppercase and lowercase the same?', options: ['A', 'C', 'O', 'S'], answer: 'O', visual: '✏️' },
        { prompt: 'Which letter is 26th?', options: ['X', 'Y', 'Z', 'W'], answer: 'Z', visual: '✏️' },
        { prompt: '"Q" is almost always followed by?', options: ['u', 'a', 'e', 'i'], answer: 'u', visual: '✏️' },
        { prompt: 'Which letter makes the "n" sound in "phone"?', options: ['p', 'h', 'n', 'none'], answer: 'n', visual: '✏️' },
        { prompt: 'How many consonants in the alphabet?', options: ['19', '20', '21', '22'], answer: '21', visual: '✏️' },
        { prompt: 'Which letter is first in the alphabet?', options: ['A', 'B', 'C', 'E'], answer: 'A', visual: '✏️' },
        { prompt: 'Uppercase of "g" is?', options: ['G', 'Q', 'C', 'J'], answer: 'G', visual: '✏️' },
        { prompt: 'Which pair of letters look mirror images?', options: ['b and p', 'c and d', 'f and t', 'm and w'], answer: 'b and p', visual: '✏️' },
        { prompt: '"V" sounds like — which animal?', options: ['fox', 'vulture', 'viper', 'all of above include v'], answer: 'vulture', visual: '✏️' },
        { prompt: 'Which letter is between "H" and "J"?', options: ['G', 'I', 'K', 'L'], answer: 'I', visual: '✏️' },
        { prompt: 'How many letters in "ALPHABET"?', options: ['7', '8', '9', '10'], answer: '8', visual: '✏️' },
        { prompt: 'Which position is "P" in the alphabet?', options: ['14th', '15th', '16th', '17th'], answer: '16th', visual: '✏️' },
        { prompt: 'Which set contains ONLY vowels?', options: ['a,e,i,o,u', 'a,b,e,i,o', 'a,e,i,u,y', 'e,i,o,u,w'], answer: 'a,e,i,o,u', visual: '✏️' },
        { prompt: 'The word "EDUCATION" starts with a?', options: ['Consonant', 'Vowel', 'Number', 'Symbol'], answer: 'Vowel', visual: '✏️' },
    ],

    VOWEL_VILLAGE: [
        { prompt: 'Which word has a short "a" sound?', options: ['cake', 'late', 'cat', 'came'], answer: 'cat', visual: '🌈' },
        { prompt: 'Which word has a long "e" sound?', options: ['bed', 'red', 'bead', 'head'], answer: 'bead', visual: '🌈' },
        { prompt: 'Which is a vowel?', options: ['b', 'f', 'o', 't'], answer: 'o', visual: '🌈' },
        { prompt: '"boat" has which vowel combo?', options: ['oa', 'oe', 'oo', 'ou'], answer: 'oa', visual: '🌈' },
        { prompt: 'Which word has the long "i" sound?', options: ['bit', 'bid', 'bin', 'bike'], answer: 'bike', visual: '🌈' },
        { prompt: 'How many vowels in the word "beautiful"?', options: ['3', '4', '5', '6'], answer: '5', visual: '🌈' },
        { prompt: 'Which word has a short "o" sound?', options: ['bone', 'home', 'hot', 'hope'], answer: 'hot', visual: '🌈' },
        { prompt: 'Which vowel is in "cup"?', options: ['a', 'e', 'i', 'u'], answer: 'u', visual: '🌈' },
        { prompt: 'Which word has the "oo" sound?', options: ['foot', 'moon', 'book', 'good'], answer: 'moon', visual: '🌈' },
        { prompt: '"Silent e" rule: adding "e" makes the vowel?', options: ['short', 'long', 'silent', 'disappear'], answer: 'long', visual: '🌈' },
        { prompt: 'Which word follows the "silent e" rule?', options: ['cat', 'hat', 'cape', 'cap'], answer: 'cape', visual: '🌈' },
        { prompt: 'Which has the short "e"?', options: ['eat', 'equal', 'egg', 'eagle'], answer: 'egg', visual: '🌈' },
        { prompt: '"ai" in "rain" makes which sound?', options: ['short a', 'long a', 'short i', 'long i'], answer: 'long a', visual: '🌈' },
        { prompt: '"igh" in "night" sounds like?', options: ['long i', 'long g', 'short i', 'long h'], answer: 'long i', visual: '🌈' },
        { prompt: 'Which has a long "o"?', options: ['hot', 'lot', 'note', 'not'], answer: 'note', visual: '🌈' },
        { prompt: 'How many vowels in "rhythm"?', options: ['0', '1', '2', '3'], answer: '1', visual: '🌈' },
        { prompt: '"ou" in "house" sounds like?', options: ['long o', 'ow as in cow', 'oo', 'uh'], answer: 'ow as in cow', visual: '🌈' },
        { prompt: 'Which has two vowels together (vowel digraph)?', options: ['cat', 'heat', 'bit', 'hut'], answer: 'heat', visual: '🌈' },
        { prompt: '"ew" in "new" sounds like?', options: ['short e', 'long u/oo', 'long e', 'short u'], answer: 'long u/oo', visual: '🌈' },
        { prompt: 'Which word has a diphthong (two vowel sounds)?', options: ['bat', 'beat', 'boy', 'bet'], answer: 'boy', visual: '🌈' },
        { prompt: 'The schwa sound (ə) appears in the word?', options: ['cat', 'the', 'hit', 'top'], answer: 'the', visual: '🌈' },
        { prompt: 'Which has the long "u"?', options: ['bus', 'but', 'mule', 'mud'], answer: 'mule', visual: '🌈' },
        { prompt: '"ea" in "bread" sounds like?', options: ['long e', 'short e', 'long a', 'short a'], answer: 'short e', visual: '🌈' },
        { prompt: 'Which vowel changes the meaning most: "bit" vs ___?', options: ['bat', 'bot', 'but', 'all of these'], answer: 'all of these', visual: '🌈' },
        { prompt: 'R-controlled vowel: "ar" sounds like in "car":?', options: ['ay', 'ah-r', 'air', 'err'], answer: 'ah-r', visual: '🌈' },
        { prompt: 'Which has the "oy" sound?', options: ['coin', 'cone', 'noon', 'loan'], answer: 'coin', visual: '🌈' },
        { prompt: '"ue" in "blue" sounds like?', options: ['long u', 'short u', 'ew', 'all of above'], answer: 'long u', visual: '🌈' },
        { prompt: 'How many vowel sounds in "elephant"?', options: ['2', '3', '4', '5'], answer: '3', visual: '🌈' },
        { prompt: '"ie" in "pie" sounds like?', options: ['long i', 'long e', 'short i', 'short e'], answer: 'long i', visual: '🌈' },
        { prompt: 'Which word has NO vowel sound? (trick question)', options: ['cry', 'gym', 'myth', 'None — all have vowel sounds'], answer: 'None — all have vowel sounds', visual: '🌈' },
    ],

    TENSE_TREKKER: [
        { prompt: '"She __ (go) to school every day." Correct form?', options: ['go', 'goes', 'went', 'gone'], answer: 'goes', visual: '⏰' },
        { prompt: 'Past tense of "run"?', options: ['runned', 'ran', 'runs', 'raned'], answer: 'ran', visual: '⏰' },
        { prompt: 'Future tense of "eat"?', options: ['ate', 'eaten', 'will eat', 'eats'], answer: 'will eat', visual: '⏰' },
        { prompt: '"They __ playing when it rained." Fill in:', options: ['are', 'were', 'was', 'is'], answer: 'were', visual: '⏰' },
        { prompt: 'Past tense of "write"?', options: ['writed', 'written', 'wrote', 'writ'], answer: 'wrote', visual: '⏰' },
        { prompt: '"I have __ (see) that movie." Correct form?', options: ['saw', 'seen', 'see', 'sawed'], answer: 'seen', visual: '⏰' },
        { prompt: 'Which sentence is in simple past?', options: ['She sings', 'She sang', 'She has sung', 'She will sing'], answer: 'She sang', visual: '⏰' },
        { prompt: 'Past tense of "bring"?', options: ['bringed', 'brung', 'brought', 'brings'], answer: 'brought', visual: '⏰' },
        { prompt: '"By 5 PM, I __ (finish) my homework." Best tense?', options: ['will finish', 'will have finished', 'finished', 'finish'], answer: 'will have finished', visual: '⏰' },
        { prompt: 'Which is present perfect?', options: ['I eat', 'I ate', 'I have eaten', 'I was eating'], answer: 'I have eaten', visual: '⏰' },
        { prompt: 'Past tense of "choose"?', options: ['choosed', 'chosed', 'chosen', 'chose'], answer: 'chose', visual: '⏰' },
        { prompt: '"While I __ (read), the phone rang." Fill in:', options: ['read', 'was reading', 'reads', 'have read'], answer: 'was reading', visual: '⏰' },
        { prompt: 'Which is past continuous?', options: ['She ran', 'She runs', 'She was running', 'She had run'], answer: 'She was running', visual: '⏰' },
        { prompt: 'Past tense of "fly"?', options: ['flied', 'flyed', 'flew', 'flown'], answer: 'flew', visual: '⏰' },
        { prompt: '"I __ (not see) him since Monday." Correct form?', options: ['don\'t see', 'didn\'t see', 'haven\'t seen', 'hadn\'t seen'], answer: 'haven\'t seen', visual: '⏰' },
        { prompt: 'Which tense describes a habit in the past?', options: ['Simple past', 'Used to', 'Past perfect', 'Past continuous'], answer: 'Used to', visual: '⏰' },
        { prompt: 'Past participle of "break"?', options: ['broke', 'braked', 'broken', 'breaked'], answer: 'broken', visual: '⏰' },
        { prompt: '"He said he __ (be) tired." Correct indirect speech?', options: ['is', 'was', 'were', 'had been'], answer: 'was', visual: '⏰' },
        { prompt: 'Which sentence uses future perfect?', options: ['I will go', 'I will be going', 'I will have gone', 'I go'], answer: 'I will have gone', visual: '⏰' },
        { prompt: 'Past tense of "sink"?', options: ['sinked', 'sinked', 'sank', 'sunk'], answer: 'sank', visual: '⏰' },
        { prompt: '"By the time he arrived, we __ (leave)." Fill in:', options: ['left', 'have left', 'had left', 'were leaving'], answer: 'had left', visual: '⏰' },
        { prompt: 'Which tense: "I am going to study tomorrow."', options: ['Simple future', 'Future plan (going to)', 'Present continuous', 'Future perfect'], answer: 'Future plan (going to)', visual: '⏰' },
        { prompt: 'Past tense of "rise"?', options: ['rised', 'risen', 'rose', 'arised'], answer: 'rose', visual: '⏰' },
        { prompt: '"They __ (work) here for 10 years." Present perfect?', options: ['work', 'worked', 'have worked', 'had worked'], answer: 'have worked', visual: '⏰' },
        { prompt: 'Past tense of "bite"?', options: ['bited', 'bitten', 'bit', 'biten'], answer: 'bit', visual: '⏰' },
        { prompt: 'Which correctly uses past perfect?', options: ['She had went', 'She had gone', 'She have gone', 'She has went'], answer: 'She had gone', visual: '⏰' },
        { prompt: 'Future continuous: "This time tomorrow, I __."', options: ['will study', 'will be studying', 'am studying', 'have studied'], answer: 'will be studying', visual: '⏰' },
        { prompt: 'Past tense of "lie down"?', options: ['lied', 'laid', 'lay', 'lain'], answer: 'lay', visual: '⏰' },
        { prompt: '"If I __ (study), I would pass." Conditional form?', options: ['study', 'studied', 'had studied', 'will study'], answer: 'studied', visual: '⏰' },
        { prompt: 'Which is NOT an irregular verb?', options: ['go-went', 'run-ran', 'jump-jumped', 'see-saw'], answer: 'jump-jumped', visual: '⏰' },
    ],

    PUNCTUATION_RUSH: [
        { prompt: 'Which punctuation ends a statement?', options: [',', '.', ':', ';'], answer: '.', visual: '🧩' },
        { prompt: 'What goes at the end of a question?', options: ['!', '.', ',', '?'], answer: '?', visual: '🧩' },
        { prompt: '"Wow that\'s amazing" needs which mark at the end?', options: ['.', '?', '!', ','], answer: '!', visual: '🧩' },
        { prompt: 'Which mark separates items in a list?', options: ['.', '!', ',', ':'], answer: ',', visual: '🧩' },
        { prompt: '"Tom said (blank) I am tired." Fill the blank:', options: [',', ':', '"', '('], answer: '"', visual: '🧩' },
        { prompt: 'An apostrophe in "it\'s" shows?', options: ['Possession', 'Contraction', 'Plural', 'Omission of letters'], answer: 'Contraction', visual: '🧩' },
        { prompt: '"The boy\'s bag" — apostrophe shows?', options: ['Contraction', 'Plural', 'Possession', 'All three'], answer: 'Possession', visual: '🧩' },
        { prompt: 'Which uses correct punctuation?', options: ['Lets eat, Grandma!', 'Lets eat Grandma!', 'Let\'s eat Grandma!', 'Let\'s eat, grandma'], answer: "Let's eat, Grandma!", visual: '🧩' },
        { prompt: 'A colon (:) is used before?', options: ['A list or explanation', 'A question', 'An exclamation', 'A new sentence'], answer: 'A list or explanation', visual: '🧩' },
        { prompt: 'Which sentence is correctly punctuated?', options: ['I like cats dogs and fish.', 'I like cats, dogs and fish.', 'I like cats, dogs, and fish.', 'i like cats dogs, and fish'], answer: 'I like cats, dogs, and fish.', visual: '🧩' },
        { prompt: 'Semicolon (;) connects?', options: ['Two unrelated clauses', 'Two related independent clauses', 'A list', 'A question'], answer: 'Two related independent clauses', visual: '🧩' },
        { prompt: '"Its" without apostrophe means?', options: ['It is', 'It has', 'Belonging to it', 'Both A and B'], answer: 'Belonging to it', visual: '🧩' },
        { prompt: 'Which is a run-on sentence (missing punctuation)?', options: ['She ran fast.', 'She ran fast she tripped.', 'She ran fast, but tripped.', 'She ran fast; she tripped.'], answer: 'She ran fast she tripped.', visual: '🧩' },
        { prompt: 'Ellipsis (…) is used to show?', options: ['Excitement', 'A pause or trailing off', 'A list', 'Possession'], answer: 'A pause or trailing off', visual: '🧩' },
        { prompt: '"childrens\' books" — is this correct?', options: ['Yes', 'No — should be "children\'s books"', 'No — "childrens books"', 'No — "children books"'], answer: "No — should be \"children's books\"", visual: '🧩' },
        { prompt: 'Which sentence needs a question mark?', options: ['She left early.', 'Did she leave early', 'What a mess!', 'I wonder if she left early.'], answer: 'Did she leave early', visual: '🧩' },
        { prompt: 'Parentheses () are used for?', options: ['Emphasis', 'Extra or side information', 'Questions', 'Lists only'], answer: 'Extra or side information', visual: '🧩' },
        { prompt: '"The students, who studied hard, all passed." Commas here show?', options: ['A list', 'Non-restrictive clause', 'Direct address', 'Pause only'], answer: 'Non-restrictive clause', visual: '🧩' },
        { prompt: 'Which correctly uses a hyphen?', options: ['Well-known author', 'Well known author', 'Well, known author', 'Well known-author'], answer: 'Well-known author', visual: '🧩' },
        { prompt: 'Which sentence uses correct capitalisation?', options: ['I live in london.', 'i live in London.', 'I live in London.', 'I Live In London.'], answer: 'I live in London.', visual: '🧩' },
        { prompt: 'A dash (—) is used for?', options: ['A list only', 'Emphasis or an aside', 'Contraction', 'Plural'], answer: 'Emphasis or an aside', visual: '🧩' },
        { prompt: 'Which is correctly punctuated dialogue?', options: ['"Hello," she said.', 'Hello," she said.', '"Hello" she said.', 'Hello, she said.'], answer: '"Hello," she said.', visual: '🧩' },
        { prompt: '"boys\' locker room" — how many boys?', options: ['One', 'More than one', 'Unknown', 'Both'], answer: 'More than one', visual: '🧩' },
        { prompt: 'Inverted commas/quotation marks are used for?', options: ['Definitions', 'Direct speech', 'Emphasis', 'All of the above'], answer: 'Direct speech', visual: '🧩' },
        { prompt: 'Which sentence is correctly punctuated?', options: ['After eating the lions rested.', 'After eating the lions, rested.', 'After eating, the lions rested.', 'After, eating the lions rested.'], answer: 'After eating, the lions rested.', visual: '🧩' },
        { prompt: '"Who\'s" is a contraction of?', options: ['Whose', 'Who is / who has', 'Who was', 'Who were'], answer: 'Who is / who has', visual: '🧩' },
        { prompt: 'Where does the period go with closing quotation marks (US style)?', options: ['Before the quotes', 'After the quotes', 'Outside', 'No period needed'], answer: 'Before the quotes', visual: '🧩' },
        { prompt: 'Which correctly lists items?', options: ['red: blue: green', 'red, blue, green', 'red; blue; green.', 'red. blue. green'], answer: 'red, blue, green', visual: '🧩' },
        { prompt: 'An exclamation mark (!) expresses?', options: ['A question', 'Strong emotion or command', 'A list', 'A pause'], answer: 'Strong emotion or command', visual: '🧩' },
        { prompt: '"It\'s going to rain. Bring your umbrella." How many sentences?', options: ['1', '2', '3', '0'], answer: '2', visual: '🧩' },
    ],

    IDIOM_HUNTER: [
        { prompt: '"Break the ice" means?', options: ['Crack real ice', 'Start a conversation', 'Win a game', 'Get cold'], answer: 'Start a conversation', visual: '🏹' },
        { prompt: '"Hit the nail on the head" means?', options: ['Hurt yourself', 'Be exactly right', 'Do DIY', 'Miss the point'], answer: 'Be exactly right', visual: '🏹' },
        { prompt: '"Under the weather" means?', options: ['Outside', 'Feeling ill', 'Cloudy day', 'In the rain'], answer: 'Feeling ill', visual: '🏹' },
        { prompt: '"Beat around the bush" means?', options: ['Avoid the main point', 'Hit a bush', 'Win a race', 'Hide in bushes'], answer: 'Avoid the main point', visual: '🏹' },
        { prompt: '"Cost an arm and a leg" means?', options: ['Medical bill', 'Very expensive', 'Free', 'Medium price'], answer: 'Very expensive', visual: '🏹' },
        { prompt: '"Let the cat out of the bag" means?', options: ['Free a cat', 'Reveal a secret', 'Open a bag', 'Buy groceries'], answer: 'Reveal a secret', visual: '🏹' },
        { prompt: '"Bite the bullet" means?', options: ['Eat carefully', 'Endure pain bravely', 'Shoot a gun', 'Bite food'], answer: 'Endure pain bravely', visual: '🏹' },
        { prompt: '"Spill the beans" means?', options: ['Drop food', 'Share a secret', 'Cook dinner', 'Be messy'], answer: 'Share a secret', visual: '🏹' },
        { prompt: '"A piece of cake" means?', options: ['Eating dessert', 'Something very easy', 'Birthday party', 'Small task'], answer: 'Something very easy', visual: '🏹' },
        { prompt: '"Burn bridges" means?', options: ['Destroy roads', 'Permanently damage relationships', 'Light a fire', 'Travel'], answer: 'Permanently damage relationships', visual: '🏹' },
        { prompt: '"Once in a blue moon" means?', options: ['Monthly', 'Rarely', 'Never', 'Often'], answer: 'Rarely', visual: '🏹' },
        { prompt: '"Tie the knot" means?', options: ['Actual knot', 'Get married', 'Start work', 'Sew clothes'], answer: 'Get married', visual: '🏹' },
        { prompt: '"Kill two birds with one stone" means?', options: ['Hunt birds', 'Solve two problems at once', 'Be violent', 'Throw stones'], answer: 'Solve two problems at once', visual: '🏹' },
        { prompt: '"Bite off more than you can chew" means?', options: ['Eat too much', 'Take on more than you can handle', 'Get hurt', 'Be greedy with food'], answer: 'Take on more than you can handle', visual: '🏹' },
        { prompt: '"Speak of the devil" is said when?', options: ['Talking about evil', 'Someone appears just as you mention them', 'Warning others', 'Starting a story'], answer: 'Someone appears just as you mention them', visual: '🏹' },
        { prompt: '"Every cloud has a silver lining" means?', options: ['Clouds are metallic', 'Every bad situation has a good aspect', 'Weather is nice', 'Cloudy skies are good'], answer: 'Every bad situation has a good aspect', visual: '🏹' },
        { prompt: '"Hit the sack" means?', options: ['Punch a bag', 'Go to sleep', 'Hit someone', 'Play sport'], answer: 'Go to sleep', visual: '🏹' },
        { prompt: '"The ball is in your court" means?', options: ['Play basketball', 'It\'s your decision', 'You won', 'Go to court'], answer: "It's your decision", visual: '🏹' },
        { prompt: '"Throw in the towel" means?', options: ['Do laundry', 'Give up', 'Play sports', 'Win'], answer: 'Give up', visual: '🏹' },
        { prompt: '"On the fence" means?', options: ['Sitting on a fence', 'Undecided', 'Watching', 'Outside'], answer: 'Undecided', visual: '🏹' },
        { prompt: '"Pull someone\'s leg" means?', options: ['Trip them', 'Joke with them', 'Help them', 'Harm them'], answer: 'Joke with them', visual: '🏹' },
        { prompt: '"Bite the hand that feeds you" means?', options: ['Be ungrateful to someone who helps you', 'Bite animals', 'Dislike food', 'Be aggressive'], answer: 'Be ungrateful to someone who helps you', visual: '🏹' },
        { prompt: '"The last straw" means?', options: ['Final piece of hay', 'Breaking point after many problems', 'Last drink', 'End of a straw'], answer: 'Breaking point after many problems', visual: '🏹' },
        { prompt: '"Add fuel to the fire" means?', options: ['Light a fire', 'Make a bad situation worse', 'Help someone', 'Add energy'], answer: 'Make a bad situation worse', visual: '🏹' },
        { prompt: '"A blessing in disguise" means?', options: ['A priest\'s disguise', 'Something good that seemed bad at first', 'Literal disguise', 'A religious gift'], answer: 'Something good that seemed bad at first', visual: '🏹' },
        { prompt: '"Go back to the drawing board" means?', options: ['Return to art class', 'Start over from the beginning', 'Draw a picture', 'Board a ship'], answer: 'Start over from the beginning', visual: '🏹' },
        { prompt: '"Hit the road" means?', options: ['Fix roads', 'Start travelling', 'Hit pavement', 'Drive fast'], answer: 'Start travelling', visual: '🏹' },
        { prompt: '"Take with a grain of salt" means?', options: ['Season food', 'Be sceptical of information', 'Eat carefully', 'Add salt'], answer: 'Be sceptical of information', visual: '🏹' },
        { prompt: '"Up in the air" means?', options: ['Flying', 'Uncertain or undecided', 'High altitude', 'Excited'], answer: 'Uncertain or undecided', visual: '🏹' },
        { prompt: '"On the same page" means?', options: ['Reading same book', 'Having same understanding', 'Sitting together', 'Being equal'], answer: 'Having same understanding', visual: '🏹' },
    ],

    COMPREHENSION_CODEBREAKER: [
        { prompt: 'An inference is when you?', options: ['Read literally', 'Use text + knowledge to figure something out', 'Guess randomly', 'Copy from the text'], answer: 'Use text + knowledge to figure something out', visual: '📖' },
        { prompt: 'The main idea of a passage is?', options: ['First sentence', 'Last sentence', 'Central point the whole passage is about', 'Most interesting fact'], answer: 'Central point the whole passage is about', visual: '📖' },
        { prompt: 'A synonym for "enormous" is?', options: ['tiny', 'large', 'modest', 'slight'], answer: 'large', visual: '📖' },
        { prompt: 'When the author says "John\'s heart sank," they mean John was?', options: ['Physically ill', 'Drowning', 'Very disappointed', 'Surprised'], answer: 'Very disappointed', visual: '📖' },
        { prompt: 'Reading between the lines means?', options: ['Fast reading', 'Understanding implied meaning', 'Skimming', 'Line-by-line reading'], answer: 'Understanding implied meaning', visual: '📖' },
        { prompt: 'A fable typically ends with a?', options: ['Twist', 'Moral lesson', 'Surprise', 'Cliffhanger'], answer: 'Moral lesson', visual: '📖' },
        { prompt: '"The character paced anxiously" suggests the character was?', options: ['Excited', 'Nervous or worried', 'Happy', 'Tired'], answer: 'Nervous or worried', visual: '📖' },
        { prompt: 'A biography is written about?', options: ['Fictional character', 'The author themselves', 'Someone else\'s real life', 'A made-up place'], answer: "Someone else's real life", visual: '📖' },
        { prompt: 'Context clues help you determine?', options: ['A word\'s meaning from surrounding text', 'The setting', 'Author\'s purpose', 'Passage length'], answer: "A word's meaning from surrounding text", visual: '📖' },
        { prompt: 'The word "however" signals?', options: ['Agreement', 'Contrast or contradiction', 'Cause', 'Result'], answer: 'Contrast or contradiction', visual: '📖' },
        { prompt: 'An autobiography is written?', options: ['By someone else', 'By the subject themselves', 'By a journalist', 'By a teacher'], answer: 'By the subject themselves', visual: '📖' },
        { prompt: '"First… then… finally…" are examples of?', options: ['Character traits', 'Sequence/chronological signal words', 'Opinion words', 'Evidence words'], answer: 'Sequence/chronological signal words', visual: '📖' },
        { prompt: 'The purpose of a persuasive text is to?', options: ['Entertain', 'Inform', 'Convince the reader', 'Tell a story'], answer: 'Convince the reader', visual: '📖' },
        { prompt: 'A narrative text primarily?', options: ['Argues a point', 'Explains how to do something', 'Tells a story', 'Lists facts'], answer: 'Tells a story', visual: '📖' },
        { prompt: 'Summarising means?', options: ['Copying the whole passage', 'Retelling main points briefly', 'Adding your opinion', 'Expanding the text'], answer: 'Retelling main points briefly', visual: '📖' },
        { prompt: 'The word "therefore" signals?', options: ['Contrast', 'Cause and effect conclusion', 'New idea', 'List'], answer: 'Cause and effect conclusion', visual: '📖' },
        { prompt: 'An expository text is meant to?', options: ['Entertain', 'Persuade', 'Explain/inform', 'Frighten'], answer: 'Explain/inform', visual: '📖' },
        { prompt: '"She bit her lip" usually suggests she was?', options: ['Hungry', 'Anxious/unsure', 'Angry', 'Confused'], answer: 'Anxious/unsure', visual: '📖' },
        { prompt: 'Point of view: "I walked into the room" is in?', options: ['First person', 'Second person', 'Third person limited', 'Third person omniscient'], answer: 'First person', visual: '📖' },
        { prompt: 'Which is a fact (not opinion)?', options: ['The film was exciting.', 'The Earth orbits the Sun.', 'Chocolate is the best flavour.', 'Cats are better than dogs.'], answer: 'The Earth orbits the Sun.', visual: '📖' },
        { prompt: 'A text\'s "tone" refers to?', options: ['Volume', 'Author\'s attitude or feeling', 'Font size', 'Number of paragraphs'], answer: "Author's attitude or feeling", visual: '📖' },
        { prompt: 'Which reading strategy helps comprehension most?', options: ['Reading without pausing', 'Asking questions while reading', 'Reading only the first paragraph', 'Speed reading only'], answer: 'Asking questions while reading', visual: '📖' },
        { prompt: 'The climax of a story is?', options: ['The beginning', 'The resolution', 'The turning point/most intense moment', 'The setting'], answer: 'The turning point/most intense moment', visual: '📖' },
        { prompt: '"For example" signals?', options: ['Contrast', 'Conclusion', 'Illustration/evidence', 'New topic'], answer: 'Illustration/evidence', visual: '📖' },
        { prompt: 'What does "chronologically" mean in a text?', options: ['In random order', 'In the order events occurred', 'From most to least important', 'Alphabetically'], answer: 'In the order events occurred', visual: '📖' },
        { prompt: 'A character\'s motivation is?', options: ['Their appearance', 'The reason behind their actions', 'Where they live', 'How they speak'], answer: 'The reason behind their actions', visual: '📖' },
        { prompt: 'The theme of a story is?', options: ['The title', 'Where it takes place', 'The central message or lesson', 'Who the characters are'], answer: 'The central message or lesson', visual: '📖' },
        { prompt: '"On the other hand" signals?', options: ['Agreement', 'Elaboration', 'Contrast/alternative view', 'Summary'], answer: 'Contrast/alternative view', visual: '📖' },
        { prompt: 'Which is subjective (opinion-based)?', options: ['Water freezes at 0°C.', 'She was the greatest leader.', 'The Amazon is the largest rainforest.', 'DNA carries genetic information.'], answer: 'She was the greatest leader.', visual: '📖' },
        { prompt: 'When you paraphrase, you?', options: ['Quote directly', 'Restate in your own words', 'Copy with quotation marks', 'Summarise the plot'], answer: 'Restate in your own words', visual: '📖' },
    ],

    ESSAY_ENGINEER: [
        { prompt: 'An essay\'s thesis statement should be in the?', options: ['Conclusion', 'Middle paragraph', 'Introduction', 'Title'], answer: 'Introduction', visual: '📰' },
        { prompt: 'Topic sentences belong at the?', options: ['End of each paragraph', 'Beginning of each body paragraph', 'End of the essay', 'Middle of each paragraph'], answer: 'Beginning of each body paragraph', visual: '📰' },
        { prompt: 'PEEL stands for?', options: ['Point, Explain, Evidence, Link', 'Point, Essay, Example, Learn', 'Paragraph, Explain, Evidence, Language', 'Plan, Edit, Expand, Link'], answer: 'Point, Explain, Evidence, Link', visual: '📰' },
        { prompt: 'Which transition best shows contrast?', options: ['Furthermore', 'In addition', 'However', 'Therefore'], answer: 'However', visual: '📰' },
        { prompt: 'Which transition shows cause and effect?', options: ['However', 'On the other hand', 'Consequently', 'In contrast'], answer: 'Consequently', visual: '📰' },
        { prompt: 'A conclusion should?', options: ['Introduce new ideas', 'Restate and summarise main points', 'Add more evidence', 'List definitions'], answer: 'Restate and summarise main points', visual: '📰' },
        { prompt: 'Formal essays should avoid?', options: ['Evidence', 'Contractions like "don\'t"', 'Topic sentences', 'Arguments'], answer: "Contractions like \"don't\"", visual: '📰' },
        { prompt: 'Which makes the strongest argument?', options: ['Personal story', 'Peer-reviewed statistics', 'Your opinion', 'Exaggeration'], answer: 'Peer-reviewed statistics', visual: '📰' },
        { prompt: 'Coherence in an essay means?', options: ['Good vocabulary', 'Ideas flow logically and connect well', 'Long paragraphs', 'No grammar errors'], answer: 'Ideas flow logically and connect well', visual: '📰' },
        { prompt: 'The purpose of evidence in an essay is to?', options: ['Make it longer', 'Support and prove your argument', 'Impress the reader', 'Avoid repetition'], answer: 'Support and prove your argument', visual: '📰' },
        { prompt: 'Which is an effective hook sentence?', options: ['This essay will discuss climate change.', 'Climate change is bad.', 'In 2050, rising seas may swallow coastal cities.', 'My essay is about climate change.'], answer: 'In 2050, rising seas may swallow coastal cities.', visual: '📰' },
        { prompt: 'Counterargument in an essay means?', options: ['Agreeing with everything', 'Acknowledging and refuting opposing views', 'Repeating your main argument', 'Changing your conclusion'], answer: 'Acknowledging and refuting opposing views', visual: '📰' },
        { prompt: '"In conclusion" belongs in the?', options: ['Introduction', 'Body paragraph 1', 'Body paragraph 2', 'Conclusion'], answer: 'Conclusion', visual: '📰' },
        { prompt: 'Which is NOT a valid source for an essay?', options: ['Academic journal', 'Wikipedia (unverified)', 'Government statistics', 'Peer-reviewed book'], answer: 'Wikipedia (unverified)', visual: '📰' },
        { prompt: 'Which transition adds more information?', options: ['However', 'Nevertheless', 'Furthermore', 'Although'], answer: 'Furthermore', visual: '📰' },
        { prompt: 'Plagiarism means?', options: ['Using your own ideas', 'Copying others\' work without attribution', 'Citing sources correctly', 'Paraphrasing properly'], answer: "Copying others' work without attribution", visual: '📰' },
        { prompt: 'Vocabulary choice in a formal essay should be?', options: ['Slang', 'Formal and precise', 'Conversational', 'Simple/basic'], answer: 'Formal and precise', visual: '📰' },
        { prompt: 'A paragraph should have how many main ideas?', options: ['As many as possible', 'One focused idea', 'Two or three', 'None'], answer: 'One focused idea', visual: '📰' },
        { prompt: 'Passive voice is typically?', options: ['Preferred in formal writing', 'Avoided in most written essays', 'Always correct', 'Always wrong'], answer: 'Avoided in most written essays', visual: '📰' },
        { prompt: 'Which shows the strongest evidence integration?', options: ['Evidence says: "X" (Smith, 2020), which proves...', 'X.', 'Smith says something.', 'Evidence is everywhere.'], answer: 'Evidence says: "X" (Smith, 2020), which proves...', visual: '📰' },
        { prompt: 'An analytical essay primarily?', options: ['Tells a story', 'Analyses and interprets a topic', 'Lists facts only', 'Writes instructions'], answer: 'Analyses and interprets a topic', visual: '📰' },
        { prompt: 'The body of an essay should contain?', options: ['Introduction only', 'Only conclusions', 'Detailed arguments with evidence', 'Personal anecdotes only'], answer: 'Detailed arguments with evidence', visual: '📰' },
        { prompt: 'Which word signals an example?', options: ['Therefore', 'However', 'For instance', 'Consequently'], answer: 'For instance', visual: '📰' },
        { prompt: 'A critical essay should?', options: ['Avoid opinions', 'Only praise the subject', 'Evaluate strengths and weaknesses', 'Summarise without judgment'], answer: 'Evaluate strengths and weaknesses', visual: '📰' },
        { prompt: 'The best length for a topic sentence?', options: ['One very long, detailed sentence', 'One clear, concise sentence', 'Two to three sentences', 'Half a paragraph'], answer: 'One clear, concise sentence', visual: '📰' },
        { prompt: 'Proofreading means?', options: ['Writing the first draft', 'Reviewing for errors before submission', 'Planning the essay', 'Researching the topic'], answer: 'Reviewing for errors before submission', visual: '📰' },
        { prompt: 'An argumentative essay requires?', options: ['Only descriptions', 'A clear claim + supporting evidence', 'Only questions', 'A story'], answer: 'A clear claim + supporting evidence', visual: '📰' },
        { prompt: 'Which transition word signals opposition best?', options: ['Additionally', 'Similarly', 'Notwithstanding', 'As a result'], answer: 'Notwithstanding', visual: '📰' },
        { prompt: 'Sentence variety improves?', options: ['Speed of writing', 'Readability and flow', 'Length of essay', 'Number of arguments'], answer: 'Readability and flow', visual: '📰' },
        { prompt: 'Outlining before writing helps with?', options: ['Grammar', 'Structure and logical flow', 'Vocabulary', 'Avoiding plagiarism'], answer: 'Structure and logical flow', visual: '📰' },
    ],

    PARTS_OF_SPEECH_DUEL: [
        { prompt: '"Beautiful" is which part of speech?', options: ['Noun', 'Verb', 'Adjective', 'Adverb'], answer: 'Adjective', visual: '🎭' },
        { prompt: '"Quickly" is?', options: ['Adjective', 'Adverb', 'Noun', 'Verb'], answer: 'Adverb', visual: '🎭' },
        { prompt: '"Happiness" is?', options: ['Verb', 'Adjective', 'Noun', 'Preposition'], answer: 'Noun', visual: '🎭' },
        { prompt: '"Because" is a?', options: ['Noun', 'Conjunction', 'Preposition', 'Adverb'], answer: 'Conjunction', visual: '🎭' },
        { prompt: '"She" is a?', options: ['Noun', 'Adjective', 'Pronoun', 'Verb'], answer: 'Pronoun', visual: '🎭' },
        { prompt: '"In" is a?', options: ['Conjunction', 'Adverb', 'Preposition', 'Noun'], answer: 'Preposition', visual: '🎭' },
        { prompt: '"Wow!" is an?', options: ['Adjective', 'Interjection', 'Noun', 'Adverb'], answer: 'Interjection', visual: '🎭' },
        { prompt: '"Ate" is?', options: ['Noun', 'Adjective', 'Verb', 'Adverb'], answer: 'Verb', visual: '🎭' },
        { prompt: '"The" is?', options: ['Pronoun', 'Article (Determiner)', 'Adjective', 'Noun'], answer: 'Article (Determiner)', visual: '🎭' },
        { prompt: '"Both… and…" is a?', options: ['Subordinating conjunction', 'Correlative conjunction', 'Preposition', 'Noun phrase'], answer: 'Correlative conjunction', visual: '🎭' },
        { prompt: 'An abstract noun is a noun that is?', options: ['Physical/tangible', 'An idea or feeling', 'A place', 'A person'], answer: 'An idea or feeling', visual: '🎭' },
        { prompt: '"Children" is plural of?', options: ['Childs', 'Childen', 'Child', 'Childrens'], answer: 'Child', visual: '🎭' },
        { prompt: 'A transitive verb?', options: ['Needs no object', 'Requires a direct object', 'Is always past tense', 'Is always present'], answer: 'Requires a direct object', visual: '🎭' },
        { prompt: '"Carefully" modifies which word in "She carefully opened the box"?', options: ['She', 'box', 'opened', 'the'], answer: 'opened', visual: '🎭' },
        { prompt: '"Either…or…" is a?', options: ['Coordinating conjunction', 'Correlative conjunction', 'Subordinating conjunction', 'Preposition'], answer: 'Correlative conjunction', visual: '🎭' },
        { prompt: 'A collective noun refers to?', options: ['One person', 'A group treated as a unit', 'An abstract idea', 'A verb'], answer: 'A group treated as a unit', visual: '🎭' },
        { prompt: '"Himself" is a?', options: ['Personal pronoun', 'Possessive pronoun', 'Reflexive pronoun', 'Relative pronoun'], answer: 'Reflexive pronoun', visual: '🎭' },
        { prompt: 'Which is a proper noun?', options: ['city', 'river', 'London', 'country'], answer: 'London', visual: '🎭' },
        { prompt: 'Auxiliary verb in "She has eaten": ?', options: ['She', 'has', 'eaten', 'all'], answer: 'has', visual: '🎭' },
        { prompt: '"Loudly" — comparing: "loud, louder, ___"?', options: ['more loud', 'most loudly', 'loudest', 'more louder'], answer: 'loudest', visual: '🎭' },
        { prompt: '"Among" vs "between": "between" is used for?', options: ['3 or more', '2 things', 'groups', 'any number'], answer: '2 things', visual: '🎭' },
        { prompt: 'A gerund is a verb used as a?', options: ['Adjective', 'Adverb', 'Noun', 'Interjection'], answer: 'Noun', visual: '🎭' },
        { prompt: '"Swimming is fun." "Swimming" here is a?', options: ['Verb', 'Gerund (noun)', 'Adjective', 'Adverb'], answer: 'Gerund (noun)', visual: '🎭' },
        { prompt: 'Superlative adjective of "good"?', options: ['Better', 'Gooder', 'Best', 'Most good'], answer: 'Best', visual: '🎭' },
        { prompt: 'Which is an indefinite pronoun?', options: ['he', 'they', 'everyone', 'we'], answer: 'everyone', visual: '🎭' },
        { prompt: '"Although" is a?', options: ['Coordinating conjunction', 'Subordinating conjunction', 'Preposition', 'Adverb'], answer: 'Subordinating conjunction', visual: '🎭' },
        { prompt: 'An infinitive is "to +" what?', options: ['noun', 'adjective', 'base verb', 'adverb'], answer: 'base verb', visual: '🎭' },
        { prompt: '"Their" is which type of pronoun?', options: ['Reflexive', 'Possessive', 'Relative', 'Personal'], answer: 'Possessive', visual: '🎭' },
        { prompt: 'Comparative of "bad"?', options: ['more bad', 'badder', 'worse', 'worst'], answer: 'worse', visual: '🎭' },
        { prompt: 'Which sentence has an appositive?', options: ['She runs fast.', 'Tom, my brother, plays guitar.', 'I ate lunch.', 'He left quickly.'], answer: 'Tom, my brother, plays guitar.', visual: '🎭' },
    ],
}
