import { Question } from '../question-banks'

export const SOCIAL_BANKS: Record<string, Question[]> = {

    CIVILIZATION_BUILDER: [
        { prompt: 'The first civilization emerged in?', options: ['Egypt', 'Mesopotamia (Tigris-Euphrates)', 'India', 'China'], answer: 'Mesopotamia (Tigris-Euphrates)', visual: '🏛️' },
        { prompt: 'The ancient writing system of Mesopotamia was called?', options: ['Hieroglyphics', 'Cuneiform', 'Sanskrit', 'Oracle bone script'], answer: 'Cuneiform', visual: '🏛️' },
        { prompt: 'The Nile River was central to which ancient civilisation?', options: ['Roman', 'Greek', 'Egyptian', 'Persian'], answer: 'Egyptian', visual: '🏛️' },
        { prompt: 'The Great Wall of China was mainly built to?', options: ['Trade with neighbours', 'Protect from northern invaders', 'Divert rivers', 'Mark borders peacefully'], answer: 'Protect from northern invaders', visual: '🏛️' },
        { prompt: 'The Indus Valley Civilisation was famous for?', options: ['Pyramids', 'Advanced urban planning & sanitation', 'Writing philosophy', 'Maritime trade only'], answer: 'Advanced urban planning & sanitation', visual: '🏛️' },
        { prompt: 'Which ancient wonder was in Egypt?', options: ['Hanging Gardens', 'Colossus of Rhodes', 'Great Pyramid of Giza', 'Lighthouse of Alexandria'], answer: 'Great Pyramid of Giza', visual: '🏛️' },
        { prompt: 'Greek democracy originated in?', options: ['Sparta', 'Troy', 'Athens', 'Olympia'], answer: 'Athens', visual: '🏛️' },
        { prompt: 'The Roman Republic became an Empire under?', options: ['Julius Caesar', 'Augustus Caesar', 'Cicero', 'Brutus'], answer: 'Augustus Caesar', visual: '🏛️' },
        { prompt: 'The Silk Road connected China with?', options: ['Africa', 'Americas', 'Rome/Mediterranean', 'Australia'], answer: 'Rome/Mediterranean', visual: '🏛️' },
        { prompt: 'The Maurya Empire\'s most famous ruler was?', options: ['Akbar', 'Ashoka', 'Chandragupta', 'Vikramaditya'], answer: 'Ashoka', visual: '🏛️' },
        { prompt: 'Pharaohs in ancient Egypt were considered?', options: ['Elected leaders', 'God-kings', 'Military generals only', 'Priests only'], answer: 'God-kings', visual: '🏛️' },
        { prompt: 'The Olympic Games started in ancient?', options: ['Rome', 'Egypt', 'Greece', 'Persia'], answer: 'Greece', visual: '🏛️' },
        { prompt: 'Confucianism originated in?', options: ['India', 'Japan', 'China', 'Korea'], answer: 'China', visual: '🏛️' },
        { prompt: 'The Aztec Empire was located in modern-day?', options: ['Peru', 'Mexico', 'Brazil', 'Colombia'], answer: 'Mexico', visual: '🏛️' },
        { prompt: 'The Maya civilisation excelled at?', options: ['Iron smelting', 'Mathematics, astronomy & calendar', 'Maritime navigation only', 'Building aqueducts'], answer: 'Mathematics, astronomy & calendar', visual: '🏛️' },
        { prompt: 'Which empire was known as "the empire on which the sun never sets"?', options: ['Roman', 'Mongol', 'British', 'Ottoman'], answer: 'British', visual: '🏛️' },
        { prompt: 'The printing press was invented by?', options: ['Thomas Edison', 'Johannes Gutenberg', 'Leonardo da Vinci', 'Archimedes'], answer: 'Johannes Gutenberg', visual: '🏛️' },
        { prompt: 'The Renaissance began in?', options: ['France', 'England', 'Italy', 'Germany'], answer: 'Italy', visual: '🏛️' },
        { prompt: 'Feudalism was a system where?', options: ['Merchants ruled', 'Land was exchanged for military service', 'Kings elected by people', 'Priests held all power'], answer: 'Land was exchanged for military service', visual: '🏛️' },
        { prompt: 'The Black Death (14th century) was a?', options: ['War', 'Volcanic eruption', 'Bubonic plague pandemic', 'Flood'], answer: 'Bubonic plague pandemic', visual: '🏛️' },
    ],

    DEMOCRACY_DEBATE: [
        { prompt: 'Democracy means?', options: ['Rule by the king', 'Rule by the people', 'Rule by the military', 'Rule by the church'], answer: 'Rule by the people', visual: '🗳️' },
        { prompt: 'The Indian Constitution came into effect on?', options: ['15 August 1947', '26 January 1950', '26 November 1949', '2 October 1950'], answer: '26 January 1950', visual: '🗳️' },
        { prompt: 'Universal adult franchise means?', options: ['Only educated can vote', 'Every adult citizen can vote', 'Only property owners vote', 'Voting for men only'], answer: 'Every adult citizen can vote', visual: '🗳️' },
        { prompt: 'The Preamble of the Indian Constitution begins with?', options: ['We the People of India', 'In the name of God', 'By order of Parliament', 'India is a nation'], answer: 'We the People of India', visual: '🗳️' },
        { prompt: 'A constitutional monarchy has a?', options: ['King with unlimited power', 'King with limited power under constitution', 'No king', 'Only elected rulers'], answer: 'King with limited power under constitution', visual: '🗳️' },
        { prompt: 'The three branches of government are?', options: ['President, PM, Governor', 'Executive, Legislative, Judicial', 'Army, Navy, Air Force', 'State, District, Village'], answer: 'Executive, Legislative, Judicial', visual: '🗳️' },
        { prompt: 'Freedom of speech is a?', options: ['Directive principle', 'Fundamental right', 'Fundamental duty', 'State policy'], answer: 'Fundamental right', visual: '🗳️' },
        { prompt: 'A bill becomes law when?', options: ['PM approves it', 'Parliament passes + President assents', 'Judiciary reviews it', 'People vote for it'], answer: 'Parliament passes + President assents', visual: '🗳️' },
        { prompt: 'Which is the highest law of the land in India?', options: ['Penal Code', 'Constitution', 'Civil Code', 'Supreme Court order'], answer: 'Constitution', visual: '🗳️' },
        { prompt: 'The idea of checks and balances means?', options: ['Banks check accounts', 'Each branch limits the others\' power', 'Citizens check government spending', 'Police maintain law'], answer: "Each branch limits the others' power", visual: '🗳️' },
        { prompt: 'Federalism means power is shared between?', options: ['Two political parties', 'Central and state governments', 'Army and police', 'President and PM'], answer: 'Central and state governments', visual: '🗳️' },
        { prompt: 'Which article abolished untouchability?', options: ['Article 13', 'Article 17', 'Article 21', 'Article 9'], answer: 'Article 17', visual: '🗳️' },
        { prompt: 'Right to Education (RTE) applies to children aged?', options: ['5-15 years', '6-14 years', '4-16 years', '5-18 years'], answer: '6-14 years', visual: '🗳️' },
        { prompt: 'Lok Sabha has how many seats?', options: ['245', '250', '543', '552'], answer: '543', visual: '🗳️' },
        { prompt: 'The President of India is elected by?', options: ['Direct popular vote', 'Elected members of Parliament + state legislatures', 'Rajya Sabha only', 'Lok Sabha only'], answer: 'Elected members of Parliament + state legislatures', visual: '🗳️' },
        { prompt: 'Judicial review means?', options: ['Judges review their own decisions', 'Courts can examine constitutionality of laws', 'Citizens review judges', 'Parliament reviews court orders'], answer: 'Courts can examine constitutionality of laws', visual: '🗳️' },
        { prompt: 'A referendum is when?', options: ['Parliament debates a bill', 'Citizens vote directly on an issue', 'President appoints ministers', 'Courts rule on a case'], answer: 'Citizens vote directly on an issue', visual: '🗳️' },
        { prompt: 'Secularism means?', options: ['Government follows one religion', 'No state religion; all religions equal', 'Religion is banned', 'Only majority religion is recognised'], answer: 'No state religion; all religions equal', visual: '🗳️' },
        { prompt: 'Which is a Fundamental Duty in India?', options: ['Free education', 'Right to vote', 'To protect the environment', 'Right to property'], answer: 'To protect the environment', visual: '🗳️' },
        { prompt: 'Local self-government at village level is called?', options: ['Zila Parishad', 'Panchayati Raj', 'Tehsil', 'Nagar Panchayat'], answer: 'Panchayati Raj', visual: '🗳️' },
    ],

    EMPIRE_FALL: [
        { prompt: 'The Roman Empire fell in the West in?', options: ['410 AD', '455 AD', '476 AD', '500 AD'], answer: '476 AD', visual: '🏰' },
        { prompt: 'The primary cause of Rome\'s fall was?', options: ['Single cause', 'Multiple factors: invasions, economic trouble, corruption', 'Disease alone', 'Natural disaster'], answer: 'Multiple factors: invasions, economic trouble, corruption', visual: '🏰' },
        { prompt: 'The Mongol Empire was the largest contiguous empire in history under?', options: ['Genghis Khan', 'Kublai Khan', 'Tamerlane', 'Attila'], answer: 'Genghis Khan', visual: '🏰' },
        { prompt: 'The Ottoman Empire ended in?', options: ['1900', '1918', '1922', '1923'], answer: '1922', visual: '🏰' },
        { prompt: 'The British East India Company took control of India after?', options: ['Battle of Plassey 1757', 'Battle of Panipat 1526', 'Sepoy Mutiny 1857', 'Treaty of Versailles'], answer: 'Battle of Plassey 1757', visual: '🏰' },
        { prompt: 'The Mughal Empire was founded by?', options: ['Akbar', 'Babur', 'Humayun', 'Shah Jahan'], answer: 'Babur', visual: '🏰' },
        { prompt: 'The fall of Constantinople (1453) ended the?', options: ['Roman Empire', 'Byzantine Empire', 'Ottoman Empire', 'Holy Roman Empire'], answer: 'Byzantine Empire', visual: '🏰' },
        { prompt: 'Alexander the Great\'s empire stretched from Greece to?', options: ['China', 'India (modern Pakistan)', 'Arabia', 'Africa'], answer: 'India (modern Pakistan)', visual: '🏰' },
        { prompt: 'The Han Dynasty of China fell due to?', options: ['Mongol invasion', 'Internal rebellions and landowner power', 'Roman attack', 'Tsunami'], answer: 'Internal rebellions and landowner power', visual: '🏰' },
        { prompt: 'The Gupta Empire is known as India\'s?', options: ['Dark Age', 'Golden Age', 'Iron Age', 'British Age'], answer: 'Golden Age', visual: '🏰' },
        { prompt: 'Which battle ended Napoleon\'s rule?', options: ['Battle of Trafalgar', 'Battle of Waterloo', 'Battle of Leipzig', 'Siege of Paris'], answer: 'Battle of Waterloo', visual: '🏰' },
        { prompt: 'The Soviet Union dissolved in?', options: ['1989', '1990', '1991', '1992'], answer: '1991', visual: '🏰' },
        { prompt: 'Decolonisation in Africa was mostly complete by?', options: ['1940s', '1950s', '1960s', '1970s'], answer: '1960s', visual: '🏰' },
        { prompt: 'WWI ended with the Treaty of?', options: ['Paris', 'Versailles', 'Vienna', 'Utrecht'], answer: 'Versailles', visual: '🏰' },
        { prompt: 'The Cold War was mainly between?', options: ['UK and France', 'USA and China', 'USA and USSR', 'Germany and Japan'], answer: 'USA and USSR', visual: '🏰' },
    ],

    TRADE_ROUTE_TYCOON: [
        { prompt: 'GDP stands for?', options: ['General Domestic Product', 'Gross Domestic Product', 'Government Deficit Policy', 'Global Development Plan'], answer: 'Gross Domestic Product', visual: '🌍' },
        { prompt: 'Supply and demand: when supply increases and demand stays constant, price?', options: ['Rises', 'Falls', 'Stays same', 'Doubles'], answer: 'Falls', visual: '🌍' },
        { prompt: 'Inflation means?', options: ['Decrease in prices', 'Increase in general price levels', 'More goods available', 'Lower wages'], answer: 'Increase in general price levels', visual: '🌍' },
        { prompt: 'Comparative advantage means?', options: ['Producing everything cheaply', 'Producing at lower opportunity cost than others', 'Having the most resources', 'Being the largest economy'], answer: 'Producing at lower opportunity cost than others', visual: '🌍' },
        { prompt: 'A trade deficit occurs when?', options: ['Exports > Imports', 'Imports > Exports', 'Exports = Imports', 'Government borrows money'], answer: 'Imports > Exports', visual: '🌍' },
        { prompt: 'Barter is?', options: ['Trading with money', 'Exchanging goods directly', 'Borrowing money', 'Investing in stocks'], answer: 'Exchanging goods directly', visual: '🌍' },
        { prompt: 'Tariff is a?', options: ['Tax on imports', 'Tax on exports', 'Subsidy to farmers', 'Trade ban'], answer: 'Tax on imports', visual: '🌍' },
        { prompt: 'WTO stands for?', options: ['World Trade Organisation', 'World Tourism Office', 'World Transport Order', 'Western Trade Organisation'], answer: 'World Trade Organisation', visual: '🌍' },
        { prompt: 'Opportunity cost is?', options: ['The money cost of a choice', 'The value of the next-best forgone alternative', 'The profit from an activity', 'The total cost of production'], answer: 'The value of the next-best forgone alternative', visual: '🌍' },
        { prompt: 'An embargo is?', options: ['A tax on goods', 'A complete ban on trade with a country', 'A shipping container', 'A trade agreement'], answer: 'A complete ban on trade with a country', visual: '🌍' },
        { prompt: 'Foreign exchange rate is?', options: ['Interest rate on loans', 'Value of one currency in another', 'Stock market index', 'GDP of two countries'], answer: 'Value of one currency in another', visual: '🌍' },
        { prompt: 'Free trade means?', options: ['Goods are given free', 'Trade without tariffs or quotas', 'Only domestic trade', 'Trading only between rich nations'], answer: 'Trade without tariffs or quotas', visual: '🌍' },
        { prompt: 'The law of diminishing returns states that?', options: ['More inputs always mean more output', 'Beyond a point, adding inputs reduces per-unit output', 'Prices always rise', 'All goods have elastic demand'], answer: 'Beyond a point, adding inputs reduces per-unit output', visual: '🌍' },
        { prompt: 'BRICS countries include?', options: ['Brazil, Russia, India, China, South Africa', 'Britain, Russia, Italy, Canada, Spain', 'Brazil, Romania, Indonesia, China, Switzerland', 'None of these'], answer: 'Brazil, Russia, India, China, South Africa', visual: '🌍' },
        { prompt: 'Which market has only one seller?', options: ['Oligopoly', 'Monopoly', 'Perfect competition', 'Duopoly'], answer: 'Monopoly', visual: '🌍' },
    ],
}

export const CS_BANKS: Record<string, Question[]> = {

    CYBER_SHIELD: [
        { prompt: 'Phishing is?', options: ['Catching fish online', 'Fraudulent emails/sites that steal credentials', 'A virus type', 'Network hacking tool'], answer: 'Fraudulent emails/sites that steal credentials', visual: '🔐' },
        { prompt: 'A strong password should include?', options: ['Only letters', 'Only numbers', 'Uppercase, lowercase, numbers, symbols', 'Your name and birthday'], answer: 'Uppercase, lowercase, numbers, symbols', visual: '🔐' },
        { prompt: 'Two-factor authentication (2FA) adds?', options: ['A second password layer', 'A second device', 'Biometric scan only', 'Email only'], answer: 'A second password layer', visual: '🔐' },
        { prompt: 'HTTPS means the website?', options: ['Has a homepage', 'Is encrypted and secure', 'Is government-owned', 'Has no viruses'], answer: 'Is encrypted and secure', visual: '🔐' },
        { prompt: 'Malware is?', options: ['Useful software', 'Software designed to harm systems', 'Hardware virus', 'Network cable damage'], answer: 'Software designed to harm systems', visual: '🔐' },
        { prompt: 'A firewall?', options: ['Prevents fire in data centres', 'Monitors and controls network traffic', 'Encrypts data', 'Stores passwords'], answer: 'Monitors and controls network traffic', visual: '🔐' },
        { prompt: 'Ransomware?', options: ['Allows remote access', 'Encrypts your files and demands payment', 'Slows your computer', 'Sends spam emails'], answer: 'Encrypts your files and demands payment', visual: '🔐' },
        { prompt: 'The best way to protect against phishing?', options: ['Use antivirus', 'Verify the sender and avoid suspicious links', 'Use a VPN only', 'Change password monthly'], answer: 'Verify the sender and avoid suspicious links', visual: '🔐' },
        { prompt: 'Social engineering attacks target?', options: ['Software vulnerabilities', 'Human psychology to manipulate', 'Physical hardware', 'Network hardware'], answer: 'Human psychology to manipulate', visual: '🔐' },
        { prompt: 'VPN stands for?', options: ['Very Private Network', 'Virtual Private Network', 'Verified Personal Network', 'Virtual Protocol Node'], answer: 'Virtual Private Network', visual: '🔐' },
        { prompt: 'The purpose of encryption is to?', options: ['Delete data', 'Make data unreadable without a key', 'Speed up data transfer', 'Compress files'], answer: 'Make data unreadable without a key', visual: '🔐' },
        { prompt: 'Zero-day vulnerability means?', options: ['Software with no bugs', 'An unknown flaw not yet patched by developers', 'Old software', 'Daily update'], answer: 'An unknown flaw not yet patched by developers', visual: '🔐' },
        { prompt: 'DDoS attack means?', options: ['Distributed Denial of Service — overwhelming a server', 'Data Destruction over Systems', 'Direct Digital Obstruction Server', 'None of these'], answer: 'Distributed Denial of Service — overwhelming a server', visual: '🔐' },
        { prompt: 'Which is safest for public Wi-Fi?', options: ['Use HTTP sites', 'Share passwords over WhatsApp', 'Use a VPN', 'Browse without protection'], answer: 'Use a VPN', visual: '🔐' },
        { prompt: 'Biometric authentication uses?', options: ['Passwords', 'Physical characteristics like fingerprint or face', 'Security questions', 'PIN codes only'], answer: 'Physical characteristics like fingerprint or face', visual: '🔐' },
    ],

    LOGIC_GATE_GARDEN: [
        { prompt: 'AND gate output is 1 only when?', options: ['Any input is 1', 'Both inputs are 1', 'Neither input is 1', 'One input is 0'], answer: 'Both inputs are 1', visual: '🧮' },
        { prompt: 'OR gate output is 1 when?', options: ['Both are 0', 'Both are 1 only', 'At least one input is 1', 'All inputs are 0'], answer: 'At least one input is 1', visual: '🧮' },
        { prompt: 'NOT gate (inverter) with input 0 gives?', options: ['0', '1', 'Undefined', 'Both 0 and 1'], answer: '1', visual: '🧮' },
        { prompt: 'NAND gate is?', options: ['NOT of AND', 'NOT of OR', 'AND + NOT', 'OR + AND'], answer: 'NOT of AND', visual: '🧮' },
        { prompt: 'NOR gate is?', options: ['NOT of AND', 'NOT of OR', 'OR + AND', 'AND + NOR'], answer: 'NOT of OR', visual: '🧮' },
        { prompt: 'XOR gate output is 1 when?', options: ['Both inputs same', 'Inputs are different', 'Both are 0', 'Both are 1'], answer: 'Inputs are different', visual: '🧮' },
        { prompt: 'Truth table for AND: 1 AND 0 = ?', options: ['0', '1', 'Undefined', '2'], answer: '0', visual: '🧮' },
        { prompt: 'Truth table for OR: 0 OR 0 = ?', options: ['0', '1', 'Undefined', '2'], answer: '0', visual: '🧮' },
        { prompt: 'XNOR gate output is 1 when?', options: ['Inputs are different', 'Inputs are the same', 'One input is 0', 'Both inputs are 0'], answer: 'Inputs are the same', visual: '🧮' },
        { prompt: 'Which gate is called "universal gate"?', options: ['AND', 'OR', 'NOT', 'NAND'], answer: 'NAND', visual: '🧮' },
        { prompt: 'De Morgan\'s theorem: NOT(A AND B) = ?', options: ['NOT A AND NOT B', 'NOT A OR NOT B', 'A OR B', 'NOT A AND B'], answer: 'NOT A OR NOT B', visual: '🧮' },
        { prompt: 'A half adder performs?', options: ['Addition of 3 bits', 'Binary addition of 2 single bits', 'Subtraction', 'Multiplication'], answer: 'Binary addition of 2 single bits', visual: '🧮' },
        { prompt: 'Boolean algebra simplification: A + A = ?', options: ['2A', 'A', 'A²', '0'], answer: 'A', visual: '🧮' },
        { prompt: 'A + 0 = ? (Boolean)', options: ['0', '1', 'A', 'Not defined'], answer: 'A', visual: '🧮' },
        { prompt: 'A · 1 = ? (Boolean)', options: ['0', '1', 'A', 'Not defined'], answer: 'A', visual: '🧮' },
    ],

    AI_TRAINING_GROUND: [
        { prompt: 'Machine learning is?', options: ['Programming rules manually', 'Systems that learn from data', 'Hardware design', 'Network routing'], answer: 'Systems that learn from data', visual: '🧠' },
        { prompt: 'Supervised learning uses?', options: ['Unlabelled data', 'Labelled training data with correct answers', 'No data', 'Random data'], answer: 'Labelled training data with correct answers', visual: '🧠' },
        { prompt: 'Unsupervised learning finds?', options: ['Known patterns', 'Hidden patterns in unlabelled data', 'Predefined answers', 'Random solutions'], answer: 'Hidden patterns in unlabelled data', visual: '🧠' },
        { prompt: 'A neural network is inspired by?', options: ['Computer chips', 'Human brain neurons', 'Solar panels', 'DNA'], answer: 'Human brain neurons', visual: '🧠' },
        { prompt: 'Overfitting means?', options: ['Model is too simple', 'Model performs well on training but poorly on new data', 'Model learns nothing', 'Data is too large'], answer: 'Model performs well on training but poorly on new data', visual: '🧠' },
        { prompt: 'Training data is used to?', options: ['Test the model', 'Teach the model patterns', 'Validate model fairly', 'Deploy the model'], answer: 'Teach the model patterns', visual: '🧠' },
        { prompt: 'Which is a classification task?', options: ['Predicting house price', 'Grouping similar items', 'Detecting spam/not spam', 'Finding patterns in music'], answer: 'Detecting spam/not spam', visual: '🧠' },
        { prompt: 'Reinforcement learning learns through?', options: ['Labelled data', 'Trial and error with rewards/punishments', 'Text descriptions', 'Human feedback only'], answer: 'Trial and error with rewards/punishments', visual: '🧠' },
        { prompt: 'What is bias in ML models?', options: ['Hardware error', 'Systematic unfairness in predictions due to skewed data', 'Random noise', 'Overfitting only'], answer: 'Systematic unfairness in predictions due to skewed data', visual: '🧠' },
        { prompt: 'Deep learning uses?', options: ['Shallow networks', 'Deep neural networks with many layers', 'Only linear models', 'No neural networks'], answer: 'Deep neural networks with many layers', visual: '🧠' },
        { prompt: 'Natural Language Processing (NLP) handles?', options: ['Images', 'Human language understanding by machines', 'Hardware signals', 'Mathematical equations'], answer: 'Human language understanding by machines', visual: '🧠' },
        { prompt: 'Which algorithm classifies data into K groups?', options: ['Linear regression', 'K-Means clustering', 'Decision tree', 'SVM'], answer: 'K-Means clustering', visual: '🧠' },
        { prompt: 'The test set in ML is used to?', options: ['Train the model', 'Tune hyperparameters', 'Evaluate final model performance', 'Generate data'], answer: 'Evaluate final model performance', visual: '🧠' },
        { prompt: 'Which is a regression task?', options: ['Detecting faces', 'Classifying emails', 'Predicting tomorrow\'s temperature', 'Grouping similar documents'], answer: "Predicting tomorrow's temperature", visual: '🧠' },
        { prompt: 'Transfer learning means?', options: ['Copying data', 'Using a pre-trained model on a new task', 'Moving models to cloud', 'Teaching students'], answer: 'Using a pre-trained model on a new task', visual: '🧠' },
    ],

    ENCRYPTION_ESCAPE: [
        { prompt: 'Caesar cipher shifts each letter by?', options: ['Random amount', 'A fixed number', 'Its ASCII value', 'Its position squared'], answer: 'A fixed number', visual: '🔐' },
        { prompt: 'Symmetric encryption uses?', options: ['Two different keys', 'Same key for encryption and decryption', 'No keys', 'Public key only'], answer: 'Same key for encryption and decryption', visual: '🔐' },
        { prompt: 'RSA is an example of?', options: ['Symmetric encryption', 'Asymmetric (public-key) encryption', 'Hash function', 'Compression'], answer: 'Asymmetric (public-key) encryption', visual: '🔐' },
        { prompt: 'A hash function is?', options: ['Reversible encryption', 'One-way function producing fixed-size output', 'A type of key', 'A compression algorithm'], answer: 'One-way function producing fixed-size output', visual: '🔐' },
        { prompt: 'The public key is?', options: ['Secret', 'Shared freely with anyone', 'Only for encryption', 'Only for decryption'], answer: 'Shared freely with anyone', visual: '🔐' },
        { prompt: 'The private key should be?', options: ['Shared with trusted friends', 'Known only to the owner', 'Posted publicly', 'Same as public key'], answer: 'Known only to the owner', visual: '🔐' },
        { prompt: 'MD5 and SHA-256 are types of?', options: ['Encryption algorithms', 'Hash functions', 'Symmetric keys', 'Compression formats'], answer: 'Hash functions', visual: '🔐' },
        { prompt: 'Caesar cipher with shift of 3: "A" becomes?', options: ['B', 'C', 'D', 'E'], answer: 'D', visual: '🔐' },
        { prompt: 'SSL/TLS protects?', options: ['Local files', 'Data in transit (HTTPS)', 'Hard drives', 'Local network only'], answer: 'Data in transit (HTTPS)', visual: '🔐' },
        { prompt: 'Digital signature verifies?', options: ['Password strength', 'Message authenticity and sender identity', 'Encryption method', 'Network speed'], answer: 'Message authenticity and sender identity', visual: '🔐' },
        { prompt: 'Brute force attack tries?', options: ['Social engineering', 'All possible key combinations', 'Single known key', 'Physical access'], answer: 'All possible key combinations', visual: '🔐' },
        { prompt: 'Which is more secure?', options: ['Short key (56-bit)', 'Long key (256-bit)', 'No encryption', 'Simple Caesar cipher'], answer: 'Long key (256-bit)', visual: '🔐' },
        { prompt: 'End-to-end encryption means?', options: ['Only sender encrypts', 'Only receiver decrypts', 'Only sender and receiver can read the message', 'Server can read messages'], answer: 'Only sender and receiver can read the message', visual: '🔐' },
        { prompt: 'Steganography is?', options: ['Strong encryption', 'Hiding a message within another file (e.g., image)', 'Hash function', 'Public-key system'], answer: 'Hiding a message within another file (e.g., image)', visual: '🔐' },
        { prompt: 'One-time pad is?', options: ['A weak cipher', 'Theoretically unbreakable if used correctly', 'Symmetric encryption', 'A type of hash'], answer: 'Theoretically unbreakable if used correctly', visual: '🔐' },
    ],
}

export const GK_BANKS: Record<string, Question[]> = {

    INVENTORS_WORKSHOP: [
        { prompt: 'Who invented the telephone?', options: ['Thomas Edison', 'Alexander Graham Bell', 'Nikola Tesla', 'Guglielmo Marconi'], answer: 'Alexander Graham Bell', visual: '🌟' },
        { prompt: 'Who invented the light bulb (practical version)?', options: ['Nikola Tesla', 'Benjamin Franklin', 'Thomas Edison', 'James Watt'], answer: 'Thomas Edison', visual: '🌟' },
        { prompt: 'Who invented the World Wide Web?', options: ['Bill Gates', 'Tim Berners-Lee', 'Steve Jobs', 'Jack Dorsey'], answer: 'Tim Berners-Lee', visual: '🌟' },
        { prompt: 'The steam engine was improved by?', options: ['James Watt', 'Thomas Newcomen', 'George Stephenson', 'Isambard Brunel'], answer: 'James Watt', visual: '🌟' },
        { prompt: 'Who invented the aeroplane?', options: ['Charles Lindbergh', 'Howard Hughes', 'Wright Brothers', 'Alberto Santos-Dumont'], answer: 'Wright Brothers', visual: '🌟' },
        { prompt: 'Penicillin was discovered by?', options: ['Louis Pasteur', 'Marie Curie', 'Alexander Fleming', 'Edward Jenner'], answer: 'Alexander Fleming', visual: '🌟' },
        { prompt: 'Who invented the printing press?', options: ['Galileo', 'Johannes Gutenberg', 'Isaac Newton', 'Leonardo da Vinci'], answer: 'Johannes Gutenberg', visual: '🌟' },
        { prompt: 'The theory of relativity was proposed by?', options: ['Niels Bohr', 'Max Planck', 'Albert Einstein', 'Werner Heisenberg'], answer: 'Albert Einstein', visual: '🌟' },
        { prompt: 'Who invented the radio?', options: ['Thomas Edison', 'Alexander Graham Bell', 'Guglielmo Marconi', 'Nikola Tesla'], answer: 'Guglielmo Marconi', visual: '🌟' },
        { prompt: 'DNA double helix structure was discovered by?', options: ['Mendel & Darwin', 'Watson, Crick & Franklin', 'Pasteur & Koch', 'Curie & Bohr'], answer: 'Watson, Crick & Franklin', visual: '🌟' },
        { prompt: 'Isaac Newton discovered?', options: ['Theory of relativity', 'Laws of motion & gravity', 'Electromagnetic waves', 'Radioactivity'], answer: 'Laws of motion & gravity', visual: '🌟' },
        { prompt: 'Who invented the computer?', options: ['Alan Turing', 'Charles Babbage (mechanical)', 'Steve Wozniak', 'Bill Gates'], answer: 'Charles Babbage (mechanical)', visual: '🌟' },
        { prompt: 'Marie Curie was first to discover?', options: ['X-rays', 'Radioactivity', 'Penicillin', 'DNA'], answer: 'Radioactivity', visual: '🌟' },
        { prompt: 'Who invented the telescope?', options: ['Galileo Galilei', 'Isaac Newton', 'Hans Lippershey', 'Copernicus'], answer: 'Hans Lippershey', visual: '🌟' },
        { prompt: 'Vaccination was pioneered by?', options: ['Louis Pasteur', 'Edward Jenner', 'Alexander Fleming', 'Joseph Lister'], answer: 'Edward Jenner', visual: '🌟' },
        { prompt: 'The electric battery was invented by?', options: ['Michael Faraday', 'Alessandro Volta', 'Thomas Edison', 'Nikola Tesla'], answer: 'Alessandro Volta', visual: '🌟' },
        { prompt: 'Who proposed the heliocentric model?', options: ['Aristotle', 'Ptolemy', 'Copernicus', 'Galileo'], answer: 'Copernicus', visual: '🌟' },
        { prompt: 'C language was created by?', options: ['Dennis Ritchie', 'Bjarne Stroustrup', 'Guido van Rossum', 'Linus Torvalds'], answer: 'Dennis Ritchie', visual: '🌟' },
        { prompt: 'Who invented dynamite?', options: ['Thomas Edison', 'Alfred Nobel', 'James Watt', 'Nikola Tesla'], answer: 'Alfred Nobel', visual: '🌟' },
        { prompt: 'The first vaccine was for?', options: ['Polio', 'Smallpox', 'Malaria', 'Cholera'], answer: 'Smallpox', visual: '🌟' },
    ],

    BUDGET_BATTLE: [
        { prompt: 'A budget is?', options: ['A list of purchases', 'A plan for income and expenses', 'Your bank balance', 'Tax paid'], answer: 'A plan for income and expenses', visual: '💳' },
        { prompt: 'If income is ₹20,000 and expenses are ₹18,000, you have a?', options: ['Deficit of ₹2,000', 'Surplus of ₹2,000', 'Balanced budget', 'Loss of ₹2,000'], answer: 'Surplus of ₹2,000', visual: '💳' },
        { prompt: 'Fixed expenses are?', options: ['Expenses that change monthly', 'Expenses that stay constant like rent', 'One-time purchases', 'Luxury spending'], answer: 'Expenses that stay constant like rent', visual: '💳' },
        { prompt: 'Variable expenses include?', options: ['Rent', 'Loan EMI', 'Groceries and utilities', 'Insurance premium'], answer: 'Groceries and utilities', visual: '💳' },
        { prompt: 'An emergency fund should cover at least?', options: ['1 week of expenses', '1 month', '3-6 months', '1 year'], answer: '3-6 months', visual: '💳' },
        { prompt: 'Credit card debt is dangerous because of?', options: ['Low interest rates', 'High interest rates compounding quickly', 'No repayment needed', 'No credit limit'], answer: 'High interest rates compounding quickly', visual: '💳' },
        { prompt: 'Compound interest is better for?', options: ['Borrowers', 'Savers/investors', 'Neither', 'Both equally'], answer: 'Savers/investors', visual: '💳' },
        { prompt: 'The 50/30/20 rule divides income into?', options: ['Savings/Wants/Needs', 'Needs/Wants/Savings', 'Taxes/Rent/Food', 'Investment/Spending/Tax'], answer: 'Needs/Wants/Savings', visual: '💳' },
        { prompt: 'Diversification in investing means?', options: ['Putting all money in one stock', 'Spreading investments across different assets', 'Saving only in cash', 'Avoiding stocks'], answer: 'Spreading investments across different assets', visual: '💳' },
        { prompt: 'Inflation of 7% means your money\'s buying power?', options: ['Increases 7%', 'Decreases by ~7%', 'Stays same', 'Doubles'], answer: 'Decreases by ~7%', visual: '💳' },
        { prompt: 'Net worth = ?', options: ['Income - Tax', 'Assets - Liabilities', 'Savings - Expenses', 'Income + Savings'], answer: 'Assets - Liabilities', visual: '💳' },
        { prompt: 'Which asset typically has best long-term returns?', options: ['Savings account', 'Fixed deposits', 'Equities/Stocks', 'Cash under mattress'], answer: 'Equities/Stocks', visual: '💳' },
        { prompt: 'Needs vs Wants: a smartphone is?', options: ['Always a need', 'Always a want', 'Depends on use case', 'Neither'], answer: 'Depends on use case', visual: '💳' },
        { prompt: 'Tax deducted at source (TDS) is?', options: ['Tax paid annually', 'Tax deducted before income reaches you', 'Tax on luxury goods', 'Import duty'], answer: 'Tax deducted before income reaches you', visual: '💳' },
        { prompt: 'Liquidity means?', options: ['Amount of water a bank holds', 'How quickly an asset can be converted to cash', 'Amount of debt', 'Interest rate'], answer: 'How quickly an asset can be converted to cash', visual: '💳' },
        { prompt: 'PPF (Public Provident Fund) is a?', options: ['Bank loan', 'Long-term government savings scheme', 'Stock market index', 'Insurance policy'], answer: 'Long-term government savings scheme', visual: '💳' },
        { prompt: 'Health insurance protects against?', options: ['Market risk', 'Medical expenses', 'Job loss', 'Property damage'], answer: 'Medical expenses', visual: '💳' },
        { prompt: 'A Ponzi scheme is?', options: ['Legal investment strategy', 'Fraud using new investors\' money to pay old ones', 'Stock trading method', 'Government bond'], answer: "Fraud using new investors' money to pay old ones", visual: '💳' },
        { prompt: 'ROI stands for?', options: ['Rate of Insurance', 'Return on Investment', 'Reserve of Interest', 'Revenue over Income'], answer: 'Return on Investment', visual: '💳' },
        { prompt: 'The safest investment option?', options: ['Cryptocurrency', 'Government bonds', 'Single company stocks', 'Forex trading'], answer: 'Government bonds', visual: '💳' },
    ],

    EQ_MAZE: [
        { prompt: 'Emotional Intelligence (EQ) is the ability to?', options: ['Solve maths quickly', 'Recognise and manage emotions', 'Run fast', 'Memorise facts'], answer: 'Recognise and manage emotions', visual: '🧘' },
        { prompt: 'Empathy means?', options: ['Feeling sorry for someone', 'Understanding and sharing another\'s feelings', 'Ignoring others\' problems', 'Being sympathetic only'], answer: "Understanding and sharing another's feelings", visual: '🧘' },
        { prompt: 'Active listening involves?', options: ['Waiting for your turn to speak', 'Fully concentrating on what is being said', 'Looking at your phone', 'Preparing your response while they talk'], answer: 'Fully concentrating on what is being said', visual: '🧘' },
        { prompt: 'When you feel angry, the healthiest response is?', options: ['Yell immediately', 'Physically act out', 'Pause, breathe, then respond thoughtfully', 'Ignore the feeling'], answer: 'Pause, breathe, then respond thoughtfully', visual: '🧘' },
        { prompt: 'Self-awareness means?', options: ['Being selfish', 'Knowing your own emotions, strengths, and weaknesses', 'Ignoring feedback', 'Being confident at all times'], answer: 'Knowing your own emotions, strengths, and weaknesses', visual: '🧘' },
        { prompt: 'Social skills in EQ involve?', options: ['Being popular', 'Managing relationships and communicating well', 'Avoiding conflict always', 'Never disagreeing'], answer: 'Managing relationships and communicating well', visual: '🧘' },
        { prompt: 'Resilience is the ability to?', options: ['Never fail', 'Bounce back from setbacks', 'Avoid challenges', 'Always win'], answer: 'Bounce back from setbacks', visual: '🧘' },
        { prompt: 'Conflict resolution best practice?', options: ['Avoid it entirely', 'Fight until you win', 'Find a mutually acceptable solution', 'Give in immediately'], answer: 'Find a mutually acceptable solution', visual: '🧘' },
        { prompt: '"I feel hurt when you interrupt me" is an example of?', options: ['Blaming statement', 'I-statement (non-blaming communication)', 'Passive aggression', 'Avoidance'], answer: 'I-statement (non-blaming communication)', visual: '🧘' },
        { prompt: 'Growth mindset believes?', options: ['Abilities are fixed', 'Abilities can be developed through effort', 'Failure is permanent', 'Smart people don\'t need to work'], answer: 'Abilities can be developed through effort', visual: '🧘' },
        { prompt: 'Peer pressure is?', options: ['Teacher assigning homework', 'Influence from people your age to act in certain ways', 'Parent advice', 'Self-motivation'], answer: 'Influence from people your age to act in certain ways', visual: '🧘' },
        { prompt: 'Stress management technique: mindfulness means?', options: ['Worrying about future', 'Focusing on present moment without judgment', 'Multitasking effectively', 'Ignoring problems'], answer: 'Focusing on present moment without judgment', visual: '🧘' },
        { prompt: 'The "fight or flight" response is triggered by?', options: ['Happiness', 'Boredom', 'Perceived threat (stress or fear)', 'Relaxation'], answer: 'Perceived threat (stress or fear)', visual: '🧘' },
        { prompt: 'Which communication style is healthiest?', options: ['Passive', 'Aggressive', 'Assertive', 'Passive-aggressive'], answer: 'Assertive', visual: '🧘' },
        { prompt: 'Gratitude practices are linked to?', options: ['Increased stress', 'Improved mental wellbeing', 'Worse relationships', 'Reduced empathy'], answer: 'Improved mental wellbeing', visual: '🧘' },
    ],
}

export const HINDI_BANKS: Record<string, Question[]> = {

    SHABDKOSH_SPRINT: [
        { prompt: '"पानी" का English?', options: ['Fire', 'Water', 'Air', 'Earth'], answer: 'Water', visual: '📚' },
        { prompt: '"School" का Hindi?', options: ['दुकान', 'विद्यालय', 'कार्यालय', 'बाज़ार'], answer: 'विद्यालय', visual: '📚' },
        { prompt: '"खुश" का अर्थ?', options: ['Sad', 'Angry', 'Happy', 'Tired'], answer: 'Happy', visual: '📚' },
        { prompt: '"सूरज" का English?', options: ['Moon', 'Star', 'Sun', 'Sky'], answer: 'Sun', visual: '📚' },
        { prompt: '"Book" को Hindi में?', options: ['कलम', 'किताब', 'कापी', 'थैला'], answer: 'किताब', visual: '📚' },
        { prompt: '"दोस्त" का English?', options: ['Enemy', 'Brother', 'Friend', 'Teacher'], answer: 'Friend', visual: '📚' },
        { prompt: '"Tree" को Hindi में?', options: ['नदी', 'पहाड़', 'पेड़', 'फूल'], answer: 'पेड़', visual: '📚' },
        { prompt: '"घर" का English?', options: ['Road', 'Home', 'Market', 'School'], answer: 'Home', visual: '📚' },
        { prompt: '"Beautiful" का Hindi?', options: ['बड़ा', 'अच्छा', 'सुंदर', 'छोटा'], answer: 'सुंदर', visual: '📚' },
        { prompt: '"नदी" का English?', options: ['Lake', 'Sea', 'River', 'Ocean'], answer: 'River', visual: '📚' },
        { prompt: '"Flower" को Hindi में?', options: ['फल', 'पत्ती', 'फूल', 'बीज'], answer: 'फूल', visual: '📚' },
        { prompt: '"आकाश" का English?', options: ['Earth', 'Sky', 'Cloud', 'Rain'], answer: 'Sky', visual: '📚' },
        { prompt: '"Brave" का Hindi अर्थ?', options: ['डरपोक', 'साहसी', 'कमज़ोर', 'आलसी'], answer: 'साहसी', visual: '📚' },
        { prompt: '"चाँद" का English?', options: ['Star', 'Sun', 'Moon', 'Planet'], answer: 'Moon', visual: '📚' },
        { prompt: '"Teacher" को Hindi में?', options: ['छात्र', 'शिक्षक', 'डॉक्टर', 'नर्स'], answer: 'शिक्षक', visual: '📚' },
        { prompt: '"हाथ" का English?', options: ['Leg', 'Hand', 'Head', 'Eye'], answer: 'Hand', visual: '📚' },
        { prompt: '"Fast" का Hindi अर्थ?', options: ['धीमा', 'तेज़', 'शांत', 'लम्बा'], answer: 'तेज़', visual: '📚' },
        { prompt: '"रात" का English?', options: ['Day', 'Noon', 'Night', 'Evening'], answer: 'Night', visual: '📚' },
        { prompt: '"Lion" को Hindi में?', options: ['हाथी', 'बाघ', 'शेर', 'भालू'], answer: 'शेर', visual: '📚' },
        { prompt: '"प्यार" का English?', options: ['Hate', 'Fear', 'Love', 'Anger'], answer: 'Love', visual: '📚' },
    ],

    VYAKARAN_WARRIOR: [
        { prompt: '"राम घर जाता है" में कर्ता कौन है?', options: ['घर', 'जाता', 'है', 'राम'], answer: 'राम', visual: '✍️' },
        { prompt: 'संज्ञा किसे कहते हैं?', options: ['क्रिया का नाम', 'किसी व्यक्ति, स्थान या चीज़ का नाम', 'विशेषण का नाम', 'क्रियाविशेषण'], answer: 'किसी व्यक्ति, स्थान या चीज़ का नाम', visual: '✍️' },
        { prompt: '"सुंदर" शब्द है?', options: ['संज्ञा', 'सर्वनाम', 'विशेषण', 'क्रिया'], answer: 'विशेषण', visual: '✍️' },
        { prompt: '"वह" किस प्रकार का सर्वनाम है?', options: ['निजवाचक', 'प्रश्नवाचक', 'पुरुषवाचक', 'संबंधवाचक'], answer: 'पुरुषवाचक', visual: '✍️' },
        { prompt: '"दौड़ना" शब्द का प्रकार?', options: ['संज्ञा', 'सर्वनाम', 'विशेषण', 'क्रिया'], answer: 'क्रिया', visual: '✍️' },
        { prompt: '"बहुत" शब्द है?', options: ['संज्ञा', 'विशेषण', 'क्रियाविशेषण', 'सर्वनाम'], answer: 'क्रियाविशेषण', visual: '✍️' },
        { prompt: 'वचन कितने प्रकार के होते हैं?', options: ['एक', 'दो', 'तीन', 'चार'], answer: 'दो', visual: '✍️' },
        { prompt: '"लड़का" का बहुवचन?', options: ['लड़के', 'लड़कियाँ', 'लड़को', 'लड़की'], answer: 'लड़के', visual: '✍️' },
        { prompt: 'लिंग के आधार पर "शेर" कौन सा लिंग है?', options: ['स्त्रीलिंग', 'नपुंसकलिंग', 'पुल्लिंग', 'उभयलिंग'], answer: 'पुल्लिंग', visual: '✍️' },
        { prompt: '"शेरनी" कौन सा लिंग है?', options: ['पुल्लिंग', 'नपुंसकलिंग', 'उभयलिंग', 'स्त्रीलिंग'], answer: 'स्त्रीलिंग', visual: '✍️' },
        { prompt: '"मैं खेल रहा हूँ" — यह किस काल में है?', options: ['भूतकाल', 'भविष्यकाल', 'वर्तमान काल', 'सामान्य काल'], answer: 'वर्तमान काल', visual: '✍️' },
        { prompt: '"मैं कल जाऊँगा" — किस काल में है?', options: ['भूतकाल', 'वर्तमान काल', 'भविष्यकाल', 'संदिग्ध काल'], answer: 'भविष्यकाल', visual: '✍️' },
        { prompt: '"मैंने खाना खाया" — किस काल में है?', options: ['वर्तमान', 'भविष्य', 'भूतकाल', 'अपूर्ण'], answer: 'भूतकाल', visual: '✍️' },
        { prompt: 'विराम चिह्न "।" किसे कहते हैं?', options: ['अल्पविराम', 'पूर्ण विराम', 'प्रश्नवाचक', 'उद्गार'], answer: 'पूर्ण विराम', visual: '✍️' },
        { prompt: '"पर्वत" का पर्यायवाची?', options: ['नदी', 'पहाड़', 'समुद्र', 'वन'], answer: 'पहाड़', visual: '✍️' },
    ],
}
