import { Question } from '../question-banks'

export const SCIENCE_BANKS: Record<string, Question[]> = {

    PLANT_POWER_GROWER: [
        { prompt: 'What do plants need to make food (photosynthesis)?', options: ['Water, sunlight, CO₂', 'Water, moonlight, O₂', 'Soil, sunlight, N₂', 'Water, CO₂, sugar'], answer: 'Water, sunlight, CO₂', visual: '🌱' },
        { prompt: 'Which part of the plant makes food?', options: ['Root', 'Stem', 'Leaf', 'Flower'], answer: 'Leaf', visual: '🌱' },
        { prompt: 'What gas do plants release during photosynthesis?', options: ['CO₂', 'N₂', 'O₂', 'H₂'], answer: 'O₂', visual: '🌱' },
        { prompt: 'Roots help plants by?', options: ['Making food', 'Absorbing water & minerals', 'Producing seeds', 'Releasing oxygen'], answer: 'Absorbing water & minerals', visual: '🌱' },
        { prompt: 'Which part carries water from roots to leaves?', options: ['Flower', 'Stem', 'Fruit', 'Seed'], answer: 'Stem', visual: '🌱' },
        { prompt: 'Chlorophyll gives leaves their?', options: ['Yellow colour', 'Red colour', 'Green colour', 'Blue colour'], answer: 'Green colour', visual: '🌱' },
        { prompt: 'A seed needs __ to germinate.', options: ['Light, water, soil', 'Water, warmth, oxygen', 'Soil, light, cold', 'Water, CO₂, light'], answer: 'Water, warmth, oxygen', visual: '🌱' },
        { prompt: 'Photosynthesis occurs in the?', options: ['Mitochondria', 'Nucleus', 'Chloroplast', 'Vacuole'], answer: 'Chloroplast', visual: '🌱' },
        { prompt: 'Transpiration is the loss of water through?', options: ['Roots', 'Stomata in leaves', 'Flowers', 'Seeds'], answer: 'Stomata in leaves', visual: '🌱' },
        { prompt: 'Which is a non-flowering plant?', options: ['Rose', 'Mango', 'Fern', 'Sunflower'], answer: 'Fern', visual: '🌱' },
        { prompt: 'Pollination is the transfer of?', options: ['Water', 'Pollen from stamen to stigma', 'Seeds to soil', 'Leaves to roots'], answer: 'Pollen from stamen to stigma', visual: '🌱' },
        { prompt: 'Which nutrient is most important for plant growth?', options: ['Oxygen', 'Nitrogen', 'Carbon', 'Hydrogen only'], answer: 'Nitrogen', visual: '🌱' },
        { prompt: 'Where does a seed develop after fertilisation?', options: ['Leaf', 'Root', 'Ovary', 'Stem'], answer: 'Ovary', visual: '🌱' },
        { prompt: 'What is the process called when plants lose water vapour?', options: ['Photosynthesis', 'Respiration', 'Transpiration', 'Germination'], answer: 'Transpiration', visual: '🌱' },
        { prompt: 'Epiphytes are plants that grow?', options: ['Underground', 'On other plants (not parasitically)', 'In water only', 'In deserts'], answer: 'On other plants (not parasitically)', visual: '🌱' },
        { prompt: 'Annual plants complete their life cycle in?', options: ['One year', 'Two years', 'Ten years', '100 years'], answer: 'One year', visual: '🌱' },
        { prompt: 'The male part of a flower is the?', options: ['Pistil', 'Stigma', 'Stamen', 'Ovary'], answer: 'Stamen', visual: '🌱' },
        { prompt: 'Xylem transports?', options: ['Sugar downward', 'Water and minerals upward', 'CO₂ inward', 'O₂ outward'], answer: 'Water and minerals upward', visual: '🌱' },
        { prompt: 'Phloem transports?', options: ['Water upward', 'Food (sugars) from leaves downward', 'Minerals from root to stem', 'O₂ from leaf'], answer: 'Food (sugars) from leaves downward', visual: '🌱' },
        { prompt: 'A cactus stores water in its?', options: ['Leaves', 'Roots', 'Stem', 'Fruit'], answer: 'Stem', visual: '🌱' },
        { prompt: 'Carnivorous plants capture insects to obtain?', options: ['Energy', 'Nitrogen', 'Water', 'Carbon'], answer: 'Nitrogen', visual: '🌱' },
        { prompt: 'The green pigment in plants is called?', options: ['Carotene', 'Chlorophyll', 'Xanthophyll', 'Anthocyanin'], answer: 'Chlorophyll', visual: '🌱' },
        { prompt: 'Fruit is a mature?', options: ['Root', 'Stem', 'Ovary containing seeds', 'Leaf'], answer: 'Ovary containing seeds', visual: '🌱' },
        { prompt: 'Which gas do plants absorb during photosynthesis?', options: ['O₂', 'N₂', 'CO₂', 'H₂'], answer: 'CO₂', visual: '🌱' },
        { prompt: 'Germination is the process by which?', options: ['Flowers bloom', 'Seeds sprout and grow', 'Plants lose leaves', 'Roots lengthen'], answer: 'Seeds sprout and grow', visual: '🌱' },
    ],

    FOOD_CHAIN_ARENA: [
        { prompt: 'Who is always at the START of a food chain?', options: ['Carnivore', 'Herbivore', 'Producer (plant)', 'Decomposer'], answer: 'Producer (plant)', visual: '🍎' },
        { prompt: 'An organism that eats plants is called?', options: ['Carnivore', 'Omnivore', 'Herbivore', 'Producer'], answer: 'Herbivore', visual: '🍎' },
        { prompt: 'A top predator is also called?', options: ['Primary consumer', 'Secondary consumer', 'Apex predator', 'Decomposer'], answer: 'Apex predator', visual: '🍎' },
        { prompt: 'Decomposers break down?', options: ['Living organisms', 'Dead organic matter', 'Sunlight', 'Minerals'], answer: 'Dead organic matter', visual: '🍎' },
        { prompt: 'In a food chain: Grass → Rabbit → Fox, the fox is?', options: ['Producer', 'Primary consumer', 'Secondary consumer', 'Decomposer'], answer: 'Secondary consumer', visual: '🍎' },
        { prompt: 'Energy transfer in a food chain is?', options: ['100% efficient', 'Always increasing', '~10% efficient', '50% efficient'], answer: '~10% efficient', visual: '🍎' },
        { prompt: 'A food web is?', options: ['One food chain', 'Multiple interconnected food chains', 'Only predators', 'Only plants'], answer: 'Multiple interconnected food chains', visual: '🍎' },
        { prompt: 'Which is an omnivore?', options: ['Cow', 'Lion', 'Bear', 'Eagle'], answer: 'Bear', visual: '🍎' },
        { prompt: 'Primary consumers eat?', options: ['Other animals', 'Plants (producers)', 'Decomposers', 'Apex predators'], answer: 'Plants (producers)', visual: '🍎' },
        { prompt: 'What happens if a prey species suddenly disappears?', options: ['Nothing changes', 'Predator population increases', 'Predator population decreases', 'More producers appear'], answer: 'Predator population decreases', visual: '🍎' },
        { prompt: 'Photosynthesis makes the energy available at which level?', options: ['Consumer', 'Decomposer', 'Producer', 'All equally'], answer: 'Producer', visual: '🍎' },
        { prompt: 'An ecological pyramid shows?', options: ['Mountain heights', 'Energy/biomass at each level', 'Population movement', 'Rainfall patterns'], answer: 'Energy/biomass at each level', visual: '🍎' },
        { prompt: 'Which relationship: both organisms benefit?', options: ['Parasitism', 'Mutualism', 'Commensalism', 'Predation'], answer: 'Mutualism', visual: '🍎' },
        { prompt: 'Parasitism means?', options: ['Both benefit', 'One benefits, other is harmed', 'One benefits, other is neutral', 'Both harmed'], answer: 'One benefits, other is harmed', visual: '🍎' },
        { prompt: 'Tertiary consumers eat?', options: ['Plants only', 'Primary consumers only', 'Secondary consumers', 'Decomposers'], answer: 'Secondary consumers', visual: '🍎' },
        { prompt: 'Which is a producer?', options: ['Grasshopper', 'Frog', 'Algae', 'Snake'], answer: 'Algae', visual: '🍎' },
        { prompt: 'Biomass is?', options: ['Total weight of organisms at a level', 'Chemical energy in soil', 'Amount of sunlight', 'Water content of soil'], answer: 'Total weight of organisms at a level', visual: '🍎' },
        { prompt: 'Which factor limits the length of food chains?', options: ['Water availability', 'Energy loss at each level', 'Soil quality', 'Temperature'], answer: 'Energy loss at each level', visual: '🍎' },
        { prompt: 'Nitrogen fixation is done by?', options: ['Plants', 'Animals', 'Bacteria in soil', 'Fungi'], answer: 'Bacteria in soil', visual: '🍎' },
        { prompt: 'Which gas cycle involves producers and consumers most directly?', options: ['Nitrogen cycle', 'Carbon cycle', 'Phosphorus cycle', 'Sulphur cycle'], answer: 'Carbon cycle', visual: '🍎' },
    ],

    SOLAR_SYSTEM_DEFENDER: [
        { prompt: 'Which planet is closest to the Sun?', options: ['Venus', 'Mars', 'Mercury', 'Earth'], answer: 'Mercury', visual: '🔭' },
        { prompt: 'The largest planet in our solar system?', options: ['Saturn', 'Neptune', 'Jupiter', 'Uranus'], answer: 'Jupiter', visual: '🔭' },
        { prompt: 'Which planet has rings visible from Earth?', options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], answer: 'Saturn', visual: '🔭' },
        { prompt: 'How many planets are in our solar system?', options: ['7', '8', '9', '10'], answer: '8', visual: '🔭' },
        { prompt: 'The Sun is a?', options: ['Planet', 'Moon', 'Star', 'Asteroid'], answer: 'Star', visual: '🔭' },
        { prompt: 'Which planet is known as the Red Planet?', options: ['Venus', 'Mars', 'Jupiter', 'Mercury'], answer: 'Mars', visual: '🔭' },
        { prompt: 'Earth is the ___ planet from the Sun?', options: ['2nd', '3rd', '4th', '5th'], answer: '3rd', visual: '🔭' },
        { prompt: 'A light year measures?', options: ['Time', 'Distance light travels in one year', 'Size of stars', 'Speed of planets'], answer: 'Distance light travels in one year', visual: '🔭' },
        { prompt: 'The Moon takes approximately how long to orbit Earth?', options: ['24 hours', '7 days', '27-28 days', '365 days'], answer: '27-28 days', visual: '🔭' },
        { prompt: 'What causes seasons on Earth?', options: ['Distance from Sun', 'Earth\'s axial tilt', 'Moon\'s gravity', 'Solar wind'], answer: "Earth's axial tilt", visual: '🔭' },
        { prompt: 'The asteroid belt is located between?', options: ['Earth and Mars', 'Mars and Jupiter', 'Jupiter and Saturn', 'Saturn and Uranus'], answer: 'Mars and Jupiter', visual: '🔭' },
        { prompt: 'Which planet spins on its side?', options: ['Neptune', 'Pluto', 'Uranus', 'Saturn'], answer: 'Uranus', visual: '🔭' },
        { prompt: 'A comet is made of?', options: ['Rock and metal only', 'Ice and dust with a tail', 'Gas and plasma', 'Water only'], answer: 'Ice and dust with a tail', visual: '🔭' },
        { prompt: 'What force keeps planets in orbit around the Sun?', options: ['Magnetism', 'Gravity', 'Friction', 'Electrostatics'], answer: 'Gravity', visual: '🔭' },
        { prompt: 'How long does Earth take to orbit the Sun?', options: ['24 hours', '30 days', '365.25 days', '100 years'], answer: '365.25 days', visual: '🔭' },
        { prompt: 'Venus is unique because it rotates?', options: ['Fastest', 'Backwards (retrograde)', 'Without spinning', 'Only at night'], answer: 'Backwards (retrograde)', visual: '🔭' },
        { prompt: 'The smallest planet in our solar system?', options: ['Mars', 'Mercury', 'Venus', 'Pluto'], answer: 'Mercury', visual: '🔭' },
        { prompt: 'Which gas is most abundant on the Sun?', options: ['Oxygen', 'Helium', 'Hydrogen', 'Nitrogen'], answer: 'Hydrogen', visual: '🔭' },
        { prompt: 'A solar eclipse occurs when?', options: ['Earth blocks sunlight from Moon', 'Moon blocks sunlight from reaching Earth', 'Earth blocks Moon', 'Sun blocks Earth'], answer: 'Moon blocks sunlight from reaching Earth', visual: '🔭' },
        { prompt: 'Which planet has the most moons?', options: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'], answer: 'Saturn', visual: '🔭' },
    ],

    FORCE_MOTION_DOJO: [
        { prompt: 'Newton\'s First Law states that objects in motion tend to?', options: ['Speed up', 'Slow down', 'Stay in motion unless a force acts', 'Stop immediately'], answer: 'Stay in motion unless a force acts', visual: '🌊' },
        { prompt: 'Force = Mass × ?', options: ['Speed', 'Velocity', 'Acceleration', 'Momentum'], answer: 'Acceleration', visual: '🌊' },
        { prompt: 'Newton\'s Third Law: every action has?', options: ['A bigger reaction', 'An equal and opposite reaction', 'No reaction', 'A smaller reaction'], answer: 'An equal and opposite reaction', visual: '🌊' },
        { prompt: 'Friction is a force that?', options: ['Speeds things up', 'Opposes motion', 'Creates gravity', 'Has no effect'], answer: 'Opposes motion', visual: '🌊' },
        { prompt: 'The unit of force is the?', options: ['Joule', 'Watt', 'Newton', 'Pascal'], answer: 'Newton', visual: '🌊' },
        { prompt: 'Which has more inertia: a heavy truck or a small car?', options: ['Small car', 'Heavy truck', 'They are equal', 'Cannot determine'], answer: 'Heavy truck', visual: '🌊' },
        { prompt: 'An object accelerates when the net force is?', options: ['Zero', 'Negative only', 'Non-zero', 'Equal to gravity'], answer: 'Non-zero', visual: '🌊' },
        { prompt: 'What force pulls objects toward Earth\'s centre?', options: ['Friction', 'Gravity', 'Normal force', 'Tension'], answer: 'Gravity', visual: '🌊' },
        { prompt: 'Weight is calculated as?', options: ['Mass × Height', 'Mass × Gravity', 'Force ÷ Area', 'Mass ÷ Volume'], answer: 'Mass × Gravity', visual: '🌊' },
        { prompt: 'A ball rolling on a frictionless surface would?', options: ['Stop eventually', 'Roll forever', 'Speed up', 'Keep the same speed forever'], answer: 'Keep the same speed forever', visual: '🌊' },
        { prompt: 'Momentum = Mass × ?', options: ['Acceleration', 'Force', 'Velocity', 'Distance'], answer: 'Velocity', visual: '🌊' },
        { prompt: 'If mass doubles and force stays constant, acceleration?', options: ['Doubles', 'Halves', 'Stays same', 'Becomes zero'], answer: 'Halves', visual: '🌊' },
        { prompt: 'The force that keeps planets in orbit is?', options: ['Friction', 'Electromagnetic', 'Gravitational', 'Nuclear'], answer: 'Gravitational', visual: '🌊' },
        { prompt: 'Work = Force × ?', options: ['Time', 'Mass', 'Distance', 'Speed'], answer: 'Distance', visual: '🌊' },
        { prompt: 'Power is defined as?', options: ['Force × Distance', 'Work ÷ Time', 'Mass × Acceleration', 'Energy × Time'], answer: 'Work ÷ Time', visual: '🌊' },
        { prompt: 'The SI unit of energy is the?', options: ['Newton', 'Watt', 'Joule', 'Pascal'], answer: 'Joule', visual: '🌊' },
        { prompt: 'A stationary object has net force of?', options: ['Maximum', 'Minimum non-zero', 'Zero', 'Equal to gravity'], answer: 'Zero', visual: '🌊' },
        { prompt: 'Terminal velocity is reached when?', options: ['Speed is maximum possible', 'Air resistance equals gravity', 'Object hits the ground', 'Mass equals force'], answer: 'Air resistance equals gravity', visual: '🌊' },
        { prompt: 'Centripetal force acts?', options: ['Away from centre', 'Toward the centre of circular motion', 'Tangentially', 'With gravity only'], answer: 'Toward the centre of circular motion', visual: '🌊' },
        { prompt: 'Which has greater potential energy: ball on ground or ball on shelf?', options: ['On the ground', 'On the shelf', 'Both equal', 'Cannot determine'], answer: 'On the shelf', visual: '🌊' },
    ],

    ELECTROSTATICS_ARENA: [
        { prompt: 'Like charges?', options: ['Attract', 'Repel', 'Have no effect', 'Cancel'], answer: 'Repel', visual: '⚡' },
        { prompt: 'Coulomb\'s Law: Force is proportional to?', options: ['Sum of charges', 'Product of charges / r²', 'Difference of charges', 'Charge × distance'], answer: 'Product of charges / r²', visual: '⚡' },
        { prompt: 'Electric field lines go from?', options: ['Negative to positive', 'Positive to negative', 'Any direction', 'Circular only'], answer: 'Positive to negative', visual: '⚡' },
        { prompt: 'The unit of electric charge is?', options: ['Volt', 'Ampere', 'Coulomb', 'Ohm'], answer: 'Coulomb', visual: '⚡' },
        { prompt: 'A conductor allows?', options: ['No charge flow', 'Free flow of charges', 'Only heat flow', 'Only light'], answer: 'Free flow of charges', visual: '⚡' },
        { prompt: 'An insulator?', options: ['Allows free charge flow', 'Restricts charge flow', 'Has no electrons', 'Acts like a conductor when heated only'], answer: 'Restricts charge flow', visual: '⚡' },
        { prompt: 'Electric potential energy is highest when?', options: ['Charges far apart (like charges)', 'Charges close together (like charges)', 'Charges are neutral', 'Charges are on conductors'], answer: 'Charges close together (like charges)', visual: '⚡' },
        { prompt: 'Voltage (V) = ?', options: ['Current × Resistance', 'Charge × Distance', 'Energy / Charge', 'Force × Time'], answer: 'Energy / Charge', visual: '⚡' },
        { prompt: 'Ohm\'s Law: V = ?', options: ['IR', 'I/R', 'R/I', 'I+R'], answer: 'IR', visual: '⚡' },
        { prompt: '1 Coulomb = how many electron charges?', options: ['6.24 × 10¹⁸', '1.6 × 10¹⁹', '6.24 × 10¹²', '1.6 × 10⁻¹⁹'], answer: '6.24 × 10¹⁸', visual: '⚡' },
        { prompt: 'Electric current is flow of?', options: ['Protons', 'Electrons (negative charge)', 'Neutrons', 'Photons'], answer: 'Electrons (negative charge)', visual: '⚡' },
        { prompt: 'Capacitance stores?', options: ['Current', 'Resistance', 'Electric energy (charge)', 'Magnetic energy'], answer: 'Electric energy (charge)', visual: '⚡' },
        { prompt: 'Gauss\'s Law relates electric flux to?', options: ['Current enclosed', 'Charge enclosed / permittivity', 'Magnetic field', 'Voltage'], answer: 'Charge enclosed / permittivity', visual: '⚡' },
        { prompt: 'Which material is the best conductor?', options: ['Glass', 'Rubber', 'Silver', 'Wood'], answer: 'Silver', visual: '⚡' },
        { prompt: 'In electrostatic induction?', options: ['Charges are transferred', 'Charges are redistributed without contact', 'Charges are created', 'Charges are destroyed'], answer: 'Charges are redistributed without contact', visual: '⚡' },
    ],

    EVOLUTION_ISLAND: [
        { prompt: 'Charles Darwin proposed evolution through?', options: ['Genetic engineering', 'Natural selection', 'Mutation only', 'Lamarckism'], answer: 'Natural selection', visual: '🧬' },
        { prompt: 'Natural selection favours individuals that?', options: ['Are strongest', 'Are fastest', 'Are best adapted to their environment', 'Live longest regardless of reproduction'], answer: 'Are best adapted to their environment', visual: '🧬' },
        { prompt: 'A mutation is?', options: ['Intentional DNA change', 'Random change in DNA sequence', 'Learned behaviour', 'Always harmful'], answer: 'Random change in DNA sequence', visual: '🧬' },
        { prompt: 'Evolution occurs at the level of?', options: ['Individual organism', 'Single cell', 'Population', 'Species only'], answer: 'Population', visual: '🧬' },
        { prompt: 'Which is evidence for evolution?', options: ['Fossil record', 'Similar DNA across species', 'Vestigial structures', 'All of these'], answer: 'All of these', visual: '🧬' },
        { prompt: 'Speciation occurs when?', options: ['Two populations cannot interbreed', 'All organisms die', 'A mutation occurs', 'Habitats merge'], answer: 'Two populations cannot interbreed', visual: '🧬' },
        { prompt: 'Lamarck\'s theory suggested that?', options: ['Traits acquired in lifetime are inherited', 'Only mutations cause evolution', 'Natural selection is the only mechanism', 'Evolution is directed'], answer: 'Traits acquired in lifetime are inherited', visual: '🧬' },
        { prompt: 'Homologous structures (like human arm and whale fin) suggest?', options: ['Same function', 'Common ancestry', 'Same environment', 'Parallel evolution'], answer: 'Common ancestry', visual: '🧬' },
        { prompt: 'Analogue structures (like bird wing and insect wing) suggest?', options: ['Common ancestry', 'Different ancestry, similar function', 'Identical genes', 'Same environment'], answer: 'Different ancestry, similar function', visual: '🧬' },
        { prompt: 'Vestigial structures are?', options: ['New adaptations', 'Remnants of structures that had function in ancestors', 'Mutations', 'Disease traits'], answer: 'Remnants of structures that had function in ancestors', visual: '🧬' },
        { prompt: 'Genetic drift has the most effect in?', options: ['Large populations', 'Small populations', 'All populations equally', 'Only isolated island species'], answer: 'Small populations', visual: '🧬' },
        { prompt: 'Isolation is important for speciation because?', options: ['It kills weaker animals', 'It prevents gene flow between populations', 'It speeds up mutation', 'It creates new environments'], answer: 'It prevents gene flow between populations', visual: '🧬' },
        { prompt: 'The modern theory of evolution combines natural selection with?', options: ['Lamarckism', 'Genetics and Mendelian heredity', 'Creationism', 'Vitalism'], answer: 'Genetics and Mendelian heredity', visual: '🧬' },
        { prompt: 'Which is NOT a mechanism of evolution?', options: ['Natural selection', 'Genetic drift', 'Gene flow', 'Inheritance of acquired traits'], answer: 'Inheritance of acquired traits', visual: '🧬' },
        { prompt: 'Adaptive radiation is when?', options: ['One species goes extinct', 'One ancestral species diversifies into many', 'Species merge', 'Habitats disappear'], answer: 'One ancestral species diversifies into many', visual: '🧬' },
    ],
}
