-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "GameType" ADD VALUE 'KIDS_TYPING';
ALTER TYPE "GameType" ADD VALUE 'TYPING_SPEED';
ALTER TYPE "GameType" ADD VALUE 'NUMBER_CATERPILLAR';
ALTER TYPE "GameType" ADD VALUE 'HOT_AIR_BALLOON_RACE';
ALTER TYPE "GameType" ADD VALUE 'APPLE_ORCHARD_COLLECTOR';
ALTER TYPE "GameType" ADD VALUE 'FISH_TANK_FILL';
ALTER TYPE "GameType" ADD VALUE 'SHAPE_SORTER_CITY';
ALTER TYPE "GameType" ADD VALUE 'PIZZA_SLICE_WARS';
ALTER TYPE "GameType" ADD VALUE 'DECIMAL_DODGE';
ALTER TYPE "GameType" ADD VALUE 'MARKET_MAYHEM';
ALTER TYPE "GameType" ADD VALUE 'FACTOR_FORTRESS';
ALTER TYPE "GameType" ADD VALUE 'FRACTION_ARROW_ARCHER';
ALTER TYPE "GameType" ADD VALUE 'RATIO_RAIL_RUSH';
ALTER TYPE "GameType" ADD VALUE 'MULTIPLIER_MAYHEM';
ALTER TYPE "GameType" ADD VALUE 'ANGLE_ASSASSIN';
ALTER TYPE "GameType" ADD VALUE 'ALGEBRA_WAVE_SURFER';
ALTER TYPE "GameType" ADD VALUE 'AREA_CONSTRUCTOR';
ALTER TYPE "GameType" ADD VALUE 'INTEGER_ICE_BATTLE';
ALTER TYPE "GameType" ADD VALUE 'DATA_DETECTIVE';
ALTER TYPE "GameType" ADD VALUE 'PROBABILITY_POKER';
ALTER TYPE "GameType" ADD VALUE 'COORDINATE_COMBAT';
ALTER TYPE "GameType" ADD VALUE 'POLYNOMIAL_PACKAGER';
ALTER TYPE "GameType" ADD VALUE 'CALCULUS_CLIFF';
ALTER TYPE "GameType" ADD VALUE 'QUADRATIC_QUEST';
ALTER TYPE "GameType" ADD VALUE 'TRIG_BRIDGE_BUILDER';
ALTER TYPE "GameType" ADD VALUE 'MATRIX_MORPH_DUEL';
ALTER TYPE "GameType" ADD VALUE 'INTEGRAL_INVADER';
ALTER TYPE "GameType" ADD VALUE 'VECTOR_SPACE_VOYAGER';
ALTER TYPE "GameType" ADD VALUE 'STATISTICS_STOCK_PROPHET';
ALTER TYPE "GameType" ADD VALUE 'NUMBER_THEORY_VAULT';
ALTER TYPE "GameType" ADD VALUE 'COMPLEX_NAVIGATOR';
ALTER TYPE "GameType" ADD VALUE 'PERMUTATION_COASTER';
ALTER TYPE "GameType" ADD VALUE 'PHONICS_POND_HOP';
ALTER TYPE "GameType" ADD VALUE 'LETTER_LASSO';
ALTER TYPE "GameType" ADD VALUE 'VOWEL_VILLAGE';
ALTER TYPE "GameType" ADD VALUE 'GRAMMAR_GLADIATOR';
ALTER TYPE "GameType" ADD VALUE 'SYNONYM_SWITCHBLADE';
ALTER TYPE "GameType" ADD VALUE 'TENSE_TREKKER';
ALTER TYPE "GameType" ADD VALUE 'PUNCTUATION_RUSH';
ALTER TYPE "GameType" ADD VALUE 'IDIOM_HUNTER';
ALTER TYPE "GameType" ADD VALUE 'COMPREHENSION_CODEBREAKER';
ALTER TYPE "GameType" ADD VALUE 'PARTS_OF_SPEECH_DUEL';
ALTER TYPE "GameType" ADD VALUE 'SENTENCE_SURFBOARD';
ALTER TYPE "GameType" ADD VALUE 'ESSAY_ENGINEER';
ALTER TYPE "GameType" ADD VALUE 'SHAKESPEARE_SHOWDOWN';
ALTER TYPE "GameType" ADD VALUE 'LITERARY_DEVICE_LAB';
ALTER TYPE "GameType" ADD VALUE 'ETYMOLOGY_EXPLORER';
ALTER TYPE "GameType" ADD VALUE 'RHETORIC_RANKER';
ALTER TYPE "GameType" ADD VALUE 'PRECIS_PRESSURE';
ALTER TYPE "GameType" ADD VALUE 'PLANT_POWER_GROWER';
ALTER TYPE "GameType" ADD VALUE 'WEATHER_WARDROBE';
ALTER TYPE "GameType" ADD VALUE 'ANIMAL_KINGDOM_SORTER';
ALTER TYPE "GameType" ADD VALUE 'SOLAR_SYSTEM_DEFENDER';
ALTER TYPE "GameType" ADD VALUE 'FOOD_CHAIN_ARENA';
ALTER TYPE "GameType" ADD VALUE 'CIRCUIT_RACER';
ALTER TYPE "GameType" ADD VALUE 'MATTER_PHASE_SHIFTER';
ALTER TYPE "GameType" ADD VALUE 'MAGNET_MAZE';
ALTER TYPE "GameType" ADD VALUE 'PERIODIC_BATTLESHIP';
ALTER TYPE "GameType" ADD VALUE 'CELL_DIVISION_DERBY';
ALTER TYPE "GameType" ADD VALUE 'FORCE_MOTION_DOJO';
ALTER TYPE "GameType" ADD VALUE 'WATER_CYCLE_WIZARD';
ALTER TYPE "GameType" ADD VALUE 'REACTION_RATE_LAB';
ALTER TYPE "GameType" ADD VALUE 'GENETICS_GENOME_DUEL';
ALTER TYPE "GameType" ADD VALUE 'ELECTROSTATICS_ARENA';
ALTER TYPE "GameType" ADD VALUE 'THERMODYNAMIC_TURBO';
ALTER TYPE "GameType" ADD VALUE 'EVOLUTION_ISLAND';
ALTER TYPE "GameType" ADD VALUE 'ORGANIC_CHEM_ARCHITECT';
ALTER TYPE "GameType" ADD VALUE 'ASTROPHYSICS_ODYSSEY';
ALTER TYPE "GameType" ADD VALUE 'OPTICS_RAY_RACER';
ALTER TYPE "GameType" ADD VALUE 'WAVE_DUEL';
ALTER TYPE "GameType" ADD VALUE 'TITRATION_TOURNAMENT';
ALTER TYPE "GameType" ADD VALUE 'MY_TOWN_EXPLORER';
ALTER TYPE "GameType" ADD VALUE 'CIVILIZATION_BUILDER';
ALTER TYPE "GameType" ADD VALUE 'LANDFORM_LANDER';
ALTER TYPE "GameType" ADD VALUE 'DEMOCRACY_DEBATE';
ALTER TYPE "GameType" ADD VALUE 'TRADE_ROUTE_TYCOON';
ALTER TYPE "GameType" ADD VALUE 'MAP_MASTERY_MISSION';
ALTER TYPE "GameType" ADD VALUE 'CONSTITUTION_COURTROOM';
ALTER TYPE "GameType" ADD VALUE 'EMPIRE_FALL';
ALTER TYPE "GameType" ADD VALUE 'CURRENT_AFFAIRS_CLASH';
ALTER TYPE "GameType" ADD VALUE 'CLIMATE_COMMANDER';
ALTER TYPE "GameType" ADD VALUE 'MACRO_ECONOMY_MASTER';
ALTER TYPE "GameType" ADD VALUE 'GEOPOLITICS_GRAND';
ALTER TYPE "GameType" ADD VALUE 'HISTORIANS_COURTROOM';
ALTER TYPE "GameType" ADD VALUE 'MICRO_MARKET_MAKER';
ALTER TYPE "GameType" ADD VALUE 'COLONIAL_CONSEQUENCE';
ALTER TYPE "GameType" ADD VALUE 'ALGORITHM_ANT';
ALTER TYPE "GameType" ADD VALUE 'BINARY_BLASTER';
ALTER TYPE "GameType" ADD VALUE 'WEB_WEAVER';
ALTER TYPE "GameType" ADD VALUE 'PYTHON_PUZZLE_PATH';
ALTER TYPE "GameType" ADD VALUE 'CYBER_SHIELD';
ALTER TYPE "GameType" ADD VALUE 'LOGIC_GATE_GARDEN';
ALTER TYPE "GameType" ADD VALUE 'DATA_STRUCTURE_DUNGEON';
ALTER TYPE "GameType" ADD VALUE 'ALGORITHM_ARENA';
ALTER TYPE "GameType" ADD VALUE 'AI_TRAINING_GROUND';
ALTER TYPE "GameType" ADD VALUE 'ENCRYPTION_ESCAPE';
ALTER TYPE "GameType" ADD VALUE 'NETWORK_TOPOLOGY_RACER';
ALTER TYPE "GameType" ADD VALUE 'DEBUG_DUEL';
ALTER TYPE "GameType" ADD VALUE 'VARNAMALA_VILLAGE';
ALTER TYPE "GameType" ADD VALUE 'MATRA_MELODY';
ALTER TYPE "GameType" ADD VALUE 'KAAVYA_COLOR';
ALTER TYPE "GameType" ADD VALUE 'SHABDKOSH_SPRINT';
ALTER TYPE "GameType" ADD VALUE 'VYAKARAN_WARRIOR';
ALTER TYPE "GameType" ADD VALUE 'HINDI_HAIKU_FACTORY';
ALTER TYPE "GameType" ADD VALUE 'ANUVAAD_ARENA';
ALTER TYPE "GameType" ADD VALUE 'KAHANI_KHATAM_KARO';
ALTER TYPE "GameType" ADD VALUE 'REGIONAL_SCRIPT_DECODER';
ALTER TYPE "GameType" ADD VALUE 'NIBANDH_NINJA';
ALTER TYPE "GameType" ADD VALUE 'NATYA_SHASTRA_SCENE';
ALTER TYPE "GameType" ADD VALUE 'SAMASA_SOLVER';
ALTER TYPE "GameType" ADD VALUE 'FLAG_FIESTA';
ALTER TYPE "GameType" ADD VALUE 'COIN_COLLECTOR';
ALTER TYPE "GameType" ADD VALUE 'CAPITALS_CONQUEST';
ALTER TYPE "GameType" ADD VALUE 'INVENTORS_WORKSHOP';
ALTER TYPE "GameType" ADD VALUE 'NATIONAL_SYMBOLS_DASH';
ALTER TYPE "GameType" ADD VALUE 'EQ_MAZE';
ALTER TYPE "GameType" ADD VALUE 'BUDGET_BATTLE';
ALTER TYPE "GameType" ADD VALUE 'TIME_AUDIT_CHALLENGE';
ALTER TYPE "GameType" ADD VALUE 'CURRENT_AFFAIRS_DETECTIVE';
ALTER TYPE "GameType" ADD VALUE 'CRITICAL_THINKERS_COURT';
ALTER TYPE "GameType" ADD VALUE 'CAREER_STRATEGIST';
ALTER TYPE "GameType" ADD VALUE 'SHOP_IT_UP';
ALTER TYPE "GameType" ADD VALUE 'CITY_PLANNER_PRO';
ALTER TYPE "GameType" ADD VALUE 'COUNTRY_COMMANDER';
ALTER TYPE "GameType" ADD VALUE 'VIRTUAL_CHEM_LAB';
ALTER TYPE "GameType" ADD VALUE 'SPACE_MISSION_CONTROL';
ALTER TYPE "GameType" ADD VALUE 'STOCK_MARKET_SAVANT';
ALTER TYPE "GameType" ADD VALUE 'ECO_FARM_MANAGER';
ALTER TYPE "GameType" ADD VALUE 'BODY_MECHANIC';
ALTER TYPE "GameType" ADD VALUE 'POWER_GRID_ENGINEER';
ALTER TYPE "GameType" ADD VALUE 'BIOREACTOR_BRAINIAC';
ALTER TYPE "GameType" ADD VALUE 'NUTRITION_KITCHEN';
ALTER TYPE "GameType" ADD VALUE 'WILDLIFE_RESERVE_RANGER';
ALTER TYPE "GameType" ADD VALUE 'GLOBAL_NEGOTIATOR';
ALTER TYPE "GameType" ADD VALUE 'BRIDGE_ARCHITECT_BLITZ';
ALTER TYPE "GameType" ADD VALUE 'PUBLIC_HEALTH_STRATEGIST';
ALTER TYPE "GameType" ADD VALUE 'MULTILINGUAL_WORD_STORM';
ALTER TYPE "GameType" ADD VALUE 'PHYSICS_OF_MUSIC';
ALTER TYPE "GameType" ADD VALUE 'LOGIC_CHAIN_REACTION';
ALTER TYPE "GameType" ADD VALUE 'GEOSPY';
ALTER TYPE "GameType" ADD VALUE 'FAKE_NEWS_FORENSICS';
ALTER TYPE "GameType" ADD VALUE 'ETHICS_ENGINE';
ALTER TYPE "GameType" ADD VALUE 'CLIMATE_TIME_MACHINE';
ALTER TYPE "GameType" ADD VALUE 'DEBATE_DOJO';
ALTER TYPE "GameType" ADD VALUE 'CRISIS_ROOM';
ALTER TYPE "GameType" ADD VALUE 'FLUID_DYNAMICS_SURFER';
ALTER TYPE "GameType" ADD VALUE 'SURVEYORS_SPRINT';
ALTER TYPE "GameType" ADD VALUE 'CULTURAL_COMPASS';
ALTER TYPE "GameType" ADD VALUE 'OLYMPIAD_QUALIFIER';

-- AlterTable
ALTER TABLE "IndependentSubscription" ADD COLUMN     "billingCycle" TEXT NOT NULL DEFAULT 'MONTHLY';

-- AlterTable
ALTER TABLE "MultiplayerMatch" ADD COLUMN     "schoolRegion" TEXT DEFAULT 'GLOBAL';

-- AlterTable
ALTER TABLE "School" ALTER COLUMN "schoolRegion" SET DEFAULT 'US';

-- AlterTable
ALTER TABLE "Subscription" ADD COLUMN     "pricePerSeat" INTEGER,
ADD COLUMN     "seats" INTEGER DEFAULT 100;

-- CreateTable
CREATE TABLE "GameQuestion" (
    "id" TEXT NOT NULL,
    "gameKey" TEXT NOT NULL,
    "gradeBand" TEXT NOT NULL,
    "subjectTag" TEXT NOT NULL,
    "skillTag" TEXT NOT NULL,
    "difficultyTier" INTEGER NOT NULL DEFAULT 2,
    "questionText" TEXT NOT NULL,
    "answerOptions" JSONB,
    "correctAnswer" TEXT NOT NULL,
    "explanation" TEXT NOT NULL DEFAULT '',
    "timeLimit" INTEGER NOT NULL DEFAULT 15,
    "distractorLogic" TEXT,
    "standardAlignment" TEXT,
    "languageLevel" TEXT NOT NULL DEFAULT 'en',
    "isGenerative" BOOLEAN NOT NULL DEFAULT false,
    "seedParams" JSONB,
    "answerFormula" TEXT,
    "validatedAt" TIMESTAMP(3),
    "validationErrors" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "GameQuestion_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "QuestionHealthLog" (
    "id" TEXT NOT NULL,
    "gameKey" TEXT NOT NULL,
    "sampleSize" INTEGER NOT NULL,
    "failures" INTEGER NOT NULL DEFAULT 0,
    "failureDetails" JSONB,
    "generatorRuns" INTEGER NOT NULL DEFAULT 0,
    "generatorFails" INTEGER NOT NULL DEFAULT 0,
    "passRate" DOUBLE PRECISION NOT NULL,
    "alertSent" BOOLEAN NOT NULL DEFAULT false,
    "runAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "QuestionHealthLog_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "GameQuestion_gameKey_gradeBand_difficultyTier_idx" ON "GameQuestion"("gameKey", "gradeBand", "difficultyTier");

-- CreateIndex
CREATE INDEX "GameQuestion_gameKey_isActive_idx" ON "GameQuestion"("gameKey", "isActive");

-- CreateIndex
CREATE INDEX "GameQuestion_subjectTag_gradeBand_idx" ON "GameQuestion"("subjectTag", "gradeBand");

-- CreateIndex
CREATE INDEX "QuestionHealthLog_gameKey_runAt_idx" ON "QuestionHealthLog"("gameKey", "runAt");

-- CreateIndex
CREATE INDEX "QuestionHealthLog_runAt_idx" ON "QuestionHealthLog"("runAt");

-- CreateIndex
CREATE INDEX "MatchParticipant_isWinner_name_idx" ON "MatchParticipant"("isWinner", "name");

-- CreateIndex
CREATE INDEX "User_schoolId_xp_idx" ON "User"("schoolId", "xp" DESC);
