
import { MathEngine } from '../lib/game-engine/math-engine';

const DIFFICULTIES = ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'CHALLENGE'] as const;
const ITERATIONS = 2000;

console.log(`Starting MathEngine Validation (${ITERATIONS} iterations per difficulty)...\n`);

let totalErrors = 0;

DIFFICULTIES.forEach(diff => {
    console.log(`Testing Difficulty: ${diff}`);
    let errors = 0;
    let allowNegatives = diff === 'ADVANCED' || diff === 'CHALLENGE';

    for (let i = 0; i < ITERATIONS; i++) {
        try {
            const problem = MathEngine.generateProblem({
                difficulty: diff,
                allowNegatives: allowNegatives
            });

            // 1. Basic Type Checks
            if (!problem || typeof problem.expression !== 'string' || typeof problem.answer !== 'number') {
                console.error(`[FAIL] Invalid format`, problem);
                errors++;
                continue;
            }

            // 2. NaN / Infinity Check
            if (!Number.isFinite(problem.answer)) {
                console.error(`[FAIL] Non-finite answer: ${problem.answer} for ${problem.expression}`);
                errors++;
                continue;
            }

            // 3. Verify Calculation
            // Replace visual operators with JS operators
            const evalExpr = problem.expression
                .replace(/×/g, '*')
                .replace(/÷/g, '/');

            // Eval is safe here as input is generated by us
            // eslint-disable-next-line no-eval
            const calculated = eval(evalExpr);

            // Floating point tolerance
            if (Math.abs(calculated - problem.answer) > 0.001) {
                console.error(`[FAIL] Mismatch: ${problem.expression} = ${problem.answer}, calculated: ${calculated}`);
                errors++;
            }

            // 4. Formatting Checks
            if (problem.expression.includes('--')) {
                console.error(`[FAIL] Double negative: ${problem.expression}`);
                errors++;
            }

            // Check for trailing operators
            if (/[\+\-\*\/]$/.test(evalExpr)) {
                console.error(`[FAIL] Trailing operator: ${problem.expression}`);
                errors++;
            }

        } catch (e) {
            console.error(`[CRITICAL] Exception generating problem for ${diff}:`, e);
            errors++;
        }
    }

    if (errors === 0) {
        console.log(`✅ ${diff}: Passed ${ITERATIONS} tests.`);
    } else {
        console.log(`❌ ${diff}: Failed ${errors} tests.`);
    }
    totalErrors += errors;
    console.log('---');
});

if (totalErrors === 0) {
    console.log('\n🎉 ALL TESTS PASSED! MathEngine is robust.');
    process.exit(0);
} else {
    console.error(`\n💀 Validation Failed with ${totalErrors} total errors.`);
    process.exit(1);
}
